/// File: src/lib/spanishCommonWords.ts
//
// A base layer of English glosses for the ~790 Spanish words that occur 2+
// times across the podcast transcripts (function words, pronouns, and
// high-frequency verbs/adjectives like "antes", "aunque", "mismo") — words
// too basic to belong in a curated per-episode vocabulary list, but which
// students still hover over expecting a translation. PodcastModule merges
// this under each episode's `vocabulary` list so effectively every word a
// student is likely to hover over — not just the ~10 curated key terms —
// shows an English meaning. Keys are accent-stripped, lowercase, matching
// PodcastModule's normalizeWord().

export const COMMON_WORD_GLOSSES: Record<string, string> = {
  de: "of / from",
  que: "that / which / what",
  la: "the",
  y: "and",
  en: "in / on",
  el: "the",
  a: "to / at",
  es: "is",
  un: "a / an",
  no: "no / not",
  los: "the (pl.)",
  las: "the (pl., fem.)",
  con: "with",
  por: "for / by / through",
  mas: "more",
  una: "a / an (fem.)",
  para: "for / in order to",
  tambien: "also / too",
  como: "like / as / how",
  eso: "that",
  se: "himself / herself / oneself",
  pero: "but",
  lo: "it / the",
  si: "if / yes",
  jovenes: "young people",
  identidad: "identity",
  porque: "because",
  o: "or",
  sobre: "about / on",
  solo: "only",
  su: "his / her / its / their",
  al: "to the",
  del: "of the",
  totalmente: "totally",
  muy: "very",
  puede: "can / is able to",
  todo: "everything / all",
  me: "me / myself",
  sus: "his / her / their (pl.)",
  verdad: "truth",
  hay: "there is / there are",
  cada: "each / every",
  inteligencia: "intelligence",
  artificial: "artificial",
  todos: "everyone / all",
  yo: "I",
  hoy: "today",
  tema: "topic / theme",
  nos: "us / ourselves",
  cambio: "change",
  muchos: "many",
  episodio: "episode",
  son: "are",
  gente: "people",
  social: "social",
  personas: "people",
  poco: "a little / few",
  importante: "important",
  esta: "this / is",
  hasta: "until / even",
  familia: "family",
  ver: "to see",
  te: "you / yourself",
  aunque: "although / even though",
  algunos: "some",
  tanto: "so much",
  quien: "who",
  ni: "nor / not even",
  mucho: "a lot / much",
  viaje: "trip / journey",
  fue: "was / went",
  sin: "without",
  hacer: "to do / make",
  hablar: "to speak / talk",
  redes: "networks",
  sociales: "social (pl.)",
  parte: "part",
  exacto: "exact / exactly",
  bueno: "good / well",
  ejemplo: "example",
  tu: "you / your",
  mundo: "world",
  vida: "life",
  problema: "problem",
  dos: "two",
  creo: "I think / believe",
  tiene: "has",
  trabajo: "work / job",
  acuerdo: "agreement",
  preguntas: "questions",
  muchas: "many (fem.)",
  vez: "time (occurrence)",
  soy: "I am",
  forma: "form / way",
  mi: "my",
  comunidad: "community",
  sea: "be (subjunctive)",
  cuando: "when",
  estan: "are (estar)",
  entre: "between / among",
  ese: "that",
  ser: "to be",
  veces: "times",
  final: "end / final",
  ha: "has (auxiliary)",
  hace: "does / makes / ago",
  pueden: "can / are able to",
  aprendi: "I learned",
  algo: "something",
  tecnologia: "technology",
  ya: "already / now",
  climatico: "climate (adj.)",
  bienvenidos: "welcome",
  podcast: "podcast",
  colegio: "school",
  ahora: "now",
  tiempo: "time / weather",
  estudios: "studies",
  otros: "others",
  lado: "side",
  claro: "of course / clear",
  otro: "other / another",
  casa: "house / home",
  donde: "where",
  hablando: "talking / speaking",
  este: "this",
  hecho: "fact / done",
  vocabulario: "vocabulary",
  proxima: "next",
  viajar: "to travel",
  punto: "point",
  increible: "incredible",
  experiencia: "experience",
  educacion: "education",
  voluntariado: "volunteering",
  espana: "Spain",
  antes: "before",
  horas: "hours",
  nadie: "nobody",
  digital: "digital",
  real: "real",
  sienten: "they feel",
  tienen: "they have",
  interesante: "interesting",
  da: "gives",
  ropa: "clothes",
  todavia: "still / yet",
  eres: "you are",
  culturas: "cultures",
  tipo: "type / kind",
  podemos: "we can",
  otra: "another (fem.)",
  simplemente: "simply",
  uso: "use",
  propia: "own (fem.)",
  sido: "been",
  haya: "have (subjunctive)",
  contestar: "to answer",
  desde: "since / from",
  despues: "after / afterward",
  existen: "exist",
  algun: "some",
  comida: "food",
  ademas: "besides / also",
  incluso: "even / including",
  gobiernos: "governments",
  organizacion: "organization",
  acciones: "actions",
  menos: "less",
  afecta: "affects",
  especialmente: "especially",
  quienes: "who (pl.)",
  misma: "same (fem.)",
  fotos: "photos",
  especie: "kind / species",
  siempre: "always",
  hablan: "they speak",
  parece: "seems",
  mucha: "a lot (fem.)",
  usa: "uses",
  muestran: "they show",
  mejor: "better / best",
  diferentes: "different",
  intereses: "interests",
  ellos: "they",
  internet: "internet",
  miles: "thousands",
  aprender: "to learn",
  completamente: "completely",
  ninguna: "none / not any",
  pais: "country",
  formas: "ways / forms",
  religion: "religion",
  tradiciones: "traditions",
  tan: "so",
  entiendan: "they understand (subjunctive)",
  terminar: "to finish",
  segun: "according to",
  tenemos: "we have",
  varias: "several (fem.)",
  esto: "this",
  olvideis: "forget (subjunctive, \"no olvidéis\" = don't forget)",
  comprension: "comprehension",
  nuevo: "new",
  experiencias: "experiences",
  peru: "Peru",
  bolivia: "Bolivia",
  dias: "days",
  joven: "young / young person",
  paso: "step / pace",
  hablamos: "we speak",
  buen: "good",
  muchisimo: "so much / a lot",
  manera: "way / manner",
  cosas: "things",
  principio: "beginning",
  durante: "during",
  clave: "key",
  aprenden: "they learn",
  nosotros: "we",
  cambiando: "changing",
  pocos: "few",
  anos: "years",
  han: "have (auxiliary, pl.)",
  artistas: "artists",
  revolucion: "revolution",
  importancia: "importance",
  depende: "depends",
  bien: "well",
  semana: "week",
  uno: "one",
  comunitario: "community (adj.)",
  sociedad: "society",
  papel: "role / paper",
  paises: "countries",
  contra: "against",
  empresas: "companies",
  emisiones: "emissions",
  agricultura: "agriculture",

  // Second pass: words occurring 2+ times across the 15 episodes, still
  // uncovered by the first pass above or by any episode's curated vocabulary.
  salud: "health",
  presion: "pressure",
  dia: "day",
  plastico: "plastic",
  estudiantes: "students",
  repasar: "to review",
  coches: "cars",
  esa: "that (fem.)",
  videojuegos: "video games",
  dinero: "money",
  millones: "millions",
  fiesta: "party / festival",
  cualquier: "any",
  transporte: "transport",
  ciudades: "cities",
  vamos: "we go / let's go",
  he: "I have (auxiliary)",
  cuerpo: "body",
  pronto: "soon",
  tradicionales: "traditional",
  enorme: "enormous",
  dicho: "said",
  ano: "year",
  tener: "to have",
  reducir: "to reduce",
  generacion: "generation",
  mental: "mental",
  moda: "fashion",
  informacion: "information",
  primer: "first",
  personal: "personal",
  dicen: "they say",
  pueblo: "town / village",
  exactamente: "exactly",
  dificil: "difficult",
  mismo: "same / itself",
  trabajos: "jobs",
  verano: "summer",
  examenes: "exams",
  colegios: "schools",
  llama: "calls / is called",
  olvidar: "to forget",
  mis: "my (pl.)",
  profesional: "professional",
  importantes: "important (pl.)",
  rapido: "fast / quickly",
  futuro: "future",
  problemas: "problems",
  solucion: "solution",
  calles: "streets",
  amigos: "friends",
  adolescentes: "adolescents / teens",
  crees: "you believe",
  gracias: "thanks",
  encontrar: "to find",
  usar: "to use",
  e: "and (before i-/hi- words)",
  padres: "parents",
  meses: "months",
  edad: "age",
  musica: "music",
  bonito: "pretty / nice",
  momento: "moment",
  diferente: "different",
  esas: "those (fem.)",
  estilo: "style",
  expertos: "experts",
  coche: "car",
  encanta: "loves",
  varios: "several",
  les: "to them",
  participar: "to participate",
  sistema: "system",
  grandes: "big / large (pl.)",
  debate: "debate",
  responsabilidad: "responsibility",
  le: "to him / her",
  grande: "big",
  alguien: "someone",
  nunca: "never",
  idea: "idea",
  esports: "esports",
  jugadores: "players",
  sistemas: "systems",
  politica: "politics",
  global: "global",
  cambia: "changes",
  fascinante: "fascinating",
  casi: "almost",
  pasa: "happens",
  injusto: "unfair",
  cultura: "culture",
  ayuda: "help",
  grupo: "group",
  leido: "read (past participle)",
  aspecto: "aspect",
  espanol: "Spanish",
  propio: "own",
  seguir: "to continue / follow",
  nuestra: "our (fem.)",
  imagen: "image",
  serio: "serious",
  abiertamente: "openly",
  asi: "like this / so",
  sur: "south",
  impacto: "impact",
  duda: "doubt",
  dificiles: "difficult (pl.)",
  estar: "to be",
  solos: "alone (pl.)",
  toda: "all / whole (fem.)",
  muchisimas: "so many (fem.)",
  estaba: "was (imperfect)",
  peligrosa: "dangerous (fem.)",
  jaja: "haha",
  perfecto: "perfect",
  noticias: "news",
  historia: "history / story",
  ti: "you (object)",
  lecciones: "lessons",
  velocidad: "speed",
  cuenta: "account / realizes",
  dejar: "to leave / let",
  van: "they go",
  sabia: "knew (imperfect)",
  decir: "to say",
  era: "was (imperfect)",
  actividades: "activities",
  falta: "lack / is missing",
  proyectos: "projects",
  mientras: "while",
  visto: "seen",
  empezo: "began",
  voz: "voice",
  mayoria: "majority",
  zonas: "zones / areas",
  sentido: "sense / meaning",
  preocupante: "worrying",
  sino: "but rather",
  accion: "action",
  ejercicio: "exercise",
  perder: "to lose",
  intento: "I try / attempt",
  fisico: "physical",
  traves: "through (\"a través de\")",
  persona: "person",
  estas: "these / you are",
  parecido: "similar",
  deporte: "sport",
  resolver: "to solve",
  bicicletas: "bicycles",
  academica: "academic (fem.)",
  bolsas: "bags",
  nuestro: "our",
  viajes: "trips",
  psicologos: "psychologists",
  genera: "generates",
  realidad: "reality",
  cara: "face / expensive (fem.)",
  puedes: "you can",
  sentirte: "to feel (yourself)",
  ensenan: "they teach",
  esos: "those",
  pensar: "to think",
  mundos: "worlds",
  valores: "values",
  fundamental: "fundamental",
  camino: "path / way",
  decisiones: "decisions",
  suficiente: "enough",
  va: "goes",
  alla: "there",
  fisica: "physical (fem.) / physics",
  buena: "good (fem.)",
  pregunta: "question",
  esperamos: "we hope",
  os: "you all (object, Spain)",
  reflexionar: "to reflect",
  practicar: "to practice",
  especial: "special",
  cuentanos: "tell us",
  hice: "I did / made",
  local: "local",
  suerte: "luck",
  carnaval: "carnival",
  otras: "other (fem. pl.)",
  agua: "water",
  habia: "there was / were",
  cuanto: "how much",
  cuidado: "care",
  tren: "train",
  materiales: "materials",
  tenia: "had (imperfect)",
  mejorar: "to improve",
  reales: "real (pl.)",
  ningun: "no / not any",
  compartir: "to share",
  chicos: "guys / boys",
  concreto: "concrete / specific",
  programas: "programs",
  crear: "to create",
  humanos: "humans",
  algunas: "some (fem.)",
  nuevas: "new (fem. pl.)",
  decadas: "decades",
  podrian: "could",
  nuevos: "new (pl.)",
  pasando: "happening",
  cambiar: "to change",
  existe: "exists",
  escuchamos: "we listen",
  has: "you have",
  fines: "\"fines de semana\" = weekends",
  primera: "first (fem.)",
  recursos: "resources",
  sorprendio: "surprised",
  tenian: "they had",
  mayor: "older / bigger",
  pequenos: "small (pl.)",
  nuestras: "our (fem. pl.)",
  acceso: "access",
  espero: "I hope",
  consecuencias: "consequences",
  medidas: "measures",
  impresionante: "impressive",
  oir: "to hear",
  habitos: "habits",
  usan: "they use",
  mano: "hand",
  cien: "one hundred",
  espanolas: "Spanish (fem. pl.)",
  energia: "energy",
  vivir: "to live",
  normalmente: "normally",
  pobres: "poor",
  consejo: "advice",
  pequena: "small (fem.)",
  dietas: "diets",
  ven: "they see",
  cientifica: "scientific (fem.)",
  estres: "stress",
  haces: "you do",
  opinas: "you think / opine",
  fenomeno: "phenomenon",
  deberia: "should",
  quiero: "I want",
  amigo: "friend",
  tatuajes: "tattoos",
  cierto: "true / certain",
  sigue: "continues",
  delante: "in front",
  alguna: "some (fem.)",
  clientes: "customers",
  primeros: "first (pl.)",
  aprendizaje: "learning",
  esfuerzo: "effort",
  profesionales: "professional (pl.)",
  rapidamente: "quickly",
  electricos: "electric",
  publico: "public",
  activismo: "activism",
  educativos: "educational",
  estudiante: "student",
  aprendimos: "we learned",
  hola: "hello",
  barrio: "neighborhood",
  instagram: "Instagram",
  tiktok: "TikTok",
  curioso: "curious",
  mejores: "best (pl.)",
  momentos: "moments",
  sube: "goes up / uploads",
  mal: "bad",
  crea: "creates",
  coincide: "coincides",
  parecer: "to seem",
  positivo: "positive",
  permiten: "they allow",
  tus: "your (pl.)",
  gustos: "tastes",
  construir: "to build",
  riesgos: "risks",
  necesidad: "need",
  gusta: "is pleasing (gustar)",
  marca: "brand",
  delicado: "delicate",
  completa: "complete (fem.)",
  complicada: "complicated (fem.)",
  pertenecen: "they belong",
  sociologos: "sociologists",
  llaman: "they call",
  alli: "there",
  mezcla: "mix",
  convierte: "becomes / converts",
  entender: "to understand",
  perspectiva: "perspective",
  identifican: "they identify",
  queremos: "we want",
  corporal: "bodily",
  perfectos: "perfect (pl.)",
  negativamente: "negatively",
  estos: "these",
  temas: "topics",
  vuestra: "your (pl., fem.)",
  pase: "happened / I spent (time)",
  tres: "three",
  viajando: "traveling",
  sudamerica: "South America",
  ahi: "there",
  ecuador: "Ecuador",
  argentina: "Argentina",
  buenos: "good (pl.)",
  cuatro: "four",
  montana: "mountain",
  tiendas: "shops / tents",
  nubes: "clouds",
  verdadero: "true / real",
  rito: "rite",
  iniciacion: "initiation",
  marcan: "they mark",
  precisamente: "precisely",
  adulta: "adult (fem.)",
  igual: "same / equal",
  posibilidad: "possibility",
  tuve: "I had",
  representan: "they represent",
  catolica: "Catholic (fem.)",
  imagino: "I imagine",
  color: "color",
  caliente: "hot",
  cosa: "thing",
  probe: "I tried",
  plato: "dish",
  pescado: "fish (food)",
  carne: "meat",
  tienes: "you have",
  dentro: "inside",
  barato: "cheap",
  eran: "were (they)",
  tuviste: "you had",
  senti: "I felt",
  fatal: "terrible",
  recuerdos: "memories",
  conocer: "to know / meet",
  tanta: "so much (fem.)",
  entendi: "I understood",
  vista: "view / sight",
  situaciones: "situations",
  tantas: "so many (fem.)",
  nuestros: "our (pl.)",
  oyentes: "listeners",
  excelente: "excellent",
  tenga: "have (subjunctive)",
  sitio: "place",
  recordad: "remember (command)",
  escuchar: "to listen",
  comprobar: "to check / verify",
  parecia: "seemed",
  ciencia: "science",
  movil: "mobile phone",
  arte: "art",
  maquina: "machine",
  buenas: "good (fem. pl.)",
  dolares: "dollars",
  pedir: "to ask for",
  util: "useful",
  riesgo: "risk",
  humano: "human",
  significa: "means",
  miedo: "fear",
  proximas: "next (fem. pl.)",
  industrial: "industrial",
  siquiera: "even (\"ni siquiera\" = not even)",
  ensena: "teaches",
  ciertos: "certain (pl.)",
  unos: "some / a few",
  continua: "continuous / continues",
  accidente: "accident",
  decidir: "to decide",
  consigue: "achieves / gets",
  respuesta: "answer",
  clara: "clear (fem.)",
  union: "union",
  europea: "European (fem.)",
  intenta: "tries",
  proteger: "to protect",
  enfermedades: "diseases",
  creatividad: "creativity",
  humana: "human (fem.)",
  relacionado: "related",
  pasado: "past",
  trabaje: "I worked",
  preparar: "to prepare",
  ciudad: "city",
  sentia: "felt",
  necesita: "needs",
  sentirse: "to feel (oneself)",
  demuestra: "demonstrates",
  apoyo: "support",
  fuerte: "strong",
  gobierno: "government",
  organizaciones: "organizations",
  programa: "program",
  ninos: "children",
  deberes: "homework",
  par: "pair / couple",
  recibe: "receives",
  jugar: "to play",
  pequenas: "small (fem. pl.)",
  asociaciones: "associations",
  ante: "before / in the face of",
  modelo: "model",
  educativo: "educational",
  calidad: "quality",
  complejo: "complex",
  seguro: "sure / insurance",
  lucha: "fight / struggle",
  hemos: "we have",
  movimiento: "movement",
  activistas: "activists",
  escolares: "school (adj., pl.)",
  clima: "climate",
  extendio: "spread",
  calle: "street",
  exigir: "to demand",
  encontrado: "found",
  segunda: "second (fem.)",
  actual: "current",
  responsables: "responsible (pl.)",
  gases: "gases",
  importa: "matters",
  politicas: "policies",
  nivel: "level",
  oficial: "official",
  pues: "well / so",
  creando: "creating",
  europa: "Europe",
  calor: "heat",
  sufren: "they suffer",
  ambiental: "environmental",
  familias: "families",
  ambiente: "environment",
  sabe: "knows",
  vuestro: "your (pl.)",
  sentimos: "we feel",
  cerca: "near",
  chicas: "girls",
  suelen: "they tend to",
  sentir: "to feel",
  peor: "worse",
  entrenadores: "trainers / coaches",
  permitirse: "to afford",
  constante: "constant",
  trastornos: "disorders",
  alimentacion: "nutrition / food",
  diez: "ten",
  alarmante: "alarming",
  aprendan: "they learn (subjunctive)",
  distinguir: "to distinguish",
  general: "general",
  depresion: "depression",
  ayudo: "helped",
  hablara: "talked / would talk (subjunctive)",
  estaban: "they were",
  emocional: "emotional",
  cuidar: "to take care of",
  trato: "I try / treatment",
  estrategia: "strategy",
  obsesion: "obsession",
  siente: "feels",
  elementos: "elements",
  tatuaje: "tattoo",
  dijo: "said",
  ve: "sees",
  normal: "normal",
  expresion: "expression",
  visible: "visible",
  derecho: "right / law",
  uniformes: "uniforms",
  evitar: "to avoid",
  mostrar: "to show",
  gran: "great / big",
  dar: "to give",
  particular: "particular",
  somos: "we are",
  economica: "economic (fem.)",
  comprar: "to buy",
  famosas: "famous (fem. pl.)",
  toros: "bulls",
  prefiero: "I prefer",
  cadiz: "Cádiz",
  humor: "humor",
  politicos: "politicians",
  epoca: "era / time",
  restaurante: "restaurant",
  quizas: "maybe",
  camareros: "waiters",
  comer: "to eat",
  ganar: "to earn / win",
  sinceramente: "sincerely",
  valor: "value",
  trabajar: "to work",
  equipo: "team",
  companeros: "colleagues / classmates",
  paciencia: "patience",
  estoy: "I am",
  pesar: "weight (\"a pesar de\" = despite)",
  jugando: "playing",
  sepa: "know (subjunctive)",
  organizadas: "organized (fem. pl.)",
  internacionales: "international (pl.)",
  tradicional: "traditional",
  autenticas: "authentic (fem. pl.)",
  mundial: "world (adj.)",
  juego: "game",
  beneficios: "benefits",
  valida: "valid (fem.)",
  quedar: "to meet up / stay",
  inteligentes: "smart / intelligent (pl.)",
  prohibir: "to prohibit",
  realmente: "really",
  medioambiental: "environmental",
  recientes: "recent",
  contaminacion: "pollution",
  preocupa: "worries",
  alta: "high (fem.)",
  comparte: "shares",
  cuestion: "matter / issue",
  semanas: "weeks",
  participacion: "participation",
  combinando: "combining",
  directamente: "directly",
  corea: "Korea",
  examen: "exam",
  unico: "unique / only",
  finlandia: "Finland",
  bachillerato: "baccalaureate / high-school diploma",
  internacional: "international",
  depender: "to depend",
  basura: "garbage",
  tortugas: "turtles",
  pajitas: "straws",
  triste: "sad",
  productos: "products",
  siguen: "they continue",
  asuman: "they take on (subjunctive)",
  demasiado: "too much",
  ricos: "rich",
};
