/// scripts/gap_questions_bank.cjs
/// 500+ questions covering the IB Spanish B SL exam gaps:
///   1. False cognates  (~70 Qs)
///   2. Relative clauses (~70 Qs)
///   3. Affirmative imperative (~70 Qs)
///   4. Por vs. Para  (~60 Qs)
///   5. Passive voice  (~50 Qs)
///   6. Heading-match (MCQ paragraph-heading) (~50 Qs)
///   7. Word-bank gap-fill MCQ (~60 Qs)
///   8. Sharing the Planet extra (~60 Qs)
///   9. Pluperfect / Perfect tense (~30 Qs)
///  10. Advanced grammar mixed (~30 Qs)

const questions = [

  // =========================================================================
  // 1. FALSE COGNATES / TRICKY VOCABULARY (~70 questions)
  // =========================================================================

  { id:"gap-fc-1", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] 'Estoy muy embarazada.' ¿Qué significa 'embarazada' en inglés?", options:["pregnant","embarrassed","bothered","emotional"], correctAnswer:"pregnant", difficulty:"hard", points:30, explanation:"TRAP: 'embarazada' = pregnant. 'Embarrassed' = avergonzado/a." },
  { id:"gap-fc-2", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] '¿Puedes presentarme a tu hermana?' 'Presentar' en este contexto significa:", options:["to introduce","to present a gift","to present a speech","to show"], correctAnswer:"to introduce", difficulty:"medium", points:20, explanation:"'Presentar a alguien' = to introduce someone (not just 'to present')." },
  { id:"gap-fc-3", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] 'Estoy muy sensible hoy.' ¿Qué significa 'sensible' en español?", options:["sensitive","sensible / reasonable","sensational","careful"], correctAnswer:"sensitive", difficulty:"hard", points:30, explanation:"TRAP: Spanish 'sensible' = sensitive. English 'sensible' = sensato/razonable." },
  { id:"gap-fc-4", themeId:"experiences", type:"mcq", prompt:"[Falsos amigos] 'Mi padre es muy exitoso.' ¿Qué significa 'exitoso'?", options:["successful","exciting","extraordinary","expensive"], correctAnswer:"successful", difficulty:"hard", points:30, explanation:"'Exitoso' = successful. 'Exciting' = emocionante." },
  { id:"gap-fc-5", themeId:"experiences", type:"mcq", prompt:"[Falsos amigos] 'El argumento de la película es interesante.' ¿Qué significa 'argumento' aquí?", options:["plot / storyline","argument / disagreement","article","argument in a debate"], correctAnswer:"plot / storyline", difficulty:"hard", points:30, explanation:"'Argumento' in literature = plot. An English 'argument' = una discusión." },
  { id:"gap-fc-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Falsos amigos] 'El colegio tiene una librería enorme.' ¿Qué es una 'librería'?", options:["bookshop / bookstore","library","library card","bookcase"], correctAnswer:"bookshop / bookstore", difficulty:"hard", points:30, explanation:"TRAP: 'Librería' = bookshop. A library = una biblioteca." },
  { id:"gap-fc-7", themeId:"human-ingenuity", type:"mcq", prompt:"[Falsos amigos] 'Es una persona muy simpática.' ¿Qué significa 'simpático/a'?", options:["friendly / nice","pathetic","sympathetic","simple"], correctAnswer:"friendly / nice", difficulty:"medium", points:20, explanation:"'Simpático' = friendly/likeable. 'Sympathetic' = comprensivo." },
  { id:"gap-fc-8", themeId:"social-organization", type:"mcq", prompt:"[Falsos amigos] 'El político realizó una lectura del informe.' ¿Qué significa 'lectura'?", options:["reading / lecture (as in a text reading)","lecture (university talk)","lesson","law"], correctAnswer:"reading / lecture (as in a text reading)", difficulty:"hard", points:30, explanation:"'Lectura' = the act of reading a text. A university 'lecture' = una conferencia." },
  { id:"gap-fc-9", themeId:"social-organization", type:"mcq", prompt:"[Falsos amigos] 'Voy a asistir a la reunión mañana.' ¿Qué significa 'asistir a' algo?", options:["to attend","to assist / help with","to watch","to arrange"], correctAnswer:"to attend", difficulty:"hard", points:30, explanation:"TRAP: 'Asistir a' = to attend. 'To assist' = ayudar / asistir en." },
  { id:"gap-fc-10", themeId:"sharing-planet", type:"mcq", prompt:"[Falsos amigos] 'La fábrica contamina el río.' ¿Qué es una 'fábrica'?", options:["factory","fabric","fabrication","laboratory"], correctAnswer:"factory", difficulty:"medium", points:20, explanation:"'Fábrica' = factory. 'Fabric' = la tela." },
  { id:"gap-fc-11", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] 'Los actores son muy grandes.' ¿Qué significa 'grandes' aquí?", options:["great / important","tall / big physically","old","enormous"], correctAnswer:"great / important", difficulty:"medium", points:20, explanation:"'Grande' often means 'great' or 'important', not just physically big." },
  { id:"gap-fc-12", themeId:"experiences", type:"mcq", prompt:"[Falsos amigos] '¿Cuándo es tu cumpleaños?' ¿Qué es un 'cumpleaños'?", options:["birthday","anniversary","holiday","celebration"], correctAnswer:"birthday", difficulty:"easy", points:10, explanation:"'Cumpleaños' = birthday (the day you 'complete' another year)." },
  { id:"gap-fc-13", themeId:"human-ingenuity", type:"mcq", prompt:"[Falsos amigos] 'La conferencia de prensa fue un éxito.' ¿Qué es una 'conferencia'?", options:["press conference","a lecture at university","a conference call","a conflict"], correctAnswer:"press conference", difficulty:"medium", points:20 },
  { id:"gap-fc-14", themeId:"social-organization", type:"mcq", prompt:"[Falsos amigos] 'El fiscal acusó al criminal.' ¿Qué es un 'fiscal'?", options:["prosecutor","physical trainer","tax collector","fiscal manager"], correctAnswer:"prosecutor", difficulty:"hard", points:30, explanation:"'El fiscal' = the public prosecutor. 'Fiscal' in English relates to finances." },
  { id:"gap-fc-15", themeId:"sharing-planet", type:"mcq", prompt:"[Falsos amigos] 'Hay que conservar los recursos naturales.' ¿Qué significa 'conservar'?", options:["to preserve / conserve","to observe carefully","to reserve","to consider"], correctAnswer:"to preserve / conserve", difficulty:"easy", points:10 },
  { id:"gap-fc-16", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] 'Voy a realizar mi sueño de estudiar en el extranjero.' ¿Qué significa 'realizar'?", options:["to achieve / fulfill","to realize (understand)","to release","to relax"], correctAnswer:"to achieve / fulfill", difficulty:"hard", points:30, explanation:"'Realizar' = to carry out / achieve. 'To realize' (understand) = darse cuenta de." },
  { id:"gap-fc-17", themeId:"experiences", type:"mcq", prompt:"[Falsos amigos] '¿Qué opina usted de la situación?' ¿Qué significa 'opinar'?", options:["to have an opinion / to think","to operate","to oppose","to offer"], correctAnswer:"to have an opinion / to think", difficulty:"medium", points:20 },
  { id:"gap-fc-18", themeId:"human-ingenuity", type:"mcq", prompt:"[Falsos amigos] 'Escribe un resumen del artículo.' ¿Qué es un 'resumen'?", options:["summary","resume / CV","result","research"], correctAnswer:"summary", difficulty:"medium", points:20, explanation:"'Resumen' = summary. A 'resume' (CV) = un currículum vitae." },
  { id:"gap-fc-19", themeId:"social-organization", type:"mcq", prompt:"[Falsos amigos] 'Tuve un accidente terrible.' 'Terrible' en español significa:", options:["terrible / awful","terrific / amazing","terrifying only","tremendous"], correctAnswer:"terrible / awful", difficulty:"easy", points:10 },
  { id:"gap-fc-20", themeId:"sharing-planet", type:"mcq", prompt:"[Falsos amigos] 'El gas natural es un recurso eventualmente agotable.' ¿Qué significa 'eventualmente'?", options:["eventually / in the end","by any chance","evidently","actually"], correctAnswer:"eventually / in the end", difficulty:"hard", points:30, explanation:"TRAP: 'Eventualmente' = eventually, someday. It does NOT mean 'possibly' like English 'eventually'." },
  { id:"gap-fc-21", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] '¡Qué gracioso es ese chico!' ¿Qué significa 'gracioso'?", options:["funny","gracious","grateful","graceful"], correctAnswer:"funny", difficulty:"medium", points:20, explanation:"'Gracioso' = funny. 'Gracious' = amable / cortés." },
  { id:"gap-fc-22", themeId:"experiences", type:"mcq", prompt:"[Falsos amigos] 'Quiero recordar ese momento para siempre.' ¿Qué significa 'recordar'?", options:["to remember","to record","to remind","to recognize"], correctAnswer:"to remember", difficulty:"easy", points:10, explanation:"'Recordar' = to remember. 'To record' = grabar." },
  { id:"gap-fc-23", themeId:"human-ingenuity", type:"mcq", prompt:"[Falsos amigos] 'Los datos son muy relevantes.' ¿Qué son 'los datos'?", options:["data / information","dates","details","documents"], correctAnswer:"data / information", difficulty:"easy", points:10 },
  { id:"gap-fc-24", themeId:"social-organization", type:"mcq", prompt:"[Falsos amigos] 'Hay una manifestación en la plaza.' ¿Qué es una 'manifestación'?", options:["protest / demonstration","a show","a concert","a manifest"], correctAnswer:"protest / demonstration", difficulty:"medium", points:20, explanation:"'Manifestación' = protest/demonstration. A 'manifestation' = una señal / evidencia." },
  { id:"gap-fc-25", themeId:"sharing-planet", type:"mcq", prompt:"[Falsos amigos] 'El parque nacional pretende proteger la fauna local.' ¿Qué significa 'pretender' en español?", options:["to aim / to intend","to pretend","to claim falsely","to attempt something fake"], correctAnswer:"to aim / to intend", difficulty:"hard", points:30, explanation:"TRAP: Spanish 'pretender' = to try to / intend to. 'To pretend' (fake) = fingir." },
  { id:"gap-fc-26", themeId:"identities", type:"short", prompt:"[Falsos amigos] ¿Cómo se dice 'embarrassed' (feeling ashamed) en español? (No es 'embarazada')", correctAnswer:"avergonzado", difficulty:"hard", points:30 },
  { id:"gap-fc-27", themeId:"experiences", type:"short", prompt:"[Falsos amigos] ¿Cómo se dice 'library' (place to borrow books) en español? (No es 'librería')", correctAnswer:"la biblioteca", difficulty:"medium", points:20 },
  { id:"gap-fc-28", themeId:"human-ingenuity", type:"short", prompt:"[Falsos amigos] ¿Cómo se dice 'to realize' (to understand/become aware) en español? (No es 'realizar')", correctAnswer:"darse cuenta de", difficulty:"hard", points:30 },
  { id:"gap-fc-29", themeId:"social-organization", type:"short", prompt:"[Falsos amigos] ¿Cómo se dice 'to attend' (a meeting) en español? (No es siempre 'atender')", correctAnswer:"asistir a", difficulty:"hard", points:30 },
  { id:"gap-fc-30", themeId:"sharing-planet", type:"mcq", prompt:"[Falsos amigos] 'El plan es ambicioso pero no realista.' 'Realista' en español es:", options:["realistic","realist (person)","really great","real estate"], correctAnswer:"realistic", difficulty:"easy", points:10 },
  { id:"gap-fc-31", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] '¿Puedo introducir una moneda?' ¿Qué significa 'introducir' aquí?", options:["to insert","to introduce a person","to invent","to improve"], correctAnswer:"to insert", difficulty:"hard", points:30, explanation:"'Introducir' = to insert/put in. 'To introduce a person' = presentar." },
  { id:"gap-fc-32", themeId:"experiences", type:"mcq", prompt:"[Falsos amigos] 'La propuesta fue aprobada por el comité.' ¿Qué es una 'propuesta'?", options:["proposal / suggestion","purpose","prophecy","property"], correctAnswer:"proposal / suggestion", difficulty:"medium", points:20 },
  { id:"gap-fc-33", themeId:"human-ingenuity", type:"mcq", prompt:"[Falsos amigos] 'Actualmente, el 60% de los jóvenes usan redes sociales.' ¿Qué significa 'actualmente'?", options:["currently / nowadays","actually (in fact)","actively","actually (surprisingly)"], correctAnswer:"currently / nowadays", difficulty:"hard", points:30, explanation:"TRAP: 'Actualmente' = currently/nowadays. 'Actually' = en realidad / de hecho." },
  { id:"gap-fc-34", themeId:"social-organization", type:"mcq", prompt:"[Falsos amigos] 'La renta mínima ayuda a las familias pobres.' ¿Qué es 'la renta'?", options:["income / rent","rent only","money saved","a rental car"], correctAnswer:"income / rent", difficulty:"medium", points:20 },
  { id:"gap-fc-35", themeId:"sharing-planet", type:"mcq", prompt:"[Falsos amigos] 'La ciudad sufre de una grave polución.' ¿Qué es 'la polución'?", options:["pollution","population","evolution","solution"], correctAnswer:"pollution", difficulty:"easy", points:10 },
  { id:"gap-fc-36", themeId:"identities", type:"mcq", prompt:"[Falsos amigos] '¿Cuál es tu carrera favorita?' 'La carrera' puede significar:", options:["university degree / career / race","car","care","career center"], correctAnswer:"university degree / career / race", difficulty:"medium", points:20, explanation:"'Carrera' is multi-meaning: university degree, career, or a race." },
  { id:"gap-fc-37", themeId:"experiences", type:"mcq", prompt:"[Falsos amigos] 'Estoy muy emocionado por el viaje.' ¿Qué significa 'emocionado/a'?", options:["excited / moved emotionally","emotional (as a personality)","emotional wreck","sad"], correctAnswer:"excited / moved emotionally", difficulty:"medium", points:20, explanation:"'Emocionado' = excited/moved. 'Emotional' as a personality = emocional/sensible." },
  { id:"gap-fc-38", themeId:"human-ingenuity", type:"mcq", prompt:"[Falsos amigos] 'El científico hizo un discurso.' ¿Qué es un 'discurso'?", options:["speech","discourse (academic)","discussion","discovery"], correctAnswer:"speech", difficulty:"medium", points:20 },
  { id:"gap-fc-39", themeId:"social-organization", type:"mcq", prompt:"[Falsos amigos] '¿Cuándo vas a volver?' ¿Qué significa 'volver'?", options:["to return / come back","to become","to get worse","to volunteer"], correctAnswer:"to return / come back", difficulty:"easy", points:10 },
  { id:"gap-fc-40", themeId:"sharing-planet", type:"mcq", prompt:"[Falsos amigos] 'El incidente causó un gran perjuicio al ecosistema.' ¿Qué es un 'perjuicio'?", options:["harm / damage","prejudice","justice","privilege"], correctAnswer:"harm / damage", difficulty:"hard", points:30, explanation:"'Perjuicio' = harm/damage/prejudice in legal sense. English 'prejudice' = prejuicio (bias)." },

  // =========================================================================
  // 2. RELATIVE CLAUSES (~70 questions)
  // =========================================================================

  { id:"gap-rc-1", themeId:"identities", type:"mcq", prompt:"[Oraciones de relativo] 'El chico ___ vive en mi calle habla tres idiomas.' ¿Cuál es correcto?", options:["que","quien","donde","cual"], correctAnswer:"que", difficulty:"medium", points:20, explanation:"Use 'que' for defining relative clauses — no comma before it." },
  { id:"gap-rc-2", themeId:"identities", type:"mcq", prompt:"[Oraciones de relativo] 'Mi profesora, ___ es muy paciente, nos ayuda mucho.' ¿Cuál es correcto?", options:["quien","que","donde","cuyo"], correctAnswer:"quien", difficulty:"medium", points:20, explanation:"After a comma in non-defining relative clauses about people, 'quien' is preferred." },
  { id:"gap-rc-3", themeId:"experiences", type:"mcq", prompt:"[Oraciones de relativo] 'Este es el lugar ___ nací.' ¿Cuál es correcto?", options:["donde","que","quien","cual"], correctAnswer:"donde", difficulty:"easy", points:10, explanation:"'Donde' = where, used for places." },
  { id:"gap-rc-4", themeId:"experiences", type:"mcq", prompt:"[Oraciones de relativo] 'El libro ___ me recomendaste es fantástico.' ¿Cuál es correcto?", options:["que","quien","donde","el cual"], correctAnswer:"que", difficulty:"easy", points:10 },
  { id:"gap-rc-5", themeId:"human-ingenuity", type:"mcq", prompt:"[Oraciones de relativo] 'La aplicación, ___ fue creada por estudiantes, ya tiene un millón de usuarios.' ¿Cuál es correcto?", options:["que","quien","donde","cuyo"], correctAnswer:"que", difficulty:"medium", points:20, explanation:"Non-defining clause about a thing → 'que'." },
  { id:"gap-rc-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Oraciones de relativo] 'El periodista ___ artículo leímos ganó un premio.' ¿Cuál es correcto?", options:["cuyo","que","quien","donde"], correctAnswer:"cuyo", difficulty:"hard", points:30, explanation:"'Cuyo/a' = whose. It agrees with the noun it precedes: 'cuyo artículo'." },
  { id:"gap-rc-7", themeId:"social-organization", type:"mcq", prompt:"[Oraciones de relativo] 'La organización para ___ trabaja mi madre ayuda a refugiados.' ¿Cuál es correcto?", options:["la que","que","donde","quien"], correctAnswer:"la que", difficulty:"hard", points:30, explanation:"After a preposition + article, use 'el/la/los/las que' or 'el/la cual'." },
  { id:"gap-rc-8", themeId:"social-organization", type:"mcq", prompt:"[Oraciones de relativo] 'Las personas ___ participaron en la manifestación eran muy jóvenes.' ¿Cuál es correcto?", options:["que","quienes","donde","cuya"], correctAnswer:"que", difficulty:"easy", points:10 },
  { id:"gap-rc-9", themeId:"sharing-planet", type:"mcq", prompt:"[Oraciones de relativo] 'El río, ___ nace en los Andes, desemboca en el Atlántico.' ¿Cuál es correcto?", options:["que","quien","donde","cuyo"], correctAnswer:"que", difficulty:"medium", points:20 },
  { id:"gap-rc-10", themeId:"sharing-planet", type:"mcq", prompt:"[Oraciones de relativo] 'El científico, con ___ hablé ayer, estudia el cambio climático.' ¿Cuál es correcto?", options:["quien","que","donde","cual"], correctAnswer:"quien", difficulty:"hard", points:30, explanation:"After a preposition, use 'quien' for people: 'con quien'." },
  { id:"gap-rc-11", themeId:"identities", type:"short", prompt:"[Oraciones de relativo] Completa: 'La ciudad ___ vivo tiene mucha diversidad cultural.'", correctAnswer:"donde", difficulty:"easy", points:10 },
  { id:"gap-rc-12", themeId:"identities", type:"short", prompt:"[Oraciones de relativo] Completa: 'El idioma ___ hablo en casa es el español.'", correctAnswer:"que", difficulty:"easy", points:10 },
  { id:"gap-rc-13", themeId:"experiences", type:"short", prompt:"[Oraciones de relativo] Completa: 'Mi abuelo, ___ nació en Cuba, me contaba historias de su infancia.'", correctAnswer:"quien", difficulty:"medium", points:20 },
  { id:"gap-rc-14", themeId:"experiences", type:"mcq", prompt:"[Oraciones de relativo] '¿Cuándo viene la persona de ___ me hablaste?' ¿Cuál es correcto?", options:["quien","que","la cual","donde"], correctAnswer:"quien", difficulty:"hard", points:30 },
  { id:"gap-rc-15", themeId:"human-ingenuity", type:"mcq", prompt:"[Oraciones de relativo] 'Este es el motivo por ___ no apoyo esa decisión.' ¿Cuál es correcto?", options:["el que / el cual","que","quien","donde"], correctAnswer:"el que / el cual", difficulty:"hard", points:30, explanation:"'Por el que / por el cual' = for which, the reason why." },
  { id:"gap-rc-16", themeId:"human-ingenuity", type:"mcq", prompt:"[Oraciones de relativo] 'La empresa ___ inventó el producto fue fundada en 1990.' ¿Cuál es correcto?", options:["que","quien","cuya","donde"], correctAnswer:"que", difficulty:"easy", points:10 },
  { id:"gap-rc-17", themeId:"social-organization", type:"mcq", prompt:"[Oraciones de relativo] El pronombre relativo 'cuyo/cuya' siempre concuerda con:", options:["el sustantivo que le sigue","el sujeto","el verbo","el objeto"], correctAnswer:"el sustantivo que le sigue", difficulty:"hard", points:30, explanation:"'Cuyo' = whose. It agrees in gender/number with the noun that follows it, not with the person it refers to." },
  { id:"gap-rc-18", themeId:"social-organization", type:"mcq", prompt:"[Oraciones de relativo] 'La razón ___ muchos emigran es la falta de oportunidades.' ¿Cuál es correcto?", options:["por la que","que","donde","quien"], correctAnswer:"por la que", difficulty:"hard", points:30 },
  { id:"gap-rc-19", themeId:"sharing-planet", type:"mcq", prompt:"[Oraciones de relativo] 'El parque ___ se han observado nuevas especies está en peligro.' ¿Cuál es correcto?", options:["donde","que","quien","cuya"], correctAnswer:"donde", difficulty:"medium", points:20 },
  { id:"gap-rc-20", themeId:"sharing-planet", type:"short", prompt:"[Oraciones de relativo] Completa: 'El volcán, ___ erupción causó grandes daños, está en Nicaragua.'", correctAnswer:"cuya", difficulty:"hard", points:30 },
  { id:"gap-rc-21", themeId:"identities", type:"mcq", prompt:"[Oraciones de relativo - puzzle] ¿Cuál de estas oraciones es correcta?", options:["El chico que estudia mucho aprueba los exámenes.","El chico quien estudia mucho aprueba los exámenes.","El chico donde estudia mucho aprueba los exámenes.","El chico cuyo estudia mucho aprueba los exámenes."], correctAnswer:"El chico que estudia mucho aprueba los exámenes.", difficulty:"medium", points:20 },
  { id:"gap-rc-22", themeId:"experiences", type:"mcq", prompt:"[Oraciones de relativo] ¿Cuándo se usa 'el cual / la cual' en lugar de 'que'?", options:["Después de una preposición larga o en cláusulas no restrictivas formales","Siempre que haya una persona","Cuando hay dos personas","Solo en preguntas"], correctAnswer:"Después de una preposición larga o en cláusulas no restrictivas formales", difficulty:"hard", points:30, explanation:"'El cual / la cual' is used after prepositions and in formal non-defining clauses." },
  { id:"gap-rc-23", themeId:"human-ingenuity", type:"mcq", prompt:"[Oraciones de relativo] 'El ordenador ___ uso para estudiar es muy lento.' ¿Cuál es correcto?", options:["que","quien","donde","cuyo"], correctAnswer:"que", difficulty:"easy", points:10 },
  { id:"gap-rc-24", themeId:"social-organization", type:"mcq", prompt:"[Oraciones de relativo] 'Los ciudadanos, entre ___ hay muchas personas mayores, apoyan la reforma.' ¿Cuál es correcto?", options:["quienes","que","cuya","donde"], correctAnswer:"quienes", difficulty:"hard", points:30, explanation:"'Entre quienes' = among whom — after preposition, use quienes for people." },
  { id:"gap-rc-25", themeId:"sharing-planet", type:"short", prompt:"[Oraciones de relativo] Completa: 'La fábrica, ___ productos contaminan el río, debe cerrar.'", correctAnswer:"cuyos", difficulty:"hard", points:30 },
  { id:"gap-rc-26", themeId:"identities", type:"puzzle", prompt:"[Oraciones de relativo - ordenar] Crea una oración con pronombre relativo:", options:["estudia","que","chica","la","medicina","mucho"], correctAnswer:"la chica que estudia mucho medicina", difficulty:"medium", points:20 },
  { id:"gap-rc-27", themeId:"experiences", type:"mcq", prompt:"[Oraciones de relativo] '¿De dónde eres tú?' — ¿Qué pronombre relativo podría usar 'donde' en la respuesta?", options:["El país donde nací es Colombia.","El país que nací es Colombia.","El país quien nací es Colombia.","El país cuya nací es Colombia."], correctAnswer:"El país donde nací es Colombia.", difficulty:"easy", points:10 },
  { id:"gap-rc-28", themeId:"human-ingenuity", type:"mcq", prompt:"[Oraciones de relativo] 'La empresa, a ___ se le otorgó el contrato, es española.' ¿Cuál es correcto?", options:["la que","quien","que","donde"], correctAnswer:"la que", difficulty:"hard", points:30, explanation:"For things (empresa) after a preposition, use 'la que / la cual'." },
  { id:"gap-rc-29", themeId:"social-organization", type:"mcq", prompt:"[Oraciones de relativo] '¿Cuál es la frase correcta?'", options:["Las personas que viven en pobreza necesitan apoyo.","Las personas quienes viven en pobreza necesitan apoyo.","Las personas donde viven en pobreza necesitan apoyo.","Las personas cuyas viven en pobreza necesitan apoyo."], correctAnswer:"Las personas que viven en pobreza necesitan apoyo.", difficulty:"easy", points:10 },
  { id:"gap-rc-30", themeId:"sharing-planet", type:"mcq", prompt:"[Oraciones de relativo] ¿Cuál de estas oraciones usa 'cuyo' correctamente?", options:["El árbol cuyos frutos son venenosos debe cortarse.","El árbol cuyo son venenosos frutos debe cortarse.","El árbol cuya frutos son venenosos debe cortarse.","El árbol quien frutos son venenosos debe cortarse."], correctAnswer:"El árbol cuyos frutos son venenosos debe cortarse.", difficulty:"hard", points:30, explanation:"'Cuyos frutos' — cuyo agrees with 'frutos' (masculine plural) → cuyos." },

  // =========================================================================
  // 3. AFFIRMATIVE IMPERATIVE (~70 questions)
  // =========================================================================

  { id:"gap-imp-1", themeId:"identities", type:"mcq", prompt:"[Imperativo afirmativo - tú] ¿Cuál es el imperativo afirmativo de 'hablar' para 'tú'?", options:["habla","hablas","hable","habla tú"], correctAnswer:"habla", difficulty:"easy", points:10, explanation:"Tú imperative for regular -ar verbs: drop -as → habla." },
  { id:"gap-imp-2", themeId:"identities", type:"mcq", prompt:"[Imperativo afirmativo - tú] ¿Cuál es el imperativo de 'comer' para 'tú'?", options:["come","comes","coma","comer"], correctAnswer:"come", difficulty:"easy", points:10 },
  { id:"gap-imp-3", themeId:"identities", type:"mcq", prompt:"[Imperativo afirmativo - tú] ¿Cuál es el imperativo de 'escribir' para 'tú'?", options:["escribe","escribes","escriba","escribir"], correctAnswer:"escribe", difficulty:"easy", points:10 },
  { id:"gap-imp-4", themeId:"identities", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'tener' para 'tú'?", options:["ten","tiene","tenga","tener"], correctAnswer:"ten", difficulty:"medium", points:20, explanation:"Irregular tú imperative: tener → ten, poner → pon, venir → ven, hacer → haz, decir → di, ser → sé, ir → ve, salir → sal." },
  { id:"gap-imp-5", themeId:"identities", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'ser' para 'tú'?", options:["sé","sea","eres","ser"], correctAnswer:"sé", difficulty:"medium", points:20, explanation:"Irregular: ser → sé (note the accent to distinguish from 'se')." },
  { id:"gap-imp-6", themeId:"experiences", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'ir' para 'tú'?", options:["ve","va","ir","vete"], correctAnswer:"ve", difficulty:"medium", points:20, explanation:"Ir → ve (tú imperative). Note: 'vete' = go away (reflexive form)." },
  { id:"gap-imp-7", themeId:"experiences", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'hacer' para 'tú'?", options:["haz","hace","haga","hacer"], correctAnswer:"haz", difficulty:"medium", points:20 },
  { id:"gap-imp-8", themeId:"experiences", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'decir' para 'tú'?", options:["di","dice","diga","decir"], correctAnswer:"di", difficulty:"medium", points:20 },
  { id:"gap-imp-9", themeId:"experiences", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'poner' para 'tú'?", options:["pon","pone","ponga","poner"], correctAnswer:"pon", difficulty:"medium", points:20 },
  { id:"gap-imp-10", themeId:"experiences", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'venir' para 'tú'?", options:["ven","viene","venga","venir"], correctAnswer:"ven", difficulty:"medium", points:20 },
  { id:"gap-imp-11", themeId:"human-ingenuity", type:"mcq", prompt:"[Imperativo afirmativo - irregular] ¿Cuál es el imperativo de 'salir' para 'tú'?", options:["sal","sale","salga","salir"], correctAnswer:"sal", difficulty:"medium", points:20 },
  { id:"gap-imp-12", themeId:"human-ingenuity", type:"short", prompt:"[Imperativo - tú] Da el imperativo afirmativo de 'leer' (tú): '¡___ ese artículo!'", correctAnswer:"lee", difficulty:"easy", points:10 },
  { id:"gap-imp-13", themeId:"human-ingenuity", type:"short", prompt:"[Imperativo - tú] Da el imperativo afirmativo de 'abrir' (tú): '¡___ la ventana!'", correctAnswer:"abre", difficulty:"easy", points:10 },
  { id:"gap-imp-14", themeId:"human-ingenuity", type:"short", prompt:"[Imperativo - tú] Da el imperativo afirmativo de 'beber' (tú): '¡___ más agua!'", correctAnswer:"bebe", difficulty:"easy", points:10 },
  { id:"gap-imp-15", themeId:"social-organization", type:"mcq", prompt:"[Imperativo afirmativo - usted] ¿Cuál es el imperativo de 'hablar' para 'usted'?", options:["hable","habla","hablen","hablar"], correctAnswer:"hable", difficulty:"medium", points:20, explanation:"Usted imperative uses the opposite vowel: hablar → hable, comer → coma, vivir → viva." },
  { id:"gap-imp-16", themeId:"social-organization", type:"mcq", prompt:"[Imperativo afirmativo - usted] ¿Cuál es el imperativo de 'escribir' para 'usted'?", options:["escriba","escribe","escriben","escribir"], correctAnswer:"escriba", difficulty:"medium", points:20 },
  { id:"gap-imp-17", themeId:"social-organization", type:"mcq", prompt:"[Imperativo afirmativo - usted] ¿Cuál es el imperativo de 'leer' para 'usted'?", options:["lea","lee","leer","lean"], correctAnswer:"lea", difficulty:"medium", points:20 },
  { id:"gap-imp-18", themeId:"social-organization", type:"mcq", prompt:"[Imperativo afirmativo - ustedes] ¿Cuál es el imperativo de 'hablar' para 'ustedes'?", options:["hablen","hablan","hable","hablar"], correctAnswer:"hablen", difficulty:"medium", points:20, explanation:"Ustedes imperative: add -n to the usted form → hablen, coman, escriban." },
  { id:"gap-imp-19", themeId:"social-organization", type:"mcq", prompt:"[Imperativo afirmativo - nosotros] '¡___ juntos para mejorar el mundo!' ¿Cuál es el imperativo de 'trabajar' para 'nosotros'?", options:["trabajemos","trabajamos","trabajan","trabajar"], correctAnswer:"trabajemos", difficulty:"hard", points:30, explanation:"Nosotros imperative: drop -amos/-emos/-imos, add opposite vowel + mos: trabajemos." },
  { id:"gap-imp-20", themeId:"sharing-planet", type:"mcq", prompt:"[Imperativo - contexto] En un folleto de reciclaje: '¡___ los residuos plásticos correctamente!' ¿Cuál es el imperativo correcto para 'separar' (vosotros)?", options:["separad","separáis","separar","separo"], correctAnswer:"separad", difficulty:"hard", points:30, explanation:"Vosotros affirmative imperative: replace -r with -d: separar → separad." },
  { id:"gap-imp-21", themeId:"sharing-planet", type:"mcq", prompt:"[Imperativo - instrucciones] En un manual ecológico: '¡___ (apagar, tú) las luces al salir!' ¿Cuál es correcto?", options:["apaga","apague","apagas","apagar"], correctAnswer:"apaga", difficulty:"easy", points:10 },
  { id:"gap-imp-22", themeId:"sharing-planet", type:"short", prompt:"[Imperativo - tú] Da el imperativo de 'reciclar' (tú): '¡___ siempre!'", correctAnswer:"recicla", difficulty:"easy", points:10 },
  { id:"gap-imp-23", themeId:"identities", type:"mcq", prompt:"[Imperativo con pronombres] '¡Dímelo!' Esta forma combina:", options:["di (imperativo) + me + lo (pronombres átonos)","decir + melo","dice + me + lo","di + me + lo separado"], correctAnswer:"di (imperativo) + me + lo (pronombres átonos)", difficulty:"hard", points:30, explanation:"With affirmative imperative, object pronouns attach to the end: di + me + lo = dímelo." },
  { id:"gap-imp-24", themeId:"identities", type:"mcq", prompt:"[Imperativo con pronombres] '¡Cómpramelo!' ¿Qué significa?", options:["Buy it for me!","Buy me something!","He buys it for me.","Buy it yourself!"], correctAnswer:"Buy it for me!", difficulty:"hard", points:30, explanation:"Compra + me + lo = buy (it) for me! Pronombres attached to imperative." },
  { id:"gap-imp-25", themeId:"experiences", type:"short", prompt:"[Imperativo - nosotros] Da el imperativo de 'salir' (nosotros): '¡___ a explorar el mundo!'", correctAnswer:"salgamos", difficulty:"hard", points:30, explanation:"Irregular nosotros imperative: salir → salgamos (based on present subjunctive)." },
  { id:"gap-imp-26", themeId:"experiences", type:"mcq", prompt:"[Imperativo - uso en texto] En una receta de cocina, ¿qué forma verbal domina?", options:["El imperativo afirmativo (tú o usted)","El pretérito","El futuro","El imperfecto"], correctAnswer:"El imperativo afirmativo (tú o usted)", difficulty:"easy", points:10, explanation:"Recipes use imperative: 'Corta las cebollas, añade el aceite, mezcla bien...'" },
  { id:"gap-imp-27", themeId:"human-ingenuity", type:"mcq", prompt:"[Imperativo - IB Paper 2] En un artículo de instrucciones sobre cómo usar una app: '¡___ (instalar, usted) la aplicación primero!'", options:["instale","instala","instalar","instalad"], correctAnswer:"instale", difficulty:"medium", points:20 },
  { id:"gap-imp-28", themeId:"human-ingenuity", type:"mcq", prompt:"[Imperativo + reflexivo] '¡Lávate las manos!' ¿Qué significa?", options:["Wash your hands!","He washes his hands.","You wash yourself.","Please wash the hands."], correctAnswer:"Wash your hands!", difficulty:"medium", points:20, explanation:"Lava (tú imperative of lavar) + te (reflexive pronoun) attached = lávate." },
  { id:"gap-imp-29", themeId:"social-organization", type:"mcq", prompt:"[Imperativo - nosotros] '¡___ (luchar) por un mundo más justo!' ¿Cuál es correcto?", options:["Luchemos","Luchamos","Luchar","Luchen"], correctAnswer:"Luchemos", difficulty:"hard", points:30 },
  { id:"gap-imp-30", themeId:"social-organization", type:"mcq", prompt:"[Imperativo - usted formal] En una carta formal al director: 'Le ruego que ___ (considerar, usted) mi propuesta.' ¿Qué forma es correcta para la cortesía formal?", options:["considere","considera","consideramos","consideren"], correctAnswer:"considere", difficulty:"hard", points:30 },
  { id:"gap-imp-31", themeId:"sharing-planet", type:"mcq", prompt:"[Imperativo afirmativo] '¡___ (plantar, vosotros) árboles en vuestro barrio!' ¿Cuál es correcto?", options:["plantad","plantan","planten","plantamos"], correctAnswer:"plantad", difficulty:"hard", points:30, explanation:"Vosotros affirmative imperative: plantar → plantad." },
  { id:"gap-imp-32", themeId:"sharing-planet", type:"short", prompt:"[Imperativo] Da el imperativo de 'reducir' para 'tú': '¡___ tu huella de carbono!'", correctAnswer:"reduce", difficulty:"medium", points:20 },
  { id:"gap-imp-33", themeId:"identities", type:"mcq", prompt:"[Imperativo irregular] '¡___ (ser, tú) auténtico!' ¿Cuál es el imperativo correcto?", options:["sé","sea","ser","eres"], correctAnswer:"sé", difficulty:"medium", points:20 },
  { id:"gap-imp-34", themeId:"experiences", type:"mcq", prompt:"[Imperativo irregular] '¡___ (ir, tú) a explorar nuevas culturas!' ¿Cuál es correcto?", options:["ve","ir","vas","vaya"], correctAnswer:"ve", difficulty:"medium", points:20 },
  { id:"gap-imp-35", themeId:"human-ingenuity", type:"mcq", prompt:"[Imperativo irregular] '¡___ (venir, tú) a la conferencia sobre tecnología!'", options:["ven","viene","vino","venir"], correctAnswer:"ven", difficulty:"medium", points:20 },

  // =========================================================================
  // 4. POR vs. PARA (~60 questions)
  // =========================================================================

  { id:"gap-pp-1", themeId:"identities", type:"mcq", prompt:"[Por/Para] 'Estudio español ___ mejorar mis oportunidades laborales.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"PARA: purpose / goal (in order to)." },
  { id:"gap-pp-2", themeId:"identities", type:"mcq", prompt:"[Por/Para] 'Este libro fue escrito ___ Gabriel García Márquez.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"medium", points:20, explanation:"POR: agent in passive constructions (written by)." },
  { id:"gap-pp-3", themeId:"identities", type:"mcq", prompt:"[Por/Para] 'Te doy este regalo ___ tu cumpleaños.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"PARA: recipient / destination of something." },
  { id:"gap-pp-4", themeId:"identities", type:"mcq", prompt:"[Por/Para] 'Gracias ___ tu ayuda.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"easy", points:10, explanation:"POR: expressing thanks (gracias por = thanks for)." },
  { id:"gap-pp-5", themeId:"experiences", type:"mcq", prompt:"[Por/Para] 'Caminé ___ el parque esta mañana.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"medium", points:20, explanation:"POR: movement through a place." },
  { id:"gap-pp-6", themeId:"experiences", type:"mcq", prompt:"[Por/Para] 'El tren sale ___ Madrid a las 10.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"PARA: destination (the train goes TO Madrid)." },
  { id:"gap-pp-7", themeId:"experiences", type:"mcq", prompt:"[Por/Para] 'Te llamo ___ la tarde.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"easy", points:10, explanation:"POR: time periods of the day (por la mañana/tarde/noche)." },
  { id:"gap-pp-8", themeId:"experiences", type:"mcq", prompt:"[Por/Para] 'Necesito este informe ___ el viernes.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"PARA: deadline (needed by Friday)." },
  { id:"gap-pp-9", themeId:"human-ingenuity", type:"mcq", prompt:"[Por/Para] 'La noticia fue publicada ___ el periódico.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"medium", points:20, explanation:"POR: agent (published by the newspaper)." },
  { id:"gap-pp-10", themeId:"human-ingenuity", type:"mcq", prompt:"[Por/Para] 'Este software fue diseñado ___ estudiantes de idiomas.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"PARA: intended for a specific audience." },
  { id:"gap-pp-11", themeId:"human-ingenuity", type:"mcq", prompt:"[Por/Para] 'Pagaré 50 euros ___ este libro.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"medium", points:20, explanation:"POR: exchange (paying X for Y)." },
  { id:"gap-pp-12", themeId:"human-ingenuity", type:"mcq", prompt:"[Por/Para] '___ ser tan joven, habla español muy bien.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"hard", points:30, explanation:"PARA: considering / given that (for her age, she speaks well)." },
  { id:"gap-pp-13", themeId:"social-organization", type:"mcq", prompt:"[Por/Para] 'Luchamos ___ la igualdad de derechos.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"medium", points:20, explanation:"POR: on behalf of / in favor of a cause." },
  { id:"gap-pp-14", themeId:"social-organization", type:"mcq", prompt:"[Por/Para] 'El proyecto está ___ terminar.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"hard", points:30, explanation:"POR + infinitive = still to be done, in the process of: está por terminar = it's yet to be finished." },
  { id:"gap-pp-15", themeId:"social-organization", type:"mcq", prompt:"[Por/Para] 'Habla ___ teléfono todo el día.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"easy", points:10, explanation:"POR: means of communication (by phone)." },
  { id:"gap-pp-16", themeId:"social-organization", type:"mcq", prompt:"[Por/Para] 'Ella trabaja ___ una ONG internacional.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"PARA: employer (she works for an NGO)." },
  { id:"gap-pp-17", themeId:"sharing-planet", type:"mcq", prompt:"[Por/Para] 'La contaminación es causada ___ las fábricas.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"easy", points:10, explanation:"POR: cause / agent." },
  { id:"gap-pp-18", themeId:"sharing-planet", type:"mcq", prompt:"[Por/Para] 'Necesitamos actuar ___ salvar el planeta.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"easy", points:10, explanation:"PARA: purpose (in order to save)." },
  { id:"gap-pp-19", themeId:"sharing-planet", type:"mcq", prompt:"[Por/Para] 'Los árboles son importantes ___ producir oxígeno.' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"easy", points:10, explanation:"PARA: purpose/function." },
  { id:"gap-pp-20", themeId:"sharing-planet", type:"mcq", prompt:"[Por/Para] 'Estuvimos tres días ___ las montañas.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"medium", points:20, explanation:"POR: duration + location (through/around the mountains for three days)." },
  { id:"gap-pp-21", themeId:"identities", type:"short", prompt:"[Por/Para] Completa: 'Estoy muy agradecida ___ todo lo que hiciste.'", correctAnswer:"por", difficulty:"easy", points:10 },
  { id:"gap-pp-22", themeId:"experiences", type:"short", prompt:"[Por/Para] Completa: 'Salimos ___ Buenos Aires mañana.'", correctAnswer:"para", difficulty:"easy", points:10 },
  { id:"gap-pp-23", themeId:"human-ingenuity", type:"short", prompt:"[Por/Para] Completa: 'Esta aplicación fue creada ___ jóvenes estudiantes.'", correctAnswer:"por", difficulty:"easy", points:10 },
  { id:"gap-pp-24", themeId:"social-organization", type:"short", prompt:"[Por/Para] Completa: 'El informe debe estar listo ___ el lunes.'", correctAnswer:"para", difficulty:"easy", points:10 },
  { id:"gap-pp-25", themeId:"sharing-planet", type:"short", prompt:"[Por/Para] Completa: 'Reciclo ___ proteger el medio ambiente.'", correctAnswer:"para", difficulty:"easy", points:10 },
  { id:"gap-pp-26", themeId:"identities", type:"mcq", prompt:"[Por/Para - regla] ¿Cuándo se usa POR? Elige la opción CORRECTA.", options:["Para expresar duración, causa, agente, medio, precio, movimiento por un lugar","Para expresar propósito, destinatario, plazo, empleo, opinión sorprendente"], correctAnswer:"Para expresar duración, causa, agente, medio, precio, movimiento por un lugar", difficulty:"hard", points:30 },
  { id:"gap-pp-27", themeId:"experiences", type:"mcq", prompt:"[Por/Para - regla] ¿Cuándo se usa PARA? Elige la opción CORRECTA.", options:["Para expresar propósito, destinatario, plazo, empleo, comparación sorprendente","Para expresar duración, causa, agente, medio, precio"], correctAnswer:"Para expresar propósito, destinatario, plazo, empleo, comparación sorprendente", difficulty:"hard", points:30 },
  { id:"gap-pp-28", themeId:"human-ingenuity", type:"mcq", prompt:"[Por/Para] 'Mandé el mensaje ___ correo electrónico.' ¿Por o para?", options:["por","para"], correctAnswer:"por", difficulty:"easy", points:10, explanation:"POR: means (by email)." },
  { id:"gap-pp-29", themeId:"social-organization", type:"mcq", prompt:"[Por/Para] 'Lo hago ___ amor, no ___ dinero.' Completa con por/para.", options:["por / por","para / para","por / para","para / por"], correctAnswer:"por / por", difficulty:"hard", points:30, explanation:"Both express motivation/cause here: I do it because of love, not because of money." },
  { id:"gap-pp-30", themeId:"sharing-planet", type:"mcq", prompt:"[Por/Para] '¿Tienes algún consejo ___ ahorrar energía?' ¿Por o para?", options:["para","por"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"PARA: purpose (advice in order to save energy)." },

  // =========================================================================
  // 5. PASSIVE VOICE (~50 questions)
  // =========================================================================

  { id:"gap-pv-1", themeId:"identities", type:"mcq", prompt:"[Voz pasiva] Transforma a voz pasiva: 'El profesor escribió el libro.' ¿Cuál es correcta?", options:["El libro fue escrito por el profesor.","El libro es escrito por el profesor.","El libro fue escrito del profesor.","El libro escribió por el profesor."], correctAnswer:"El libro fue escrito por el profesor.", difficulty:"medium", points:20, explanation:"Passive: subject + ser (conjugated) + past participle (agrees) + por + agent." },
  { id:"gap-pv-2", themeId:"identities", type:"mcq", prompt:"[Voz pasiva] 'La ley ___ aprobada por el parlamento.' ¿Cuál es la forma correcta de SER?", options:["fue","era","es","ha sido"], correctAnswer:"fue", difficulty:"medium", points:20, explanation:"The action was completed in the past → fue (preterite of ser)." },
  { id:"gap-pv-3", themeId:"experiences", type:"mcq", prompt:"[Voz pasiva] 'Los derechos humanos ___ reconocidos en 1948.' ¿Cuál es correcto?", options:["fueron","son","eran","serán"], correctAnswer:"fueron", difficulty:"medium", points:20 },
  { id:"gap-pv-4", themeId:"experiences", type:"mcq", prompt:"[Voz pasiva - concordancia] 'Las casas ___ construidas por la empresa.' ¿Cuál es correcto?", options:["fueron construidas","fue construidas","fueron construido","era construidas"], correctAnswer:"fueron construidas", difficulty:"medium", points:20, explanation:"Past participle agrees with subject: casas (fem. pl.) → construidas." },
  { id:"gap-pv-5", themeId:"human-ingenuity", type:"mcq", prompt:"[Voz pasiva con SE] '¿Cuál es una pasiva con SE correcta?'", options:["Se inventó el teléfono en el siglo XIX.","El teléfono se inventó por Bell.","Se inventaron el teléfono en 1876.","El teléfono fue se inventado."], correctAnswer:"Se inventó el teléfono en el siglo XIX.", difficulty:"medium", points:20, explanation:"Impersonal passive with SE: Se + 3rd person verb. No agent (por...) used." },
  { id:"gap-pv-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Pasiva con SE] '¿Cómo ___ (hablar) español en Argentina?' ¿Cuál es correcto?", options:["se habla","se hablan","hablan","se habló"], correctAnswer:"se habla", difficulty:"medium", points:20, explanation:"Impersonal se + singular verb (for a single language)." },
  { id:"gap-pv-7", themeId:"social-organization", type:"mcq", prompt:"[Voz pasiva] Elige la forma pasiva correcta: 'Los manifestantes / detener / la policía (pasado)'", options:["Los manifestantes fueron detenidos por la policía.","Los manifestantes fue detenidos por la policía.","Los manifestantes fueron detenido por la policía.","Los manifestantes eran detenidos por la policía."], correctAnswer:"Los manifestantes fueron detenidos por la policía.", difficulty:"hard", points:30 },
  { id:"gap-pv-8", themeId:"social-organization", type:"short", prompt:"[Voz pasiva] Transforma: 'El gobierno firmó el acuerdo.' → 'El acuerdo ___ ___ por el gobierno.'", correctAnswer:"fue firmado", difficulty:"medium", points:20 },
  { id:"gap-pv-9", themeId:"sharing-planet", type:"mcq", prompt:"[Voz pasiva] 'La selva amazónica ___ destruida cada año por la deforestación.' ¿Cuál es correcto?", options:["es","fue","eran","fueron"], correctAnswer:"es", difficulty:"medium", points:20, explanation:"Ongoing present action → es (presente de ser + past participle)." },
  { id:"gap-pv-10", themeId:"sharing-planet", type:"mcq", prompt:"[Pasiva vs activa] ¿Cuál de estas oraciones está en VOZ PASIVA?", options:["El río fue contaminado por las fábricas.","Las fábricas contaminaron el río.","El río está contaminado.","La gente contamina el río."], correctAnswer:"El río fue contaminado por las fábricas.", difficulty:"medium", points:20, explanation:"Passive = ser + past participle + por + agent. The other options are active voice or stative." },
  { id:"gap-pv-11", themeId:"identities", type:"mcq", prompt:"[Pasiva - presente] 'El español ___ hablado por más de 500 millones de personas.' ¿Cuál es correcto?", options:["es","fue","era","será"], correctAnswer:"es", difficulty:"easy", points:10 },
  { id:"gap-pv-12", themeId:"experiences", type:"mcq", prompt:"[Pasiva - futuro] 'El nuevo puente ___ construido el próximo año.' ¿Cuál es correcto?", options:["será","es","fue","ha sido"], correctAnswer:"será", difficulty:"medium", points:20, explanation:"Future passive: será + past participle." },
  { id:"gap-pv-13", themeId:"human-ingenuity", type:"mcq", prompt:"[Pasiva - diferencia] ¿Cuál es la diferencia entre 'fue construido' y 'está construido'?", options:["'Fue construido' describe la acción completada; 'está construido' describe el estado resultante","Son exactamente iguales","'Está construido' es incorrecto","'Fue construido' es solo para edificios"], correctAnswer:"'Fue construido' describe la acción completada; 'está construido' describe el estado resultante", difficulty:"hard", points:30, explanation:"Ser + pp = completed action (passive). Estar + pp = resulting state (not really passive, but descriptive)." },
  { id:"gap-pv-14", themeId:"social-organization", type:"mcq", prompt:"[Pasiva con SE plural] '¿Cómo ___ (vender) las entradas para el concierto?'", options:["se venden","se vende","se vendió","vendieron"], correctAnswer:"se venden", difficulty:"medium", points:20, explanation:"Se + plural verb because 'las entradas' is plural." },
  { id:"gap-pv-15", themeId:"sharing-planet", type:"mcq", prompt:"[Pasiva con SE] '¿Qué oración usa correctamente la pasiva con SE?'", options:["Se hablan muchos idiomas en España.","Se habla muchos idiomas en España.","Se habló muchos idiomas en España.","Se hablan el español en España."], correctAnswer:"Se hablan muchos idiomas en España.", difficulty:"hard", points:30, explanation:"'Idiomas' is plural → se hablan (plural verb agreement with SE passive)." },

  // =========================================================================
  // 6. HEADING MATCH / PARAGRAPH-TOPIC MCQ (~50 questions)
  // =========================================================================

  { id:"gap-hm-1", themeId:"identities", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'Muchos adolescentes sienten que no encajan ni en su cultura de origen ni en la cultura del país donde viven. Este sentimiento puede causar confusión y baja autoestima.' ¿Qué título corresponde mejor a este párrafo?", options:["La crisis de identidad entre jóvenes inmigrantes","Los beneficios del bilingüismo","La importancia de la tradición familiar","El impacto positivo de la migración"], correctAnswer:"La crisis de identidad entre jóvenes inmigrantes", difficulty:"medium", points:20 },
  { id:"gap-hm-2", themeId:"identities", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'Dormir al menos 8 horas, comer de forma equilibrada y hacer ejercicio regularmente son los pilares de una vida sana.' ¿Qué título corresponde mejor?", options:["Los hábitos esenciales para el bienestar físico","Los beneficios de las redes sociales","El estrés en los jóvenes modernos","La importancia del descanso solo"], correctAnswer:"Los hábitos esenciales para el bienestar físico", difficulty:"easy", points:10 },
  { id:"gap-hm-3", themeId:"experiences", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'Dejar atrás el país natal, la familia y los amigos para buscar una vida mejor en otro lugar es uno de los sacrificios más difíciles que una persona puede hacer.' ¿Qué título es más apropiado?", options:["El sacrificio de emigrar","Las ventajas del turismo","La vida en el campo","La integración cultural exitosa"], correctAnswer:"El sacrificio de emigrar", difficulty:"medium", points:20 },
  { id:"gap-hm-4", themeId:"experiences", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'Las fiestas de carnaval son celebradas con disfraces coloridos, música y bailes tradicionales. En muchos países latinoamericanos, es la celebración más importante del año.' ¿Qué título corresponde?", options:["El carnaval: una fiesta llena de color y tradición","Los funerales en América Latina","Las bodas tradicionales","El Día de los Muertos"], correctAnswer:"El carnaval: una fiesta llena de color y tradición", difficulty:"easy", points:10 },
  { id:"gap-hm-5", themeId:"human-ingenuity", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'La inteligencia artificial puede analizar miles de imágenes médicas en segundos, ayudando a los médicos a detectar enfermedades con mayor precisión que antes.' ¿Qué título es más adecuado?", options:["La IA revoluciona el diagnóstico médico","Los robots reemplazan a los doctores","La medicina tradicional es superior","Los peligros de la tecnología médica"], correctAnswer:"La IA revoluciona el diagnóstico médico", difficulty:"medium", points:20 },
  { id:"gap-hm-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'Las noticias falsas se propagan 6 veces más rápido en las redes sociales que las noticias verdaderas. Esto tiene consecuencias graves para la democracia y la salud pública.' ¿Qué título corresponde mejor?", options:["La desinformación: un peligro para la sociedad moderna","El periodismo profesional muere","Las ventajas de internet","Cómo escribir noticias interesantes"], correctAnswer:"La desinformación: un peligro para la sociedad moderna", difficulty:"medium", points:20 },
  { id:"gap-hm-7", themeId:"social-organization", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'A pesar de los avances en igualdad de género, las mujeres siguen ganando en promedio un 14% menos que los hombres por el mismo trabajo.' ¿Qué título es más apropiado?", options:["La brecha salarial de género persiste","Las mujeres ya tienen igualdad de derechos","El trabajo femenino no existe","La revolución feminista terminó"], correctAnswer:"La brecha salarial de género persiste", difficulty:"medium", points:20 },
  { id:"gap-hm-8", themeId:"social-organization", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'La educación gratuita y de calidad es el mejor instrumento para romper el ciclo de la pobreza y ofrecer a las nuevas generaciones una vida mejor.' ¿Qué título corresponde?", options:["La educación como puerta de salida de la pobreza","La educación privada es superior","Solo el trabajo puede acabar con la pobreza","Los jóvenes rechazan la educación"], correctAnswer:"La educación como puerta de salida de la pobreza", difficulty:"easy", points:10 },
  { id:"gap-hm-9", themeId:"sharing-planet", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'Cada año, el Amazonas pierde una zona de selva equivalente a tres veces el tamaño de Portugal. Los científicos advierten que esto puede ser irreversible.' ¿Qué título es más adecuado?", options:["La deforestación del Amazonas alcanza niveles alarmantes","El turismo en el Amazonas crece","Las especies amazónicas están a salvo","Brasil lidera la reforestación mundial"], correctAnswer:"La deforestación del Amazonas alcanza niveles alarmantes", difficulty:"medium", points:20 },
  { id:"gap-hm-10", themeId:"sharing-planet", type:"mcq", prompt:"[Encabezado - párrafo] Lee: 'Los vehículos eléctricos no emiten CO2 durante su uso y reducen significativamente la dependencia del petróleo. Sin embargo, su batería requiere materiales como el litio, cuya extracción también tiene impacto ambiental.' ¿Qué título es más completo?", options:["Los vehículos eléctricos: ventajas y desafíos medioambientales","Los coches eléctricos son perfectos","El litio no es importante","Los coches de gasolina son mejores"], correctAnswer:"Los vehículos eléctricos: ventajas y desafíos medioambientales", difficulty:"medium", points:20 },
  { id:"gap-hm-11", themeId:"identities", type:"mcq", prompt:"[Encabezado] Lee: 'Meditar diez minutos al día puede reducir el cortisol, la hormona del estrés, y mejorar la concentración y el bienestar general.' ¿Qué título es correcto?", options:["Los beneficios científicos de la meditación","La meditación es solo para adultos","La religión y la meditación son lo mismo","El estrés no existe"], correctAnswer:"Los beneficios científicos de la meditación", difficulty:"easy", points:10 },
  { id:"gap-hm-12", themeId:"experiences", type:"mcq", prompt:"[Encabezado] Lee: 'Al mudarse a otro país, muchos inmigrantes describen una primera etapa de emoción, seguida de un período de dificultad y añoranza, y finalmente de adaptación y aceptación.' ¿Qué título corresponde?", options:["Las etapas de adaptación del inmigrante","Los peligros del viaje","El regreso al país natal","La deportación y sus efectos"], correctAnswer:"Las etapas de adaptación del inmigrante", difficulty:"medium", points:20 },
  { id:"gap-hm-13", themeId:"human-ingenuity", type:"mcq", prompt:"[Encabezado] Lee: 'Plataformas como Spotify, Netflix y YouTube han cambiado radicalmente cómo consumimos música, series y videos — ahora todo está disponible a demanda, sin horarios fijos.' ¿Qué título es adecuado?", options:["El streaming transforma el consumo de entretenimiento","La televisión tradicional domina","El cine va a desaparecer","La música ya no existe"], correctAnswer:"El streaming transforma el consumo de entretenimiento", difficulty:"easy", points:10 },
  { id:"gap-hm-14", themeId:"social-organization", type:"mcq", prompt:"[Encabezado] Lee: 'El voluntariado no solo beneficia a quienes reciben la ayuda, sino también a quienes la ofrecen, mejorando su salud mental, sus habilidades sociales y su sentido de propósito.' ¿Qué título corresponde?", options:["El voluntariado: beneficioso para todos","El voluntariado es obligatorio","Solo los jóvenes pueden ser voluntarios","El voluntariado no sirve para nada"], correctAnswer:"El voluntariado: beneficioso para todos", difficulty:"easy", points:10 },
  { id:"gap-hm-15", themeId:"sharing-planet", type:"mcq", prompt:"[Encabezado] Lee: 'La energía solar y la eólica son hoy las fuentes de electricidad más baratas de la historia. Sin embargo, requieren sistemas de almacenamiento para funcionar cuando no hay sol ni viento.' ¿Qué título es más correcto?", options:["Las energías renovables: asequibles pero con limitaciones","Las energías renovables son perfectas","La energía solar es cara","El petróleo es mejor que el sol"], correctAnswer:"Las energías renovables: asequibles pero con limitaciones", difficulty:"medium", points:20 },

  // =========================================================================
  // 7. WORD-BANK GAP-FILL (~60 questions - MCQ with 6 options to fill blank)
  // =========================================================================

  { id:"gap-wb-1", themeId:"identities", type:"mcq", prompt:"[Banco de palabras] 'La ___ de un adolescente depende mucho de su entorno familiar y cultural.' Elige la palabra más adecuada:", options:["identidad","habitación","educación","decisión"], correctAnswer:"identidad", difficulty:"easy", points:10 },
  { id:"gap-wb-2", themeId:"identities", type:"mcq", prompt:"[Banco de palabras] 'El ___ de grupo puede llevar a los jóvenes a tomar malas decisiones.' Elige la palabra correcta:", options:["presión","precio","proceso","progreso"], correctAnswer:"presión", difficulty:"easy", points:10, explanation:"'La presión de grupo' = peer pressure." },
  { id:"gap-wb-3", themeId:"identities", type:"mcq", prompt:"[Banco de palabras] 'La ___ es la base de una sociedad democrática y justa.' Elige la palabra correcta:", options:["tolerancia","tecnología","tradición","televisión"], correctAnswer:"tolerancia", difficulty:"easy", points:10 },
  { id:"gap-wb-4", themeId:"identities", type:"mcq", prompt:"[Banco de palabras] 'La ___ permite ponerse en el lugar de otra persona y comprender sus sentimientos.' Elige:", options:["empatía","energía","economía","etnología"], correctAnswer:"empatía", difficulty:"easy", points:10 },
  { id:"gap-wb-5", themeId:"experiences", type:"mcq", prompt:"[Banco de palabras] 'Los inmigrantes a menudo sienten ___ por su país de origen.' Elige la palabra correcta:", options:["nostalgia","noticias","necesidad","normativa"], correctAnswer:"nostalgia", difficulty:"easy", points:10 },
  { id:"gap-wb-6", themeId:"experiences", type:"mcq", prompt:"[Banco de palabras] 'El ___ cultural ayuda a los recién llegados a entender las costumbres del nuevo país.' Elige:", options:["intercambio","instrumento","interés","idioma"], correctAnswer:"intercambio", difficulty:"medium", points:20, explanation:"'El intercambio cultural' = cultural exchange, which helps newcomers adapt." },
  { id:"gap-wb-7", themeId:"experiences", type:"mcq", prompt:"[Banco de palabras] 'La ___ es una celebración mexicana en honor a los difuntos el 1 y 2 de noviembre.' Elige:", options:["ofrenda","orquesta","oración","ocasión"], correctAnswer:"ofrenda", difficulty:"medium", points:20, explanation:"In Día de los Muertos, 'la ofrenda' (offering/altar) is a central element." },
  { id:"gap-wb-8", themeId:"experiences", type:"mcq", prompt:"[Banco de palabras] 'El ___ cultural ocurre cuando alguien llega a un país con costumbres muy diferentes.' Elige:", options:["choque","cambio","charla","campo"], correctAnswer:"choque", difficulty:"easy", points:10 },
  { id:"gap-wb-9", themeId:"human-ingenuity", type:"mcq", prompt:"[Banco de palabras] 'La ___ puede propagar noticias falsas en pocos minutos a millones de personas.' Elige:", options:["desinformación","desigualdad","democracia","declaración"], correctAnswer:"desinformación", difficulty:"medium", points:20 },
  { id:"gap-wb-10", themeId:"human-ingenuity", type:"mcq", prompt:"[Banco de palabras] 'La ___ artificial ya puede crear imágenes y textos que parecen reales.' Elige:", options:["inteligencia","información","innovación","integración"], correctAnswer:"inteligencia", difficulty:"easy", points:10 },
  { id:"gap-wb-11", themeId:"human-ingenuity", type:"mcq", prompt:"[Banco de palabras] 'El ___ de autor protege las obras creativas de ser copiadas sin permiso.' Elige:", options:["derecho","deber","dato","diagrama"], correctAnswer:"derecho", difficulty:"medium", points:20 },
  { id:"gap-wb-12", themeId:"social-organization", type:"mcq", prompt:"[Banco de palabras] 'La ___ entre ricos y pobres continúa creciendo en muchos países.' Elige:", options:["brecha","barrera","burocracia","batalla"], correctAnswer:"brecha", difficulty:"medium", points:20 },
  { id:"gap-wb-13", themeId:"social-organization", type:"mcq", prompt:"[Banco de palabras] 'El ___ universal garantiza que todos los ciudadanos puedan votar.' Elige:", options:["sufragio","sueldo","subsidio","servicio"], correctAnswer:"sufragio", difficulty:"hard", points:30 },
  { id:"gap-wb-14", themeId:"social-organization", type:"mcq", prompt:"[Banco de palabras] 'La ___ social es esencial para construir una sociedad más igualitaria.' Elige:", options:["justicia","juventud","jubilación","jornada"], correctAnswer:"justicia", difficulty:"easy", points:10 },
  { id:"gap-wb-15", themeId:"sharing-planet", type:"mcq", prompt:"[Banco de palabras] 'El ___ climático amenaza la existencia de muchas especies animales y vegetales.' Elige:", options:["cambio","calor","choque","corte"], correctAnswer:"cambio", difficulty:"easy", points:10 },
  { id:"gap-wb-16", themeId:"sharing-planet", type:"mcq", prompt:"[Banco de palabras] 'La ___ de carbono mide el impacto ambiental de nuestras actividades cotidianas.' Elige:", options:["huella","hoja","herramienta","historia"], correctAnswer:"huella", difficulty:"medium", points:20 },
  { id:"gap-wb-17", themeId:"sharing-planet", type:"mcq", prompt:"[Banco de palabras] 'La ___ contribuye a la pérdida de hábitats y al calentamiento global.' Elige:", options:["deforestación","deportación","democracia","discriminación"], correctAnswer:"deforestación", difficulty:"easy", points:10 },
  { id:"gap-wb-18", themeId:"identities", type:"mcq", prompt:"[Banco de palabras - oración compleja] 'La ___ es el proceso por el que los jóvenes dejan de ser niños y asumen responsabilidades adultas.' Elige:", options:["madurez","meditación","migración","memoria"], correctAnswer:"madurez", difficulty:"medium", points:20 },
  { id:"gap-wb-19", themeId:"experiences", type:"mcq", prompt:"[Banco de palabras] 'La ___ de los inmigrantes en la sociedad de acogida depende de muchos factores culturales y económicos.' Elige:", options:["integración","investigación","institución","instalación"], correctAnswer:"integración", difficulty:"medium", points:20 },
  { id:"gap-wb-20", themeId:"human-ingenuity", type:"mcq", prompt:"[Banco de palabras] 'El ___ periodístico debe verificar la información antes de publicarla.' Elige:", options:["periodista","pasaporte","proceso","protocolo"], correctAnswer:"periodista", difficulty:"easy", points:10 },
  { id:"gap-wb-21", themeId:"social-organization", type:"mcq", prompt:"[Banco de palabras] 'La ___ pública garantiza que todos los ciudadanos tengan acceso a servicios médicos.' Elige:", options:["sanidad","sociedad","seguridad","selección"], correctAnswer:"sanidad", difficulty:"medium", points:20 },
  { id:"gap-wb-22", themeId:"sharing-planet", type:"mcq", prompt:"[Banco de palabras] 'Las ___ renovables como la solar y la eólica son esenciales para combatir el cambio climático.' Elige:", options:["energías","empresas","emisiones","estrategias"], correctAnswer:"energías", difficulty:"easy", points:10 },
  { id:"gap-wb-23", themeId:"identities", type:"mcq", prompt:"[Banco de palabras - conector] 'El bilingüismo tiene muchas ventajas; ___, puede ser un desafío para algunos niños.' Elige el conector correcto:", options:["sin embargo","además","por lo tanto","ya que"], correctAnswer:"sin embargo", difficulty:"medium", points:20, explanation:"'Sin embargo' (however) introduces a contrast/limitation after a positive claim." },
  { id:"gap-wb-24", themeId:"experiences", type:"mcq", prompt:"[Banco de palabras - conector] 'Emigrar es difícil; ___, muchas personas lo hacen para dar una vida mejor a su familia.' Elige el conector:", options:["no obstante","además","aunque","ya sea"], correctAnswer:"no obstante", difficulty:"medium", points:20, explanation:"'No obstante' = nevertheless — introduces a contrasting idea." },
  { id:"gap-wb-25", themeId:"human-ingenuity", type:"mcq", prompt:"[Banco de palabras - conector] '___ los avances tecnológicos tienen beneficios, también presentan riesgos éticos.' Elige el conector:", options:["Aunque","Porque","Además","Cuando"], correctAnswer:"Aunque", difficulty:"medium", points:20, explanation:"'Aunque' = although — introduces a concession." },
  { id:"gap-wb-26", themeId:"social-organization", type:"mcq", prompt:"[Banco de palabras - verbo] 'El gobierno debe ___ medidas para reducir la desigualdad económica.' Elige el verbo:", options:["tomar","tener","traer","tocar"], correctAnswer:"tomar", difficulty:"easy", points:10, explanation:"'Tomar medidas' = to take measures — a fixed collocation." },
  { id:"gap-wb-27", themeId:"sharing-planet", type:"mcq", prompt:"[Banco de palabras - verbo] 'Todos debemos ___ el agua y reducir el consumo de plásticos.' Elige el verbo:", options:["conservar","conseguir","conocer","controlar"], correctAnswer:"conservar", difficulty:"easy", points:10 },
  { id:"gap-wb-28", themeId:"identities", type:"mcq", prompt:"[Banco de palabras - adjetivo] 'La identidad cultural de una persona es ___ y cambia con las experiencias de vida.' Elige:", options:["dinámica","dramática","difícil","desconocida"], correctAnswer:"dinámica", difficulty:"medium", points:20 },
  { id:"gap-wb-29", themeId:"experiences", type:"mcq", prompt:"[Banco de palabras - adjetivo] 'La experiencia de vivir en otro país puede ser ___ pero también enriquecedora.' Elige:", options:["desafiante","deliciosa","divertida","desesperada"], correctAnswer:"desafiante", difficulty:"medium", points:20, explanation:"'Desafiante' = challenging — an appropriate adjective for the difficulty of living abroad." },
  { id:"gap-wb-30", themeId:"sharing-planet", type:"mcq", prompt:"[Banco de palabras - verbo modal] 'Los países ___ comprometerse a reducir sus emisiones de CO2.' Elige la forma más adecuada:", options:["deben","debían","debieron","deberían"], correctAnswer:"deben", difficulty:"medium", points:20, explanation:"'Deben' (present: they must) expresses an obligation in the present context." },

  // =========================================================================
  // 8. SHARING THE PLANET — Extra questions (~60 questions)
  // =========================================================================

  { id:"gap-stp-e1", themeId:"sharing-planet", type:"mcq", prompt:"[Tema 5] ¿Qué es 'la agenda 2030' de la ONU?", options:["A plan with 17 sustainable development goals","A document about trade","A climate conference","A list of endangered species"], correctAnswer:"A plan with 17 sustainable development goals", difficulty:"hard", points:30 },
  { id:"gap-stp-e2", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'endangered species' en español?", correctAnswer:"las especies en peligro de extinción", difficulty:"medium", points:20 },
  { id:"gap-stp-e3", themeId:"sharing-planet", type:"mcq", prompt:"[Comprensión] 'El 71% de la superficie terrestre está cubierta por agua, pero solo el 3% es agua dulce.' ¿Qué porcentaje de agua dulce hay?", options:["3%","71%","29%","50%"], correctAnswer:"3%", difficulty:"easy", points:10 },
  { id:"gap-stp-e4", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la contaminación acústica'?", options:["noise pollution","water pollution","light pollution","soil pollution"], correctAnswer:"noise pollution", difficulty:"medium", points:20 },
  { id:"gap-stp-e5", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'overpopulation' en español?", correctAnswer:"la superpoblación", difficulty:"hard", points:30 },
  { id:"gap-stp-e6", themeId:"sharing-planet", type:"mcq", prompt:"[Comprensión] 'La economía circular propone reutilizar y reparar los productos en lugar de descartarlos.' ¿Qué propone la economía circular?", options:["Reutilizar y reparar en lugar de desechar","Producir más a menor costo","Importar más productos","Construir más fábricas"], correctAnswer:"Reutilizar y reparar en lugar de desechar", difficulty:"easy", points:10 },
  { id:"gap-stp-e7", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la soberanía alimentaria'?", options:["food sovereignty / right of peoples to control their food systems","food safety regulations","a type of diet","a government food program"], correctAnswer:"food sovereignty / right of peoples to control their food systems", difficulty:"hard", points:30 },
  { id:"gap-stp-e8", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'greenhouse gas' en español?", correctAnswer:"el gas de efecto invernadero", difficulty:"medium", points:20 },
  { id:"gap-stp-e9", themeId:"sharing-planet", type:"mcq", prompt:"[Gramática en contexto] 'Si todos ___ (usar) menos plástico, habría menos contaminación oceánica.' ¿Cuál es correcto?", options:["usáramos","usamos","usaremos","usaríamos"], correctAnswer:"usáramos", difficulty:"hard", points:30, explanation:"Si + imperfect subjunctive (usáramos) → conditional (habría). Hypothetical past condition." },
  { id:"gap-stp-e10", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la erosión del suelo'?", options:["soil erosion","water erosion","erosion of buildings","coastal erosion only"], correctAnswer:"soil erosion", difficulty:"medium", points:20 },
  { id:"gap-stp-e11", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'solar panel' en español?", correctAnswer:"el panel solar", difficulty:"easy", points:10 },
  { id:"gap-stp-e12", themeId:"sharing-planet", type:"mcq", prompt:"[Comprensión] 'Los incendios forestales se han triplicado en la última década debido al calentamiento global.' ¿Cuánto han aumentado los incendios?", options:["Se han triplicado","Se han duplicado","Han disminuido","Han desaparecido"], correctAnswer:"Se han triplicado", difficulty:"easy", points:10 },
  { id:"gap-stp-e13", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la depredación'?", options:["predation (animals preying on others)","depression","deprivation","deforestation"], correctAnswer:"predation (animals preying on others)", difficulty:"hard", points:30 },
  { id:"gap-stp-e14", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'wind turbine' en español?", correctAnswer:"el aerogenerador", difficulty:"hard", points:30 },
  { id:"gap-stp-e15", themeId:"sharing-planet", type:"mcq", prompt:"[Texto IB] 'La sobrepesca amenaza el equilibrio de los ecosistemas marinos.' ¿Qué amenaza la sobrepesca?", options:["El equilibrio de los ecosistemas marinos","El turismo costero","La pesca artesanal","Los precios del pescado"], correctAnswer:"El equilibrio de los ecosistemas marinos", difficulty:"easy", points:10 },
  { id:"gap-stp-e16", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la gestión de residuos'?", options:["waste management","waste production","garbage collection only","recyclable materials"], correctAnswer:"waste management", difficulty:"medium", points:20 },
  { id:"gap-stp-e17", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'coral reef' en español?", correctAnswer:"el arrecife de coral", difficulty:"hard", points:30 },
  { id:"gap-stp-e18", themeId:"sharing-planet", type:"mcq", prompt:"[Gramática] '¡___ (proteger, nosotros) los océanos!' ¿Cuál es el imperativo correcto?", options:["Protejamos","Protegemos","Proteger","Protegían"], correctAnswer:"Protejamos", difficulty:"hard", points:30, explanation:"Nosotros imperative of proteger: proteger → protejamos (stem change g→j before e)." },
  { id:"gap-stp-e19", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la capa de ozono'?", options:["ozone layer","carbon layer","oxygen layer","atmosphere layer"], correctAnswer:"ozone layer", difficulty:"medium", points:20 },
  { id:"gap-stp-e20", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'fossil fuels' en español?", correctAnswer:"los combustibles fósiles", difficulty:"medium", points:20 },
  { id:"gap-stp-e21", themeId:"sharing-planet", type:"mcq", prompt:"[IB Oral tema 5] ¿Cuál de estas sería una buena tesis para el IO sobre el medio ambiente?", options:["La transición a energías renovables es urgente y posible, pero requiere voluntad política global.","El medio ambiente es importante.","Hay que reciclar más.","Los animales son bonitos y deben protegerse."], correctAnswer:"La transición a energías renovables es urgente y posible, pero requiere voluntad política global.", difficulty:"medium", points:20 },
  { id:"gap-stp-e22", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la contaminación lumínica'?", options:["light pollution (excess artificial light)","luminous contamination of water","contamination by phosphorus","solar flares"], correctAnswer:"light pollution (excess artificial light)", difficulty:"hard", points:30 },
  { id:"gap-stp-e23", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'carbon neutral' en español?", correctAnswer:"neutro en carbono", difficulty:"hard", points:30 },
  { id:"gap-stp-e24", themeId:"sharing-planet", type:"mcq", prompt:"[Comprensión] 'Los incendios del Amazonas afectan no solo a Brasil sino a todo el planeta.' ¿A quién afectan los incendios?", options:["A todo el planeta","Solo a Brasil","Solo a Sudamérica","Solo a los animales"], correctAnswer:"A todo el planeta", difficulty:"easy", points:10 },
  { id:"gap-stp-e25", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la sequía'?", options:["drought","earthquake","storm","tsunami"], correctAnswer:"drought", difficulty:"medium", points:20 },
  { id:"gap-stp-e26", themeId:"sharing-planet", type:"puzzle", prompt:"[Ordenar] Crea una oración sobre la deforestación:", options:["bosques","la","destruye","deforestación","los","hábitat","y","la","de"], correctAnswer:"la deforestación destruye los bosques y el hábitat de la fauna", difficulty:"hard", points:30 },
  { id:"gap-stp-e27", themeId:"sharing-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'el vertedero'?", options:["landfill / dump","water reservoir","windmill","recycling center"], correctAnswer:"landfill / dump", difficulty:"hard", points:30 },
  { id:"gap-stp-e28", themeId:"sharing-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'climate refugee' en español?", correctAnswer:"el refugiado climático", difficulty:"hard", points:30 },
  { id:"gap-stp-e29", themeId:"sharing-planet", type:"mcq", prompt:"[Comprensión] 'El plástico tarda más de 400 años en degradarse en el medio ambiente.' ¿Cuánto tarda en degradarse?", options:["Más de 400 años","10 años","50 años","100 años"], correctAnswer:"Más de 400 años", difficulty:"easy", points:10 },
  { id:"gap-stp-e30", themeId:"sharing-planet", type:"listening", prompt:"[Escuchar] Selecciona la traducción correcta:", audioText:"Sin acción inmediata, muchas especies desaparecerán antes de que podamos estudiarlas.", options:["Without immediate action, many species will disappear before we can study them.","Scientists are already studying all endangered species.","Many species disappeared in the past.","Species only disappear due to hunting."], correctAnswer:"Without immediate action, many species will disappear before we can study them.", difficulty:"medium", points:20 },

  // =========================================================================
  // 9. PLUPERFECT / PRESENT PERFECT (~30 questions)
  // =========================================================================

  { id:"gap-pl-1", themeId:"identities", type:"mcq", prompt:"[Pretérito perfecto] 'Este año, ___ (aprender/yo) mucho sobre mi cultura familiar.' ¿Cuál es correcto?", options:["he aprendido","aprendí","había aprendido","aprendo"], correctAnswer:"he aprendido", difficulty:"medium", points:20, explanation:"Pretérito perfecto (he/ha/has + participle) = action in a time period including now (este año)." },
  { id:"gap-pl-2", themeId:"experiences", type:"mcq", prompt:"[Pretérito perfecto] '¿___ (ver/tú) alguna vez el Machu Picchu?' ¿Cuál es correcto?", options:["Has visto","Viste","Habías visto","Ves"], correctAnswer:"Has visto", difficulty:"medium", points:20, explanation:"Have you ever seen = ¿Has + past participle? (present perfect)." },
  { id:"gap-pl-3", themeId:"human-ingenuity", type:"mcq", prompt:"[Pluscuamperfecto] 'Cuando llegué al laboratorio, los científicos ya ___ (terminar) el experimento.' ¿Cuál es correcto?", options:["habían terminado","terminaron","habían terminaron","han terminado"], correctAnswer:"habían terminado", difficulty:"hard", points:30, explanation:"Pluperfect (había/habían + past participle) = completed before another past event." },
  { id:"gap-pl-4", themeId:"social-organization", type:"mcq", prompt:"[Pluscuamperfecto] 'El candidato declaró que nunca ___ (decir) eso.' ¿Cuál es correcto?", options:["había dicho","decía","dijo","ha dicho"], correctAnswer:"había dicho", difficulty:"hard", points:30, explanation:"Pluperfect: action before another past action (he declared that he had never said that)." },
  { id:"gap-pl-5", themeId:"sharing-planet", type:"mcq", prompt:"[Pretérito perfecto] 'Los científicos ___ (descubrir) nuevas especies en el Amazonas este año.' ¿Cuál es correcto?", options:["han descubierto","descubrieron","habían descubierto","descubren"], correctAnswer:"han descubierto", difficulty:"medium", points:20 },
  { id:"gap-pl-6", themeId:"identities", type:"short", prompt:"[Participo irregular] ¿Cuál es el participio pasado de 'hacer'?", correctAnswer:"hecho", difficulty:"medium", points:20, explanation:"Irregular past participles: hacer→hecho, decir→dicho, ver→visto, volver→vuelto, escribir→escrito." },
  { id:"gap-pl-7", themeId:"experiences", type:"short", prompt:"[Participio irregular] ¿Cuál es el participio pasado de 'escribir'?", correctAnswer:"escrito", difficulty:"easy", points:10 },
  { id:"gap-pl-8", themeId:"human-ingenuity", type:"short", prompt:"[Participio irregular] ¿Cuál es el participio pasado de 'romper'?", correctAnswer:"roto", difficulty:"medium", points:20 },
  { id:"gap-pl-9", themeId:"social-organization", type:"short", prompt:"[Participio irregular] ¿Cuál es el participio pasado de 'ver'?", correctAnswer:"visto", difficulty:"easy", points:10 },
  { id:"gap-pl-10", themeId:"sharing-planet", type:"short", prompt:"[Participio irregular] ¿Cuál es el participio pasado de 'abrir'?", correctAnswer:"abierto", difficulty:"medium", points:20 },
  { id:"gap-pl-11", themeId:"identities", type:"mcq", prompt:"[Futuro perfecto] 'Para el año 2050, los científicos ___ (encontrar) una solución al cambio climático.' ¿Cuál es correcto?", options:["habrán encontrado","encuentran","habrían encontrado","van a encontrar"], correctAnswer:"habrán encontrado", difficulty:"hard", points:30, explanation:"Future perfect (habrá/habrán + past participle) = will have done something by a future point." },
  { id:"gap-pl-12", themeId:"experiences", type:"mcq", prompt:"[Pretérito perfecto vs pretérito] En España, ¿cuál se prefiere para una acción reciente de hoy?", options:["Pretérito perfecto (he comido)","Pretérito indefinido (comí)","Son iguales","Imperfecto (comía)"], correctAnswer:"Pretérito perfecto (he comido)", difficulty:"hard", points:30, explanation:"In Spain, present perfect (he comido) is used for recent/today actions. Latin America prefers preterite (comí)." },
  { id:"gap-pl-13", themeId:"human-ingenuity", type:"mcq", prompt:"[Pluscuamperfecto] ¿Cuál de estas oraciones usa el pluscuamperfecto correctamente?", options:["Cuando llegué, ya se habían marchado.","Cuando llegué, ya se marcharon.","Cuando llego, ya se habían marchado.","Cuando llegué, ya se marchan."], correctAnswer:"Cuando llegué, ya se habían marchado.", difficulty:"hard", points:30 },
  { id:"gap-pl-14", themeId:"social-organization", type:"mcq", prompt:"[Condicional perfecto] 'Con más fondos, el proyecto ___ (tener) más éxito.' ¿Cuál es correcto?", options:["habría tenido","habría tener","tendría","hubiese tenido"], correctAnswer:"habría tenido", difficulty:"hard", points:30, explanation:"Conditional perfect (habría + past participle) = would have had." },
  { id:"gap-pl-15", themeId:"sharing-planet", type:"mcq", prompt:"[Pretérito perfecto] '¿Has visitado alguna vez una reserva natural?' Esta pregunta usa:", options:["El pretérito perfecto compuesto","El pretérito indefinido","El futuro","El imperfecto"], correctAnswer:"El pretérito perfecto compuesto", difficulty:"medium", points:20 },

  // =========================================================================
  // 10. ADVANCED GRAMMAR MIXED (~30 questions)
  // =========================================================================

  { id:"gap-adv-1", themeId:"identities", type:"mcq", prompt:"[Estilo indirecto] 'Ella dijo: \"Soy española.\"' → Estilo indirecto: 'Ella dijo que ___ española.'", options:["era","es","será","fuera"], correctAnswer:"era", difficulty:"hard", points:30, explanation:"Indirect speech shifts present (soy→era) to past when the reporting verb is past (dijo)." },
  { id:"gap-adv-2", themeId:"experiences", type:"mcq", prompt:"[Estilo indirecto] '\"Voy a viajar mañana\", dijo Pablo.' → Estilo indirecto: 'Pablo dijo que ___ a viajar al día siguiente.'", options:["iba","va","irá","iría"], correctAnswer:"iba", difficulty:"hard", points:30, explanation:"Present 'voy' → imperfect 'iba' in indirect speech after a past reporting verb." },
  { id:"gap-adv-3", themeId:"human-ingenuity", type:"mcq", prompt:"[Subjuntivo perfecto] 'Me alegra que ___ (inventar/ellos) esa tecnología.' ¿Cuál es correcto?", options:["hayan inventado","han inventado","hubieran inventado","inventaron"], correctAnswer:"hayan inventado", difficulty:"hard", points:30, explanation:"Present subjunctive perfect (haya/hayan + past participle) after emotion expressions." },
  { id:"gap-adv-4", themeId:"social-organization", type:"mcq", prompt:"[Subjuntivo imperfecto] 'Ojalá ___ (haber) más igualdad en el mundo.' ¿Cuál es correcto?", options:["hubiera","haya","habrá","hay"], correctAnswer:"hubiera", difficulty:"hard", points:30, explanation:"'Ojalá' with imperfect subjunctive = wish about something unlikely/hypothetical: ojalá hubiera = I wish there were." },
  { id:"gap-adv-5", themeId:"sharing-planet", type:"mcq", prompt:"[Subjuntivo con 'cuando'] 'Cuando ___ (llegar) las nuevas tecnologías, el mundo cambiará.' ¿Cuál es correcto?", options:["lleguen","llegan","llegaban","llegarán"], correctAnswer:"lleguen", difficulty:"hard", points:30, explanation:"After 'cuando' referring to the future, use the present subjunctive: lleguen." },
  { id:"gap-adv-6", themeId:"identities", type:"mcq", prompt:"[Diminutivos] '¡Qué casa tan ___!' ¿Cuál es el diminutivo correcto de 'casa pequeña'?", options:["casita","casona","casilla","casaza"], correctAnswer:"casita", difficulty:"medium", points:20, explanation:"Diminutive suffix -ita/-ito makes something smaller/endearing: casita = little house." },
  { id:"gap-adv-7", themeId:"experiences", type:"mcq", prompt:"[Aumentativos] 'Ese hombre es muy grande.' — ¿Cuál es el aumentativo de 'grande'?", options:["grandote","grandito","grandísimo como peyorativo","pequeñote"], correctAnswer:"grandote", difficulty:"medium", points:20, explanation:"Augmentative suffix -ote/-ota: grandote = big/oversized." },
  { id:"gap-adv-8", themeId:"human-ingenuity", type:"mcq", prompt:"[Superlativo absoluto] 'La tecnología es ___ (muy + importante) para nuestra vida.' ¿Cuál es el superlativo absoluto correcto?", options:["importantísima","muy importantísima","la más importante","importantamente"], correctAnswer:"importantísima", difficulty:"medium", points:20, explanation:"Superlativo absoluto: add -ísimo/a to the adjective (drop final vowel first): importante → importantísima." },
  { id:"gap-adv-9", themeId:"social-organization", type:"mcq", prompt:"[Perífrasis verbales] '¿Qué significa 'llevar + gerundio'?' Elige la opción correcta:", options:["Indica una acción que lleva cierto tiempo realizándose","Indica una acción futura","Indica una acción ya terminada","Indica un deseo"], correctAnswer:"Indica una acción que lleva cierto tiempo realizándose", difficulty:"hard", points:30, explanation:"'Llevo viviendo aquí tres años' = I have been living here for three years (duration in progress)." },
  { id:"gap-adv-10", themeId:"sharing-planet", type:"mcq", prompt:"[Gerundio vs infinitivo] Elige la forma correcta: '___ (reciclar) es fundamental para el medio ambiente.'", options:["Reciclar","Reciclando","Reciclo","Reciclad"], correctAnswer:"Reciclar", difficulty:"medium", points:20, explanation:"As the subject of a sentence, use the infinitive (not gerund): 'Reciclar es fundamental'." },
  { id:"gap-adv-11", themeId:"identities", type:"mcq", prompt:"[Pronombres relativos - avanzado] 'Lo que más me gusta de mi cultura es la música.' ¿Qué función tiene 'lo que' aquí?", options:["Pronombre relativo neutro que reemplaza una idea abstracta","Objeto directo normal","Pronombre de persona","Adverbio de tiempo"], correctAnswer:"Pronombre relativo neutro que reemplaza una idea abstracta", difficulty:"hard", points:30, explanation:"'Lo que' = what / that which — a neuter relative pronoun referring to an abstract concept." },
  { id:"gap-adv-12", themeId:"experiences", type:"mcq", prompt:"[Condicional si - niveles] ¿Cuál de estos pares es una condición REAL (probable)?", options:["Si tengo tiempo, voy al museo.","Si tuviera tiempo, iría al museo.","Si hubiera tenido tiempo, habría ido.","Si tuviese tiempo, fuera al museo."], correctAnswer:"Si tengo tiempo, voy al museo.", difficulty:"hard", points:30, explanation:"Real condition: Si + present indicative → present/future. Hypothetical uses imperfect subjunctive + conditional." },
  { id:"gap-adv-13", themeId:"human-ingenuity", type:"mcq", prompt:"[Condicional si - hipotético] 'Si ___ (tener/yo) más tiempo, ___ (aprender) a programar.' ¿Cuál es correcto?", options:["tuviera / aprendería","tengo / aprendo","tendré / aprenderé","tenía / aprendía"], correctAnswer:"tuviera / aprendería", difficulty:"hard", points:30, explanation:"Hypothetical: Si + imperfect subjunctive → conditional." },
  { id:"gap-adv-14", themeId:"social-organization", type:"mcq", prompt:"[Discurso formal - registro] ¿Cuál de estas expresiones es más formal para introducir una argumentación?", options:["Cabe señalar que...","Pues mira...","Lo que pasa es que...","O sea..."], correctAnswer:"Cabe señalar que...", difficulty:"medium", points:20, explanation:"'Cabe señalar que' = it is worth noting that — formal academic language." },
  { id:"gap-adv-15", themeId:"sharing-planet", type:"mcq", prompt:"[Concordancia sujeto-verbo] '¿Cuál de las siguientes oraciones tiene concordancia correcta?'", options:["La mayoría de los ciudadanos apoya la ley.","La mayoría de los ciudadanos apoyan la ley.","Ambas son aceptables en español","La mayoría apoyan"], correctAnswer:"Ambas son aceptables en español", difficulty:"hard", points:30, explanation:"'La mayoría de + noun' can take singular or plural verb in Spanish — both are accepted." },
];

module.exports = { questions };
