/// scripts/gap_questions_bank_2.cjs
/// Second grammar-drill batch, filling gaps left after gap_questions_bank.cjs:
///   1. Ser vs. Estar (~25 Qs)
///   2. Gustar-type verbs + indirect object pronouns (~25 Qs)
///   3. Direct/indirect object pronouns & placement (~25 Qs)
///   4. Reflexive verbs (~20 Qs)
///   5. Negation (~20 Qs)
///   6. Comparatives & superlatives (~20 Qs)
///   7. Numbers, dates & time expressions (~25 Qs)
///   8. Question words: qué vs. cuál vs. por qué (~20 Qs)

const questions = [

  // =========================================================================
  // 1. SER vs ESTAR (~25 questions)
  // =========================================================================

  { id:"gap2-se-1", themeId:"identities", type:"mcq", prompt:"[Ser/Estar] 'Mi hermana ___ profesora de historia.' ¿Cuál es correcto?", options:["es","está","fue estar","siendo"], correctAnswer:"es", difficulty:"easy", points:10, explanation:"SER + profession (permanent characteristic)." },
  { id:"gap2-se-2", themeId:"identities", type:"mcq", prompt:"[Ser/Estar] 'Hoy ___ muy cansada porque no dormí bien.' ¿Cuál es correcto?", options:["estoy","soy","he estar","siendo"], correctAnswer:"estoy", difficulty:"easy", points:10, explanation:"ESTAR + adjective describing a temporary state/condition." },
  { id:"gap2-se-3", themeId:"identities", type:"mcq", prompt:"[Ser/Estar] '¿De dónde ___ tú?' ¿Cuál es correcto?", options:["eres","estás","fuiste estar","estarás siendo"], correctAnswer:"eres", difficulty:"easy", points:10, explanation:"SER + de = origin (where someone is from)." },
  { id:"gap2-se-4", themeId:"identities", type:"mcq", prompt:"[Ser/Estar] 'La reunión ___ en la biblioteca esta tarde.' ¿Cuál es correcto?", options:["es","está","estará siendo","siendo"], correctAnswer:"es", difficulty:"hard", points:30, explanation:"SER = location of an EVENT (where it takes place). ESTAR is used for the location of people/objects, not events." },
  { id:"gap2-se-5", themeId:"experiences", type:"mcq", prompt:"[Ser/Estar] 'El museo ___ cerca de la plaza principal.' ¿Cuál es correcto?", options:["está","es","siendo","fue ser"], correctAnswer:"está", difficulty:"medium", points:20, explanation:"ESTAR = physical location of a place/object." },
  { id:"gap2-se-6", themeId:"experiences", type:"mcq", prompt:"[Ser/Estar] 'Después del viaje, la maleta ___ rota.' ¿Cuál es correcto?", options:["está","es","siendo","fue siendo"], correctAnswer:"está", difficulty:"medium", points:20, explanation:"ESTAR + past participle = resulting state/condition." },
  { id:"gap2-se-7", themeId:"experiences", type:"mcq", prompt:"[Ser/Estar] 'Esta sopa ___ deliciosa — ¡la cocinó mi abuela!' ¿Cuál es correcto?", options:["está","es","siendo","ha ser"], correctAnswer:"está", difficulty:"hard", points:30, explanation:"ESTAR with food/taste = a subjective reaction/impression at that moment, not an inherent quality." },
  { id:"gap2-se-8", themeId:"human-ingenuity", type:"mcq", prompt:"[Ser/Estar] 'El nuevo teléfono ___ hecho de materiales reciclados.' ¿Cuál es correcto?", options:["está","es","siendo","fue estar"], correctAnswer:"está", difficulty:"hard", points:30, explanation:"ESTAR + hecho de = made of / composed of (resulting state)." },
  { id:"gap2-se-9", themeId:"human-ingenuity", type:"mcq", prompt:"[Ser/Estar] 'Ese ingeniero ___ muy inteligente.' ¿Cuál es correcto?", options:["es","está","siendo","estará siendo"], correctAnswer:"es", difficulty:"easy", points:10, explanation:"SER + adjective = inherent/permanent characteristic (intelligence as a trait)." },
  { id:"gap2-se-10", themeId:"human-ingenuity", type:"mcq", prompt:"[Ser/Estar] 'La aplicación ___ diseñada por estudiantes universitarios.' ¿Cuál es correcto?", options:["fue","estuvo","tuvo","hubo"], correctAnswer:"fue", difficulty:"hard", points:30, explanation:"SER + past participle + por = passive voice (agent performing the action)." },
  { id:"gap2-se-11", themeId:"social-organization", type:"mcq", prompt:"[Ser/Estar] 'El alcalde ___ en una reunión importante ahora mismo.' ¿Cuál es correcto?", options:["está","es","siendo","fue ser"], correctAnswer:"está", difficulty:"easy", points:10, explanation:"ESTAR = temporary location/situation of a person right now." },
  { id:"gap2-se-12", themeId:"social-organization", type:"mcq", prompt:"[Ser/Estar] 'Aquella ley ___ injusta para muchos ciudadanos.' ¿Cuál es correcto?", options:["es","está","siendo","fue estar"], correctAnswer:"es", difficulty:"medium", points:20, explanation:"SER + adjective = an inherent quality/opinion about the nature of the law." },
  { id:"gap2-se-13", themeId:"social-organization", type:"mcq", prompt:"[Ser/Estar] '¡Qué guapo ___ hoy con ese traje!' ¿Cuál es correcto?", options:["estás","eres","siendo","has ser"], correctAnswer:"estás", difficulty:"hard", points:30, explanation:"ESTAR + adjective for appearance TODAY (a specific, temporary impression), contrasting with 'eres guapo' (you are handsome, in general)." },
  { id:"gap2-se-14", themeId:"sharing-planet", type:"mcq", prompt:"[Ser/Estar] 'El bosque ___ situado al norte del país.' ¿Cuál es correcto?", options:["está","es","siendo","fue ser"], correctAnswer:"está", difficulty:"medium", points:20, explanation:"ESTAR + situado/ubicado = physical location." },
  { id:"gap2-se-15", themeId:"sharing-planet", type:"mcq", prompt:"[Ser/Estar] 'El agua del río ___ contaminada desde hace meses.' ¿Cuál es correcto?", options:["está","es","siendo","fue ser"], correctAnswer:"está", difficulty:"medium", points:20, explanation:"ESTAR + past participle = a resulting/ongoing condition (not an inherent trait of water)." },
  { id:"gap2-se-16", themeId:"sharing-planet", type:"mcq", prompt:"[Ser/Estar] 'Proteger el medio ambiente ___ responsabilidad de todos.' ¿Cuál es correcto?", options:["es","está","siendo","fue estar"], correctAnswer:"es", difficulty:"easy", points:10, explanation:"SER + noun = definition/identification (X is Y)." },
  { id:"gap2-se-17", themeId:"identities", type:"short", prompt:"[Ser/Estar] Completa: 'Mis padres ___ (ser) de Argentina, pero ahora ___ (estar) viviendo en España.'", correctAnswer:"son / están", difficulty:"medium", points:20 },
  { id:"gap2-se-18", themeId:"experiences", type:"short", prompt:"[Ser/Estar] Completa: 'El concierto ___ (ser) el sábado en el estadio.'", correctAnswer:"es", difficulty:"medium", points:20 },
  { id:"gap2-se-19", themeId:"human-ingenuity", type:"short", prompt:"[Ser/Estar] Completa: 'Todavía no sabemos si el invento ___ (ser) seguro.'", correctAnswer:"es", difficulty:"medium", points:20 },
  { id:"gap2-se-20", themeId:"social-organization", type:"short", prompt:"[Ser/Estar] Completa: 'La votación ya ___ (estar) terminada.'", correctAnswer:"está", difficulty:"medium", points:20 },
  { id:"gap2-se-21", themeId:"sharing-planet", type:"short", prompt:"[Ser/Estar] Completa: 'Los osos polares ___ (estar) en peligro de extinción.'", correctAnswer:"están", difficulty:"medium", points:20 },
  { id:"gap2-se-22", themeId:"identities", type:"mcq", prompt:"[Ser/Estar - regla] ¿Qué verbo se usa para expresar el estado civil (soltero, casado, divorciado)?", options:["Ambos: 'ser' o 'estar' según el contexto/región","Solo 'ser'","Solo 'estar'","Ninguno de los dos"], correctAnswer:"Ambos: 'ser' o 'estar' según el contexto/región", difficulty:"hard", points:30, explanation:"Marital status can take either verb: 'es soltero' (identity) or 'está soltero' (current status) — both are used, with regional variation." },
  { id:"gap2-se-23", themeId:"experiences", type:"mcq", prompt:"[Ser/Estar] 'Ya ___ listos para salir de viaje.' ¿Cuál es correcto?", options:["estamos","somos","siendo","fuimos ser"], correctAnswer:"estamos", difficulty:"hard", points:30, explanation:"ESTAR listo = ready (a temporary state). SER listo means 'to be clever' — a different meaning entirely." },
  { id:"gap2-se-24", themeId:"human-ingenuity", type:"mcq", prompt:"[Ser/Estar] Elige la oración con el significado 'that scientist is clever':", options:["Ese científico es listo.","Ese científico está listo.","Ese científico fue listo.","Ese científico siendo listo."], correctAnswer:"Ese científico es listo.", difficulty:"hard", points:30, explanation:"'Ser listo' = to be clever/smart. 'Estar listo' = to be ready. Same adjective, different meaning by verb." },
  { id:"gap2-se-25", themeId:"social-organization", type:"mcq", prompt:"[Ser/Estar] '¿Cómo ___ la situación económica del país este año?' ¿Cuál es correcto?", options:["está","es","siendo","fue ser"], correctAnswer:"está", difficulty:"medium", points:20, explanation:"'¿Cómo está...?' asks about a current/changeable condition." },

  // =========================================================================
  // 2. GUSTAR-TYPE VERBS (~25 questions)
  // =========================================================================

  { id:"gap2-gu-1", themeId:"identities", type:"mcq", prompt:"[Gustar] 'A mí ___ gusta mucho la música latina.' ¿Cuál es el pronombre correcto?", options:["me","mi","yo","le"], correctAnswer:"me", difficulty:"easy", points:10, explanation:"Gustar uses indirect object pronouns: me/te/le/nos/os/les, not subject pronouns." },
  { id:"gap2-gu-2", themeId:"identities", type:"mcq", prompt:"[Gustar] 'A ella ___ encanta hablar de su cultura.' ¿Cuál es correcto?", options:["le","la","ella","se"], correctAnswer:"le", difficulty:"easy", points:10, explanation:"'A ella le encanta' — the indirect object pronoun 'le' is required even with 'a ella' stated." },
  { id:"gap2-gu-3", themeId:"identities", type:"mcq", prompt:"[Gustar - concordancia] 'A mis padres ___ (gustar) las tradiciones familiares.' ¿Cuál es correcto?", options:["les gustan","les gusta","le gustan","les gusto"], correctAnswer:"les gustan", difficulty:"medium", points:20, explanation:"The verb agrees with 'las tradiciones' (plural, the grammatical subject of gustar), not with 'mis padres'." },
  { id:"gap2-gu-4", themeId:"experiences", type:"mcq", prompt:"[Gustar - concordancia] 'A mí ___ (gustar) viajar en tren.' ¿Cuál es correcto?", options:["me gusta","me gustan","me gusto","yo gusto"], correctAnswer:"me gusta", difficulty:"easy", points:10, explanation:"With an infinitive as the subject (viajar), gustar stays singular: me gusta viajar." },
  { id:"gap2-gu-5", themeId:"experiences", type:"mcq", prompt:"[Verbos como gustar] '___ (interesar) mucho la historia de otros países.' Completa con el pronombre de 'a nosotros':", options:["nos interesa","nos interesan","os interesa","les interesa"], correctAnswer:"nos interesa", difficulty:"medium", points:20, explanation:"'Nos interesa' = it interests us. Agrees with the singular subject 'la historia'." },
  { id:"gap2-gu-6", themeId:"experiences", type:"mcq", prompt:"[Verbos como gustar] 'A los turistas ___ (faltar) tiempo para ver toda la ciudad.' ¿Cuál es correcto?", options:["les falta","les faltan","le falta","les falto"], correctAnswer:"les falta", difficulty:"medium", points:20, explanation:"Faltar works like gustar: 'les falta tiempo' = they are lacking time." },
  { id:"gap2-gu-7", themeId:"human-ingenuity", type:"mcq", prompt:"[Verbos como gustar] '___ (molestar) las notificaciones constantes del móvil.' Completa con el pronombre de 'a ti':", options:["te molestan","te molesta","le molestan","os molestan"], correctAnswer:"te molestan", difficulty:"medium", points:20, explanation:"'Te molestan' agrees with plural 'las notificaciones'." },
  { id:"gap2-gu-8", themeId:"human-ingenuity", type:"mcq", prompt:"[Verbos como gustar] 'A los programadores ___ (apasionar) crear cosas nuevas.' ¿Cuál es correcto?", options:["les apasiona","les apasionan","le apasiona","les apasionó"], correctAnswer:"les apasiona", difficulty:"hard", points:30, explanation:"Infinitive as subject (crear) → singular verb: les apasiona." },
  { id:"gap2-gu-9", themeId:"social-organization", type:"mcq", prompt:"[Verbos como gustar] '___ (importar) mucho los derechos humanos.' Completa con el pronombre de 'a mí':", options:["me importan","me importa","yo importo","se importan"], correctAnswer:"me importan", difficulty:"medium", points:20, explanation:"Agrees with plural 'los derechos humanos': me importan." },
  { id:"gap2-gu-10", themeId:"social-organization", type:"mcq", prompt:"[Verbos como gustar] 'Al gobierno ___ (quedar) pocas opciones para resolver la crisis.' ¿Cuál es correcto?", options:["le quedan","le queda","les quedan","lo queda"], correctAnswer:"le quedan", difficulty:"hard", points:30, explanation:"'Le quedan' agrees with plural 'pocas opciones'; 'al gobierno' is singular so the pronoun is 'le', not 'les'." },
  { id:"gap2-gu-11", themeId:"sharing-planet", type:"mcq", prompt:"[Verbos como gustar] 'A los científicos ___ (preocupar) el aumento de la temperatura global.' ¿Cuál es correcto?", options:["les preocupa","les preocupan","le preocupa","les preocupó"], correctAnswer:"les preocupa", difficulty:"medium", points:20, explanation:"Singular subject 'el aumento' → 'les preocupa'." },
  { id:"gap2-gu-12", themeId:"sharing-planet", type:"mcq", prompt:"[Verbos como gustar] 'A mucha gente ___ (doler) ver los océanos tan contaminados.' ¿Cuál es correcto?", options:["le duele","le duelen","les duele","le dolió"], correctAnswer:"le duele", difficulty:"hard", points:30, explanation:"Infinitive phrase as subject ('ver los océanos...') → singular: le duele." },
  { id:"gap2-gu-13", themeId:"identities", type:"short", prompt:"[Gustar] Traduce: 'We love our traditions.' (usar 'encantar')", correctAnswer:"nos encantan nuestras tradiciones", difficulty:"medium", points:20 },
  { id:"gap2-gu-14", themeId:"experiences", type:"short", prompt:"[Gustar] Traduce: 'They are interested in new cultures.' (usar 'interesar')", correctAnswer:"les interesan las nuevas culturas", difficulty:"medium", points:20 },
  { id:"gap2-gu-15", themeId:"human-ingenuity", type:"short", prompt:"[Gustar] Traduce: 'I love this new app.' (usar 'encantar')", correctAnswer:"me encanta esta aplicación nueva", difficulty:"medium", points:20 },
  { id:"gap2-gu-16", themeId:"social-organization", type:"mcq", prompt:"[Gustar - énfasis/aclaración] '¿Cuál es la función de 'a ella' en 'A ella le gusta leer'?", options:["Aclarar o dar énfasis a quién se refiere 'le'","Es el sujeto de la oración","Es el objeto directo","Es innecesario y se puede omitir siempre"], correctAnswer:"Aclarar o dar énfasis a quién se refiere 'le'", difficulty:"hard", points:30, explanation:"'A ella/él/usted' clarifies an ambiguous 'le', since 'le' alone could refer to him, her, or usted." },
  { id:"gap2-gu-17", themeId:"sharing-planet", type:"mcq", prompt:"[Gustar - orden de palabras] ¿Cuál es el orden correcto en español?", options:["Me gustan los animales salvajes.","Gustan me los animales salvajes.","Los animales salvajes gustan me.","Me los animales salvajes gustan."], correctAnswer:"Me gustan los animales salvajes.", difficulty:"medium", points:20, explanation:"Standard order: (a + person) + pronoun + gustar + subject." },
  { id:"gap2-gu-18", themeId:"identities", type:"mcq", prompt:"[Verbos como gustar] '¿Qué te pasa? Pareces triste.' '___ duele la cabeza.' ¿Cuál es correcto?", options:["Me","Yo","Mi","Se"], correctAnswer:"Me", difficulty:"easy", points:10, explanation:"'Me duele la cabeza' = my head hurts (literally: the head hurts to me)." },
  { id:"gap2-gu-19", themeId:"experiences", type:"mcq", prompt:"[Verbos como gustar] 'A nosotros no ___ (gustar) nada la comida picante.' ¿Cuál es correcto?", options:["nos gusta","nos gustan","os gusta","les gusta"], correctAnswer:"nos gusta", difficulty:"easy", points:10, explanation:"Singular subject 'la comida' → nos gusta." },
  { id:"gap2-gu-20", themeId:"human-ingenuity", type:"mcq", prompt:"[Verbos como gustar] 'A vosotros ___ (fascinar) la robótica.' ¿Cuál es correcto?", options:["os fascina","os fascinan","les fascina","nos fascina"], correctAnswer:"os fascina", difficulty:"medium", points:20, explanation:"Vosotros → object pronoun 'os'; singular subject 'la robótica' → fascina." },
  { id:"gap2-gu-21", themeId:"social-organization", type:"short", prompt:"[Gustar] Completa: 'A los votantes jóvenes ___ (importar) mucho el cambio climático.'", correctAnswer:"les importa", difficulty:"medium", points:20 },
  { id:"gap2-gu-22", themeId:"sharing-planet", type:"short", prompt:"[Gustar] Completa: 'A mí ___ (encantar) las montañas y los bosques.'", correctAnswer:"me encantan", difficulty:"medium", points:20 },
  { id:"gap2-gu-23", themeId:"identities", type:"mcq", prompt:"[Verbos como gustar] ¿Cuál de estas oraciones es INCORRECTA?", options:["Me gusto mucho bailar.","Me gusta mucho bailar.","Nos gusta mucho bailar.","Les gusta mucho bailar."], correctAnswer:"Me gusto mucho bailar.", difficulty:"hard", points:30, explanation:"'Me gusto' would mean 'I like myself' (reflexive gustar) — wrong here. Should be 'me gusta bailar'." },
  { id:"gap2-gu-24", themeId:"experiences", type:"mcq", prompt:"[Verbos como gustar] '¿Te gustaría (a ti) visitar Perú algún día?' Esta pregunta usa gustar en:", options:["Condicional","Presente","Pretérito","Futuro"], correctAnswer:"Condicional", difficulty:"medium", points:20, explanation:"'Gustaría' is the conditional form, used for polite suggestions/hypotheticals: would you like to..." },
  { id:"gap2-gu-25", themeId:"human-ingenuity", type:"mcq", prompt:"[Verbos como gustar] '¿Cuál de estas es la traducción correcta de 'I'm missing three euros'?", options:["Me faltan tres euros.","Me falta tres euros.","Yo falto tres euros.","Me faltando tres euros."], correctAnswer:"Me faltan tres euros.", difficulty:"medium", points:20, explanation:"'Faltan' agrees with plural 'tres euros'." },

  // =========================================================================
  // 3. DIRECT/INDIRECT OBJECT PRONOUNS (~25 questions)
  // =========================================================================

  { id:"gap2-op-1", themeId:"identities", type:"mcq", prompt:"[Pronombres OD] '¿Ves la película? Sí, ___ veo esta noche.' ¿Cuál es correcto?", options:["la","le","lo","les"], correctAnswer:"la", difficulty:"easy", points:10, explanation:"'La película' is feminine singular → direct object pronoun 'la'." },
  { id:"gap2-op-2", themeId:"identities", type:"mcq", prompt:"[Pronombres OD] '¿Compraste los libros? Sí, ya ___ compré.' ¿Cuál es correcto?", options:["los","las","le","les"], correctAnswer:"los", difficulty:"easy", points:10, explanation:"'Los libros' is masculine plural → direct object pronoun 'los'." },
  { id:"gap2-op-3", themeId:"identities", type:"mcq", prompt:"[Pronombres OI] '___ escribí una carta a mi abuela.' ¿Cuál es correcto?", options:["Le","La","Lo","Les"], correctAnswer:"Le", difficulty:"easy", points:10, explanation:"Indirect object pronoun for singular 'a mi abuela' = le (the letter — direct object — is unstated here, just the recipient)." },
  { id:"gap2-op-4", themeId:"experiences", type:"mcq", prompt:"[Pronombres combinados] '¿Me prestas tu cámara? Sí, ___ presto ahora mismo.' ¿Cuál es correcto?", options:["te la","te lo","la te","te le"], correctAnswer:"te la", difficulty:"hard", points:30, explanation:"Indirect object before direct: te (to you) + la (the camera, fem.) = te la presto." },
  { id:"gap2-op-5", themeId:"experiences", type:"mcq", prompt:"[Pronombres combinados] '¿Le diste el pasaporte al guía? Sí, ___ di ayer.' ¿Cuál es correcto?", options:["se lo","le lo","lo se","se la"], correctAnswer:"se lo", difficulty:"hard", points:30, explanation:"'Le' becomes 'se' before another third-person pronoun (lo/la/los/las): se lo di." },
  { id:"gap2-op-6", themeId:"experiences", type:"mcq", prompt:"[Pronombres combinados] 'Mándame las fotos del viaje.' → '___ manda, por favor.' ¿Cuál es correcto?", options:["Mándamelas","Mándalasme","Melás manda","Me las manda"], correctAnswer:"Mándamelas", difficulty:"hard", points:30, explanation:"With affirmative imperative, pronouns attach to the verb end, in order IO + DO: mánda + me + las." },
  { id:"gap2-op-7", themeId:"human-ingenuity", type:"mcq", prompt:"[Pronombres OD] 'No entiendo este programa. ¿___ puedes explicar?' ¿Cuál es correcto?", options:["me lo","me la","me le","yo lo"], correctAnswer:"me lo", difficulty:"medium", points:20, explanation:"'Me' (to me) + 'lo' (el programa, masc.) = me lo puedes explicar." },
  { id:"gap2-op-8", themeId:"human-ingenuity", type:"mcq", prompt:"[Colocación de pronombres] '¿Dónde está tu portátil?' ¿Cuál de estas oraciones es correcta?", options:["Lo estoy usando en la biblioteca.","Estoy lo usando en la biblioteca.","Estoy usandolo en la biblioteca (sin tilde).","Uso lo en la biblioteca."], correctAnswer:"Lo estoy usando en la biblioteca.", difficulty:"medium", points:20, explanation:"With verb + gerund, the pronoun can go before the conjugated verb OR attach to the gerund (usándolo, with an accent) — never mid-phrase unattached." },
  { id:"gap2-op-9", themeId:"social-organization", type:"mcq", prompt:"[Pronombres OD] 'El gobierno anunció las nuevas leyes.' → 'El gobierno ___ anunció.' ¿Cuál es correcto?", options:["las","los","le","les"], correctAnswer:"las", difficulty:"easy", points:10, explanation:"'Las leyes' is feminine plural → las." },
  { id:"gap2-op-10", themeId:"social-organization", type:"mcq", prompt:"[Pronombres OI] 'El alcalde ___ explicó el proyecto a los vecinos.' ¿Cuál es correcto?", options:["les","los","las","le"], correctAnswer:"les", difficulty:"medium", points:20, explanation:"'A los vecinos' is plural → indirect object pronoun 'les'." },
  { id:"gap2-op-11", themeId:"sharing-planet", type:"mcq", prompt:"[Pronombres OD] '¿Reciclas las botellas? Sí, siempre ___ reciclo.' ¿Cuál es correcto?", options:["las","los","le","les"], correctAnswer:"las", difficulty:"easy", points:10 },
  { id:"gap2-op-12", themeId:"sharing-planet", type:"mcq", prompt:"[Pronombres combinados] '¿Nos vas a explicar el problema? Sí, ___ voy a explicar mañana.' ¿Cuál es correcto?", options:["os lo","os la","lo os","les lo"], correctAnswer:"os lo", difficulty:"hard", points:30, explanation:"'Os' (to you all) + 'lo' (el problema, masc.) = os lo voy a explicar." },
  { id:"gap2-op-13", themeId:"identities", type:"short", prompt:"[Pronombres OD] Reemplaza el objeto directo: 'Escribo la carta.' → 'La ___.'", correctAnswer:"escribo", difficulty:"medium", points:20 },
  { id:"gap2-op-14", themeId:"experiences", type:"short", prompt:"[Pronombres] Traduce: 'I gave it to her.' (el regalo = it, direct object masculino)", correctAnswer:"se lo di", difficulty:"hard", points:30 },
  { id:"gap2-op-15", themeId:"human-ingenuity", type:"mcq", prompt:"[Pronombre neutro 'lo'] '¿Sabías que el wifi no funciona? Sí, ya ___ sabía.' ¿Cuál es correcto?", options:["lo","la","le","los"], correctAnswer:"lo", difficulty:"hard", points:30, explanation:"'Lo' as a neuter pronoun replaces an entire idea/clause ('que el wifi no funciona'), not a specific noun." },
  { id:"gap2-op-16", themeId:"social-organization", type:"mcq", prompt:"[Pronombres OI] '¿Qué le vas a decir al comité?' ¿Qué representa 'le' aquí?", options:["Objeto indirecto: al comité","Objeto directo","Sujeto de la oración","Pronombre reflexivo"], correctAnswer:"Objeto indirecto: al comité", difficulty:"medium", points:20 },
  { id:"gap2-op-17", themeId:"sharing-planet", type:"mcq", prompt:"[Colocación con infinitivo] ¿Cuál de estas oraciones es correcta?", options:["Voy a reciclarlas. / Las voy a reciclar.","Voy la a reciclar.","Voy a las reciclar.","Las a voy reciclar."], correctAnswer:"Voy a reciclarlas. / Las voy a reciclar.", difficulty:"medium", points:20, explanation:"With a conjugated verb + infinitive, the pronoun can attach to the infinitive OR go before the conjugated verb — both are correct." },
  { id:"gap2-op-18", themeId:"identities", type:"mcq", prompt:"[Pronombres OD] 'Vi a mis primos en la fiesta.' → 'Vi ___ en la fiesta.'", options:["los","les","las","le"], correctAnswer:"los", difficulty:"medium", points:20, explanation:"'A mis primos' (people, masc. plural) as direct object → los." },
  { id:"gap2-op-19", themeId:"experiences", type:"mcq", prompt:"[Pronombres combinados] '¿Te devolvió el dinero? Sí, ___ devolvió ayer.' ¿Cuál es correcto?", options:["me lo","te lo","se me","me se"], correctAnswer:"me lo", difficulty:"hard", points:30, explanation:"The speaker is 'me' here (te devolvió = he returned to you, but the answer is from the speaker's own perspective: me lo devolvió = he returned it to me)." },
  { id:"gap2-op-20", themeId:"human-ingenuity", type:"short", prompt:"[Pronombres] Traduce: 'Show it to me.' (usar 'enseñar', imperativo tú, objeto masculino)", correctAnswer:"enséñamelo", difficulty:"hard", points:30 },
  { id:"gap2-op-21", themeId:"social-organization", type:"mcq", prompt:"[Objeto directo personal 'a'] '¿Cuál de estas oraciones usa correctamente la 'a personal'?", options:["Vi a mi vecino en el mercado.","Vi mi vecino en el mercado.","Vi a la mesa en la cocina.","A vi mi vecino."], correctAnswer:"Vi a mi vecino en el mercado.", difficulty:"medium", points:20, explanation:"The personal 'a' is required before a direct object that is a specific person." },
  { id:"gap2-op-22", themeId:"sharing-planet", type:"mcq", prompt:"[Pronombres OD] '¿Conoces esta especie de ave? No, no ___ conozco.' ¿Cuál es correcto?", options:["la","le","lo","les"], correctAnswer:"la", difficulty:"easy", points:10 },
  { id:"gap2-op-23", themeId:"identities", type:"mcq", prompt:"[Pronombres OI] 'Mi madre siempre ___ da buenos consejos (a mí).' ¿Cuál es correcto?", options:["me","mi","yo","se"], correctAnswer:"me", difficulty:"easy", points:10 },
  { id:"gap2-op-24", themeId:"experiences", type:"mcq", prompt:"[Colocación con imperativo negativo] '¿Le doy el mensaje?' 'No, no ___ des todavía.' ¿Cuál es correcto?", options:["se lo","dáselo","se le","lo se"], correctAnswer:"se lo", difficulty:"hard", points:30, explanation:"With NEGATIVE imperative, pronouns go BEFORE the verb (not attached): no se lo des." },
  { id:"gap2-op-25", themeId:"human-ingenuity", type:"mcq", prompt:"[Pronombres] '¿Cuál es la diferencia entre 'dáselo' y 'no se lo des'?", options:["Afirmativo (pronombre pegado) vs. negativo (pronombre antes del verbo)","No hay ninguna diferencia","Uno es formal y otro informal","Uno es singular y otro plural"], correctAnswer:"Afirmativo (pronombre pegado) vs. negativo (pronombre antes del verbo)", difficulty:"hard", points:30 },

  // =========================================================================
  // 4. REFLEXIVE VERBS (~20 questions)
  // =========================================================================

  { id:"gap2-rf-1", themeId:"identities", type:"mcq", prompt:"[Verbos reflexivos] 'Todos los días yo ___ (levantarse) a las siete.' ¿Cuál es correcto?", options:["me levanto","levanto","se levanta","te levantas"], correctAnswer:"me levanto", difficulty:"easy", points:10, explanation:"Reflexive verbs need a pronoun matching the subject: yo → me." },
  { id:"gap2-rf-2", themeId:"identities", type:"mcq", prompt:"[Verbos reflexivos] 'Mi hermano ___ (sentirse) orgulloso de sus raíces.' ¿Cuál es correcto?", options:["se siente","siente","me siento","te sientes"], correctAnswer:"se siente", difficulty:"easy", points:10 },
  { id:"gap2-rf-3", themeId:"identities", type:"mcq", prompt:"[Reflexivo vs no reflexivo] ¿Cuál es la diferencia entre 'lavar' y 'lavarse'?", options:["'Lavarse' implica que el sujeto realiza la acción sobre sí mismo","No hay diferencia de significado","'Lavarse' es más formal","'Lavar' solo se usa con objetos"], correctAnswer:"'Lavarse' implica que el sujeto realiza la acción sobre sí mismo", difficulty:"medium", points:20, explanation:"'Lavo el coche' (I wash the car) vs 'Me lavo' (I wash myself) — the reflexive pronoun shows the action reflects back on the subject." },
  { id:"gap2-rf-4", themeId:"experiences", type:"mcq", prompt:"[Verbos reflexivos] 'Nosotros ___ (quejarse) del mal tiempo durante el viaje.' ¿Cuál es correcto?", options:["nos quejamos","quejamos","se quejan","os quejáis"], correctAnswer:"nos quejamos", difficulty:"medium", points:20 },
  { id:"gap2-rf-5", themeId:"experiences", type:"mcq", prompt:"[Verbos reflexivos] '¿A qué hora ___ (acostarse) tú anoche?' ¿Cuál es correcto?", options:["te acostaste","acostaste","se acostó","me acosté"], correctAnswer:"te acostaste", difficulty:"medium", points:20 },
  { id:"gap2-rf-6", themeId:"experiences", type:"mcq", prompt:"[Verbos reflexivos] 'Los viajeros ___ (perderse) en el centro histórico.' ¿Cuál es correcto?", options:["se perdieron","perdieron","se perdió","nos perdimos"], correctAnswer:"se perdieron", difficulty:"medium", points:20 },
  { id:"gap2-rf-7", themeId:"human-ingenuity", type:"mcq", prompt:"[Verbos reflexivos] 'El sistema ___ (actualizarse) automáticamente cada noche.' ¿Cuál es correcto?", options:["se actualiza","actualiza","me actualizo","actualizan"], correctAnswer:"se actualiza", difficulty:"medium", points:20 },
  { id:"gap2-rf-8", themeId:"human-ingenuity", type:"mcq", prompt:"[Verbos reflexivos] 'Los estudiantes ___ (conectarse) a internet para hacer la tarea.' ¿Cuál es correcto?", options:["se conectan","conectan","se conecta","nos conectamos"], correctAnswer:"se conectan", difficulty:"easy", points:10 },
  { id:"gap2-rf-9", themeId:"social-organization", type:"mcq", prompt:"[Verbos reflexivos] 'Los ciudadanos ___ (organizarse) para protestar pacíficamente.' ¿Cuál es correcto?", options:["se organizaron","organizaron","se organizó","nos organizamos"], correctAnswer:"se organizaron", difficulty:"medium", points:20 },
  { id:"gap2-rf-10", themeId:"social-organization", type:"mcq", prompt:"[Reflexivo recíproco] 'Los dos candidatos ___ (respetarse) a pesar de sus diferencias.' ¿Cuál es correcto?", options:["se respetan","respetan","se respeta","os respetáis"], correctAnswer:"se respetan", difficulty:"hard", points:30, explanation:"Reciprocal 'se' = 'each other': se respetan = they respect each other." },
  { id:"gap2-rf-11", themeId:"sharing-planet", type:"mcq", prompt:"[Verbos reflexivos] 'La situación ___ (empeorarse) cada año por el calentamiento global.' ¿Cuál es correcto?", options:["se empeora","empeora","empeoran","nos empeoramos"], correctAnswer:"se empeora", difficulty:"medium", points:20 },
  { id:"gap2-rf-12", themeId:"sharing-planet", type:"mcq", prompt:"[Verbos reflexivos] 'Nosotros ___ (comprometerse) a reducir nuestro consumo de plástico.' ¿Cuál es correcto?", options:["nos comprometemos","comprometemos","se comprometen","os comprometéis"], correctAnswer:"nos comprometemos", difficulty:"medium", points:20 },
  { id:"gap2-rf-13", themeId:"identities", type:"short", prompt:"[Verbos reflexivos] Completa: '¿Cómo ___ (llamarse) tu mejor amigo?'", correctAnswer:"se llama", difficulty:"easy", points:10 },
  { id:"gap2-rf-14", themeId:"experiences", type:"short", prompt:"[Verbos reflexivos] Completa: 'Nosotros ___ (divertirse) mucho en el festival.'", correctAnswer:"nos divertimos", difficulty:"medium", points:20 },
  { id:"gap2-rf-15", themeId:"human-ingenuity", type:"short", prompt:"[Verbos reflexivos] Completa: 'Los científicos ___ (dedicarse) a investigar nuevas vacunas.'", correctAnswer:"se dedican", difficulty:"medium", points:20 },
  { id:"gap2-rf-16", themeId:"social-organization", type:"mcq", prompt:"[Colocación reflexiva] '¿Cuál es la posición correcta del pronombre reflexivo con el gerundio?", options:["Levantándose / Se está levantando (ambas correctas)","Solo se puede decir 'levantándose'","Solo se puede decir 'se levantando'","El pronombre nunca va con el gerundio"], correctAnswer:"Levantándose / Se está levantando (ambas correctas)", difficulty:"hard", points:30 },
  { id:"gap2-rf-17", themeId:"sharing-planet", type:"mcq", prompt:"[Verbos reflexivos - imperativo] '¡___ (preocuparse, vosotros) por el planeta!' ¿Cuál es correcto?", options:["Preocupaos","Preocuparos","Os preocupad","Preocupadse"], correctAnswer:"Preocupaos", difficulty:"hard", points:30, explanation:"Vosotros affirmative imperative + reflexive 'os': drop the final -d before attaching 'os' (except with 'irse' → idos): preocupad + os → preocupaos." },
  { id:"gap2-rf-18", themeId:"identities", type:"mcq", prompt:"[Verbos reflexivos] '¿Cuál de estos verbos NO es reflexivo por naturaleza?'", options:["comer","levantarse","ducharse","quejarse"], correctAnswer:"comer", difficulty:"easy", points:10, explanation:"'Comer' is not inherently reflexive (though 'comerse algo' exists as an intensifier); the other three are inherently or commonly reflexive." },
  { id:"gap2-rf-19", themeId:"experiences", type:"mcq", prompt:"[Verbos reflexivos] 'Yo ___ (irse) del hotel muy temprano.' ¿Cuál es correcto?", options:["me fui","fui","se fue","nos fuimos"], correctAnswer:"me fui", difficulty:"medium", points:20 },
  { id:"gap2-rf-20", themeId:"human-ingenuity", type:"mcq", prompt:"[Verbos reflexivos] 'La aplicación ___ (volverse) muy popular entre los jóvenes.' ¿Cuál es correcto?", options:["se volvió","volvió","se volvieron","nos volvimos"], correctAnswer:"se volvió", difficulty:"medium", points:20, explanation:"'Volverse' = to become (sudden/involuntary change)." },

  // =========================================================================
  // 5. NEGATION (~20 questions)
  // =========================================================================

  { id:"gap2-neg-1", themeId:"identities", type:"mcq", prompt:"[Negación] 'No conozco a ___ en esta ciudad todavía.' ¿Cuál es correcto?", options:["nadie","nada","ninguno","tampoco"], correctAnswer:"nadie", difficulty:"easy", points:10, explanation:"'Nadie' = nobody (for people)." },
  { id:"gap2-neg-2", themeId:"identities", type:"mcq", prompt:"[Negación] 'No entiendo ___ de lo que dice ese formulario.' ¿Cuál es correcto?", options:["nada","nadie","ninguno","tampoco"], correctAnswer:"nada", difficulty:"easy", points:10, explanation:"'Nada' = nothing (for things/concepts)." },
  { id:"gap2-neg-3", themeId:"experiences", type:"mcq", prompt:"[Negación] 'A mí no me gustó el hotel, y a mi hermano ___.' ¿Cuál es correcto?", options:["tampoco","también","nada","nunca"], correctAnswer:"tampoco", difficulty:"medium", points:20, explanation:"'Tampoco' = neither/not...either, echoing a previous negative statement." },
  { id:"gap2-neg-4", themeId:"experiences", type:"mcq", prompt:"[Negación] 'No he viajado ___ a Sudamérica.' ¿Cuál es correcto?", options:["nunca","siempre","también","algo"], correctAnswer:"nunca", difficulty:"easy", points:10, explanation:"'No... nunca' = never (double negative construction, standard in Spanish)." },
  { id:"gap2-neg-5", themeId:"human-ingenuity", type:"mcq", prompt:"[Negación] '___ los estudiantes ___ los profesores entendían el nuevo software al principio.' ¿Cuál es correcto?", options:["Ni / ni","No / no","Nunca / nunca","Tampoco / tampoco"], correctAnswer:"Ni / ni", difficulty:"medium", points:20, explanation:"'Ni... ni' = neither... nor." },
  { id:"gap2-neg-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Negación] 'De todas las apps que probé, ___ funcionó bien.' ¿Cuál es correcto?", options:["ninguna","nada","nadie","tampoco"], correctAnswer:"ninguna", difficulty:"medium", points:20, explanation:"'Ninguna' agrees in gender with 'apps' (fem.) and means 'none/not a single one'." },
  { id:"gap2-neg-7", themeId:"social-organization", type:"mcq", prompt:"[Negación] '___ ciudadano debería sufrir discriminación.' ¿Cuál es correcto?", options:["Ningún","Ninguno","Nadie","Nada"], correctAnswer:"Ningún", difficulty:"hard", points:30, explanation:"'Ninguno' shortens to 'ningún' before a masculine singular noun (like 'uno' → 'un')." },
  { id:"gap2-neg-8", themeId:"social-organization", type:"mcq", prompt:"[Doble negación - posición] '¿Cuál es el orden correcto cuando la palabra negativa va DESPUÉS del verbo?'", options:["No + verbo + palabra negativa (No vi a nadie.)","Palabra negativa + verbo (Nadie no vi.)","Verbo + no + palabra negativa","Solo se puede poner antes del verbo"], correctAnswer:"No + verbo + palabra negativa (No vi a nadie.)", difficulty:"medium", points:20 },
  { id:"gap2-neg-9", themeId:"sharing-planet", type:"mcq", prompt:"[Negación] 'No queda ___ tiempo para revertir el daño ambiental.' ¿Cuál es correcto?", options:["mucho","nada","nadie","ninguno"], correctAnswer:"mucho", difficulty:"medium", points:20, explanation:"'No queda mucho tiempo' = there isn't much time left — 'mucho' works with 'no' the same way 'much' works with 'not' in English." },
  { id:"gap2-neg-10", themeId:"sharing-planet", type:"mcq", prompt:"[Negación] 'No hemos visto ___ especie en peligro durante la excursión.' ¿Cuál es correcto?", options:["ninguna","nada","nadie","tampoco"], correctAnswer:"ninguna", difficulty:"medium", points:20, explanation:"'Ninguna especie' = not a single species (fem. agreement)." },
  { id:"gap2-neg-11", themeId:"identities", type:"short", prompt:"[Negación] Traduce: 'Nobody understands me.'", correctAnswer:"nadie me entiende", difficulty:"medium", points:20 },
  { id:"gap2-neg-12", themeId:"experiences", type:"short", prompt:"[Negación] Traduce: 'I have never been to Mexico.'", correctAnswer:"nunca he estado en méxico", difficulty:"medium", points:20 },
  { id:"gap2-neg-13", themeId:"human-ingenuity", type:"short", prompt:"[Negación] Traduce: 'Neither the app nor the website works.'", correctAnswer:"ni la aplicación ni la página web funcionan", difficulty:"hard", points:30 },
  { id:"gap2-neg-14", themeId:"social-organization", type:"mcq", prompt:"[Negación - posición alternativa] '¿Cuál de estas es también correcta (poniendo la palabra negativa antes del verbo)?'", options:["Nunca he mentido.","Nunca no he mentido.","No nunca he mentido.","He nunca mentido."], correctAnswer:"Nunca he mentido.", difficulty:"medium", points:20, explanation:"When the negative word comes BEFORE the verb, 'no' is omitted: Nunca he mentido (not 'No nunca...')." },
  { id:"gap2-neg-15", themeId:"sharing-planet", type:"mcq", prompt:"[Negación] '¿Alguien recicla en tu barrio?' 'No, ___ recicla.' ¿Cuál es correcto?", options:["nadie","nada","ninguno","tampoco"], correctAnswer:"nadie", difficulty:"easy", points:10 },
  { id:"gap2-neg-16", themeId:"identities", type:"mcq", prompt:"[Negación] '¿Tienes algún problema con tu identidad cultural?' 'No, no tengo ___.' ¿Cuál es correcto?", options:["ninguno","ningún","nadie","nada de eso ninguna"], correctAnswer:"ninguno", difficulty:"hard", points:30, explanation:"'Ninguno' (not shortened) is used when it stands alone, replacing the noun ('problema') rather than preceding it." },
  { id:"gap2-neg-17", themeId:"experiences", type:"mcq", prompt:"[Negación] 'Todavía no ___ decidido a dónde viajar el próximo verano.' ¿Cuál es correcto?", options:["he","soy","estoy","tengo"], correctAnswer:"he", difficulty:"medium", points:20, explanation:"'Todavía no he decidido' = I still haven't decided (present perfect with 'todavía no')." },
  { id:"gap2-neg-18", themeId:"human-ingenuity", type:"mcq", prompt:"[Negación] '¿Cuál es el equivalente de 'not even' en español?'", options:["ni siquiera","ni nunca","tampoco nada","ni nada"], correctAnswer:"ni siquiera", difficulty:"hard", points:30, explanation:"'Ni siquiera' = not even: 'Ni siquiera sabía usar el ratón.'" },
  { id:"gap2-neg-19", themeId:"social-organization", type:"mcq", prompt:"[Negación] 'El proyecto no beneficia a nadie ___ perjudica a la comunidad.' ¿Cuál es correcto?", options:["ni","no","nunca","tampoco"], correctAnswer:"ni", difficulty:"hard", points:30, explanation:"'Ni' continues a negative list without needing a second 'no': no beneficia... ni perjudica." },
  { id:"gap2-neg-20", themeId:"sharing-planet", type:"mcq", prompt:"[Negación] '¿Cuál es la traducción correcta de 'There's nothing we can do'?'", options:["No hay nada que podamos hacer.","No hay algo que podamos hacer.","Hay nada que podamos hacer.","No hay nada que podemos hacer."], correctAnswer:"No hay nada que podamos hacer.", difficulty:"hard", points:30, explanation:"'Nada que' triggers the subjunctive (podamos), since it describes a hypothetical/nonexistent thing." },

  // =========================================================================
  // 6. COMPARATIVES & SUPERLATIVES (~20 questions)
  // =========================================================================

  { id:"gap2-comp-1", themeId:"identities", type:"mcq", prompt:"[Comparativo] 'Mi hermano es ___ alto ___ yo.' ¿Cuál es correcto?", options:["más / que","más / como","tan / que","menos / de"], correctAnswer:"más / que", difficulty:"easy", points:10, explanation:"Comparative of superiority: más + adjective + que." },
  { id:"gap2-comp-2", themeId:"identities", type:"mcq", prompt:"[Comparativo de igualdad] 'Yo soy ___ bilingüe ___ mi prima.' ¿Cuál es correcto?", options:["tan / como","más / que","menos / de","tanto / que"], correctAnswer:"tan / como", difficulty:"medium", points:20, explanation:"Comparative of equality with adjectives: tan + adjective + como." },
  { id:"gap2-comp-3", themeId:"experiences", type:"mcq", prompt:"[Comparativo] 'Este viaje fue ___ caro ___ el anterior.' ¿Cuál es correcto?", options:["menos / que","menos / como","tan / de","más / de"], correctAnswer:"menos / que", difficulty:"easy", points:10, explanation:"Comparative of inferiority: menos + adjective + que." },
  { id:"gap2-comp-4", themeId:"experiences", type:"mcq", prompt:"[Comparativo con sustantivo] 'Tengo ___ fotos ___ tú de ese viaje.' ¿Cuál es correcto?", options:["tantas / como","tan / como","tantas / que","tan / que"], correctAnswer:"tantas / como", difficulty:"hard", points:30, explanation:"With nouns, equality uses tanto/a/os/as (agreeing) + noun + como, not 'tan'." },
  { id:"gap2-comp-5", themeId:"human-ingenuity", type:"mcq", prompt:"[Superlativo] 'Este es ___ invento ___ importante del siglo.' ¿Cuál es correcto?", options:["el / más","más / el","el / tan","un / más"], correctAnswer:"el / más", difficulty:"medium", points:20, explanation:"Superlative: el/la/los/las + noun + más + adjective." },
  { id:"gap2-comp-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Comparativo irregular] 'Esta actualización es ___ que la anterior.' (mejor/bueno) ¿Cuál es correcto?", options:["mejor","más buena","más bien","más buen"], correctAnswer:"mejor", difficulty:"medium", points:20, explanation:"'Bueno' has an irregular comparative: mejor (better), not 'más bueno'." },
  { id:"gap2-comp-7", themeId:"human-ingenuity", type:"mcq", prompt:"[Comparativo irregular] 'La conexión de hoy es ___ que la de ayer.' (peor/malo) ¿Cuál es correcto?", options:["peor","más mala","más mal","tan malo"], correctAnswer:"peor", difficulty:"medium", points:20, explanation:"'Malo' has an irregular comparative: peor (worse)." },
  { id:"gap2-comp-8", themeId:"social-organization", type:"mcq", prompt:"[Comparativo irregular] 'Mi abuelo es ___ que yo.' (mayor/viejo) ¿Cuál es correcto?", options:["mayor","más viejo (también aceptable, pero menos formal)","más grande","tan viejo"], correctAnswer:"mayor", difficulty:"hard", points:30, explanation:"'Mayor' is the standard comparative for age (older) in formal/written Spanish." },
  { id:"gap2-comp-9", themeId:"social-organization", type:"mcq", prompt:"[Superlativo absoluto] 'La desigualdad en esa región es ___.' (muy + grave) ¿Cuál es correcto?", options:["gravísima","muy gravísima","más gravísima","grave muy"], correctAnswer:"gravísima", difficulty:"medium", points:20, explanation:"Absolute superlative: add -ísimo/a (never combine with 'muy')." },
  { id:"gap2-comp-10", themeId:"sharing-planet", type:"mcq", prompt:"[Comparativo con número] 'Hay ___ de mil especies en peligro de extinción.' ¿Cuál es correcto?", options:["más","más que","tanto","tan"], correctAnswer:"más", difficulty:"hard", points:30, explanation:"Before a number, use 'más de' (not 'más que'): más de mil." },
  { id:"gap2-comp-11", themeId:"sharing-planet", type:"mcq", prompt:"[Superlativo] 'El Amazonas es ___ selva tropical ___ grande del mundo.' ¿Cuál es correcto?", options:["la / más","el / más","la / tan","una / más"], correctAnswer:"la / más", difficulty:"medium", points:20, explanation:"'La selva' is feminine, so the superlative article agrees: la selva más grande." },
  { id:"gap2-comp-12", themeId:"identities", type:"short", prompt:"[Comparativo] Traduce: 'She is younger than her brother.' (usar 'menor')", correctAnswer:"ella es menor que su hermano", difficulty:"medium", points:20 },
  { id:"gap2-comp-13", themeId:"experiences", type:"short", prompt:"[Comparativo de igualdad] Traduce: 'This trip was as exciting as the last one.'", correctAnswer:"este viaje fue tan emocionante como el último", difficulty:"medium", points:20 },
  { id:"gap2-comp-14", themeId:"human-ingenuity", type:"short", prompt:"[Superlativo] Traduce: 'It's the most useful app I've ever used.'", correctAnswer:"es la aplicación más útil que he usado", difficulty:"hard", points:30 },
  { id:"gap2-comp-15", themeId:"social-organization", type:"mcq", prompt:"[Comparativo irregular] '¿Cuál es el comparativo irregular de 'pequeño' (referido a edad)?'", options:["menor","más pequeño","menos pequeño","peor"], correctAnswer:"menor", difficulty:"hard", points:30, explanation:"'Menor' = younger (age) — irregular comparative alongside 'más pequeño' (smaller, size)." },
  { id:"gap2-comp-16", themeId:"sharing-planet", type:"mcq", prompt:"[Comparativo] '¿Cuál de estas frases NO es correcta?'", options:["Es más mejor que antes.","Es mejor que antes.","Es peor que antes.","Es tan bueno como antes."], correctAnswer:"Es más mejor que antes.", difficulty:"medium", points:20, explanation:"'Mejor' is already comparative — never combine it with 'más' (no double comparative)." },
  { id:"gap2-comp-17", themeId:"identities", type:"mcq", prompt:"[Comparativo con verbos] 'Ella estudia ___ que yo.' ¿Cuál es correcto?", options:["más","más que","tan","tanto que"], correctAnswer:"más", difficulty:"medium", points:20, explanation:"With a verb, the comparative is simply más/menos + verb + que: estudia más que yo." },
  { id:"gap2-comp-18", themeId:"experiences", type:"mcq", prompt:"[Superlativo absoluto irregular] '¿Cuál es el superlativo absoluto de 'fácil'?'", options:["facilísimo","fácilísimo","muy facilísimo","facilisimo (sin tilde)"], correctAnswer:"facilísimo", difficulty:"hard", points:30, explanation:"Facilísimo — the stress shifts to the added -ísimo, and 'fácil' loses its own written accent." },
  { id:"gap2-comp-19", themeId:"human-ingenuity", type:"mcq", prompt:"[Comparativo] 'Cuantos ___ datos recopilemos, ___ preciso será el modelo.' ¿Cuál es correcto?", options:["más / más","más / tan","tantos / más","más / tantos"], correctAnswer:"más / más", difficulty:"hard", points:30, explanation:"'Cuanto más... más...' = the more... the more... (parallel comparative construction)." },
  { id:"gap2-comp-20", themeId:"social-organization", type:"mcq", prompt:"[Comparativo] '¿Cuál es la traducción de 'the fewer resources, the greater the inequality'?'", options:["Cuantos menos recursos, mayor la desigualdad.","Cuanto menos recursos, más grande desigualdad.","Menos recursos, más desigualdad, cuanto.","Cuantos menos recursos, más desigualdad tan grande."], correctAnswer:"Cuantos menos recursos, mayor la desigualdad.", difficulty:"hard", points:30 },

  // =========================================================================
  // 7. NUMBERS, DATES & TIME EXPRESSIONS (~25 questions)
  // =========================================================================

  { id:"gap2-num-1", themeId:"identities", type:"mcq", prompt:"[Expresiones de tiempo] '___ diez años que vivo en esta ciudad.' ¿Cuál es correcto?", options:["Hace","Desde","Hace que","Desde hace"], correctAnswer:"Hace", difficulty:"medium", points:20, explanation:"'Hace + time + que + present' = to have been doing something for X time." },
  { id:"gap2-num-2", themeId:"identities", type:"mcq", prompt:"[Expresiones de tiempo] 'Vivo en esta ciudad ___ diez años.' ¿Cuál es correcto?", options:["desde hace","hace que","desde que","hace"], correctAnswer:"desde hace", difficulty:"medium", points:20, explanation:"'Present + desde hace + time' = same meaning as 'hace + time + que + present', different word order." },
  { id:"gap2-num-3", themeId:"experiences", type:"mcq", prompt:"[Llevar + gerundio] '___ dos horas esperando el autobús.' ¿Cuál es correcto?", options:["Llevo","Tengo","Estoy","Hago"], correctAnswer:"Llevo", difficulty:"medium", points:20, explanation:"'Llevar + time + gerundio' = to have been doing something for X time." },
  { id:"gap2-num-4", themeId:"experiences", type:"mcq", prompt:"[Fechas] '¿Qué fecha es hoy?' '___ 3 de mayo.' ¿Cuál es correcto?", options:["Es el","Es la","Está el","Son el"], correctAnswer:"Es el", difficulty:"easy", points:10, explanation:"Dates use 'es el' + number + de + month (masculine article 'el', even though 'fecha' is feminine)." },
  { id:"gap2-num-5", themeId:"experiences", type:"mcq", prompt:"[Números ordinales] 'Vivo en el ___ piso.' (5th) ¿Cuál es correcto?", options:["quinto","cinco","cincoavo","quinta"], correctAnswer:"quinto", difficulty:"medium", points:20, explanation:"'Quinto' = fifth, agreeing with masculine 'piso'." },
  { id:"gap2-num-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Hora] 'La conferencia empieza ___ las nueve de la mañana.' ¿Cuál es correcto?", options:["a","en","por","de"], correctAnswer:"a", difficulty:"easy", points:10, explanation:"Clock time uses 'a las' for 'at' — a las nueve." },
  { id:"gap2-num-7", themeId:"human-ingenuity", type:"mcq", prompt:"[Expresiones de tiempo] '¿Cuánto tiempo ___ que no actualizas la aplicación?' ¿Cuál es correcto?", options:["hace","hay","tiene","lleva"], correctAnswer:"hace", difficulty:"medium", points:20, explanation:"'¿Cuánto tiempo hace que...?' = How long has it been since...?" },
  { id:"gap2-num-8", themeId:"human-ingenuity", type:"short", prompt:"[Números] Escribe en palabras: 1.500 (mil quinientos) usuarios nuevos.", correctAnswer:"mil quinientos", difficulty:"medium", points:20 },
  { id:"gap2-num-9", themeId:"social-organization", type:"mcq", prompt:"[Fechas - año] 'La ley se aprobó ___ 2015.' ¿Cuál es correcto?", options:["en","el","durante el","a"], correctAnswer:"en", difficulty:"easy", points:10, explanation:"Years use 'en': en 2015." },
  { id:"gap2-num-10", themeId:"social-organization", type:"mcq", prompt:"[Expresiones de tiempo] 'El proyecto ___ funcionando desde hace tres años.' ¿Cuál es correcto?", options:["lleva","tiene","hace","está"], correctAnswer:"lleva", difficulty:"hard", points:30, explanation:"'Llevar + gerundio' can also be used in third person: el proyecto lleva funcionando..." },
  { id:"gap2-num-11", themeId:"social-organization", type:"short", prompt:"[Números ordinales] Escribe el ordinal de 'primero' cuando va antes de un sustantivo masculino singular (forma apocopada): 'el ___ ministro'.", correctAnswer:"primer", difficulty:"hard", points:30 },
  { id:"gap2-num-12", themeId:"sharing-planet", type:"mcq", prompt:"[Porcentajes] 'El ___ por ciento de la energía es renovable.' ¿Cuál es correcto para expresar '40%'?", options:["cuarenta","cuarto","cuartenta","cuarenteno"], correctAnswer:"cuarenta", difficulty:"easy", points:10 },
  { id:"gap2-num-13", themeId:"sharing-planet", type:"mcq", prompt:"[Expresiones de tiempo] '___ hace mucho tiempo, esta zona era un bosque denso.' ¿Cuál es correcto?", options:["Hace","Desde","Llevaba","Tiene"], correctAnswer:"Hace", difficulty:"medium", points:20, explanation:"'Hace mucho tiempo' = a long time ago (used with past tense verbs, not present)." },
  { id:"gap2-num-14", themeId:"sharing-planet", type:"short", prompt:"[Fechas] Traduce: 'The conference is on June 5th.'", correctAnswer:"la conferencia es el 5 de junio", difficulty:"medium", points:20 },
  { id:"gap2-num-15", themeId:"identities", type:"mcq", prompt:"[Edad] '¿Cuántos años ___?' ¿Cuál es correcto?", options:["tienes","eres","estás","haces"], correctAnswer:"tienes", difficulty:"easy", points:10, explanation:"Age uses 'tener': tener X años, not 'ser' as in English." },
  { id:"gap2-num-16", themeId:"experiences", type:"mcq", prompt:"[Duración] 'El vuelo dura ___ ocho horas.' ¿Cuál es correcto?", options:["aproximadamente","aproximado","aproximada","aproximo"], correctAnswer:"aproximadamente", difficulty:"easy", points:10 },
  { id:"gap2-num-17", themeId:"human-ingenuity", type:"mcq", prompt:"[Expresiones de tiempo] '¿Desde cuándo usas ese programa?' '___ el año pasado.' ¿Cuál es correcto?", options:["Desde","Hace","Hace que","Llevo"], correctAnswer:"Desde", difficulty:"medium", points:20, explanation:"'Desde' + a specific starting point in time = since." },
  { id:"gap2-num-18", themeId:"social-organization", type:"mcq", prompt:"[Números - miles] '¿Cómo se escribe '2.000.000' en palabras?'", options:["dos millones","dos millón","dosmillones","dos mil miles"], correctAnswer:"dos millones", difficulty:"medium", points:20 },
  { id:"gap2-num-19", themeId:"sharing-planet", type:"mcq", prompt:"[Expresiones de tiempo] 'Para el año 2050, ___ agotado muchos recursos naturales si no cambiamos de hábitos.' ¿Cuál es correcto?", options:["habremos","hemos","habíamos","habríamos"], correctAnswer:"habremos", difficulty:"hard", points:30, explanation:"'Habremos agotado' = future perfect, describing a completed action by a future point." },
  { id:"gap2-num-20", themeId:"identities", type:"mcq", prompt:"[Fechas - día de la semana] 'Nací un ___ de octubre.' (Monday) ¿Cuál es correcto?", options:["lunes","Lunes (con mayúscula)","el lunes con acento","luness"], correctAnswer:"lunes", difficulty:"easy", points:10, explanation:"Days of the week are NOT capitalized in Spanish." },
  { id:"gap2-num-21", themeId:"experiences", type:"short", prompt:"[Llevar + gerundio] Traduce: 'We have been traveling for three weeks.'", correctAnswer:"llevamos tres semanas viajando", difficulty:"hard", points:30 },
  { id:"gap2-num-22", themeId:"human-ingenuity", type:"mcq", prompt:"[Expresiones de tiempo] '¿Cuál es la pregunta correcta para 'How long ago did you buy the phone?'?'", options:["¿Hace cuánto tiempo compraste el teléfono?","¿Cuánto hace compraste el teléfono?","¿Desde cuándo compraste el teléfono?","¿Cuánto tiempo compras el teléfono?"], correctAnswer:"¿Hace cuánto tiempo compraste el teléfono?", difficulty:"hard", points:30 },
  { id:"gap2-num-23", themeId:"social-organization", type:"mcq", prompt:"[Expresiones de tiempo - pasado] 'Hace dos años, ___ (aprobar) esa ley.' ¿Cuál es correcto?", options:["se aprobó","se aprueba","se ha aprobado","se apruebe"], correctAnswer:"se aprobó", difficulty:"medium", points:20, explanation:"'Hace + time' (without 'que') + preterite = X time ago, something happened." },
  { id:"gap2-num-24", themeId:"sharing-planet", type:"mcq", prompt:"[Números decimales] '¿Cómo se lee '3,5 grados' en español (usando coma decimal)?'", options:["tres coma cinco grados","tres punto cinco grados","tres cinco grados","tres y cinco grados"], correctAnswer:"tres coma cinco grados", difficulty:"hard", points:30, explanation:"Spanish uses a comma for decimals (and reads it as 'coma'), unlike English's decimal point." },
  { id:"gap2-num-25", themeId:"identities", type:"mcq", prompt:"[Siglos] 'Esta tradición viene del siglo ___.' (19th, escrito en números romanos) ¿Cuál es correcto?", options:["XIX","19","IXX","19º"], correctAnswer:"XIX", difficulty:"medium", points:20, explanation:"Centuries are conventionally written in Roman numerals in Spanish: siglo XIX." },

  // =========================================================================
  // 8. QUESTION WORDS: QUÉ vs CUÁL vs POR QUÉ (~20 questions)
  // =========================================================================

  { id:"gap2-qw-1", themeId:"identities", type:"mcq", prompt:"[Qué vs Cuál] '¿___ es tu nombre?' ¿Cuál es correcto?", options:["Cuál","Qué","Cómo","Cuáles"], correctAnswer:"Cuál", difficulty:"medium", points:20, explanation:"'¿Cuál es...?' is used before 'ser' when asking someone to select/identify from a set of possibilities (here: which name, among all possible names, is yours)." },
  { id:"gap2-qw-2", themeId:"identities", type:"mcq", prompt:"[Qué vs Cuál] '¿___ es la identidad cultural?' (pidiendo una definición) ¿Cuál es correcto?", options:["Qué","Cuál","Cuáles","Cómo"], correctAnswer:"Qué", difficulty:"hard", points:30, explanation:"'¿Qué es...?' asks for a DEFINITION (what is X, conceptually), while '¿Cuál es...?' asks to select among options." },
  { id:"gap2-qw-3", themeId:"experiences", type:"mcq", prompt:"[Qué vs Cuál] '¿___ país te gustó más de tu viaje?' ¿Cuál es correcto?", options:["Qué","Cuál","Cuáles","Quién"], correctAnswer:"Qué", difficulty:"hard", points:30, explanation:"Before a noun (país), Spanish uses 'qué', not 'cuál' — unlike English 'which country'." },
  { id:"gap2-qw-4", themeId:"experiences", type:"mcq", prompt:"[Qué vs Cuál] '¿___ de estos dos vuelos prefieres?' ¿Cuál es correcto?", options:["Cuál","Qué","Cuáles","Cuyo"], correctAnswer:"Cuál", difficulty:"medium", points:20, explanation:"'Cuál de estos' asks to choose among specific options." },
  { id:"gap2-qw-5", themeId:"human-ingenuity", type:"mcq", prompt:"[Por qué vs Porque] '¿___ dejaste de usar esa aplicación?' ¿Cuál es correcto?", options:["Por qué","Porque","Porqué","Por que"], correctAnswer:"Por qué", difficulty:"medium", points:20, explanation:"'Por qué' (two words, with accent) = why, used in questions." },
  { id:"gap2-qw-6", themeId:"human-ingenuity", type:"mcq", prompt:"[Por qué vs Porque] 'Dejé de usarla ___ era muy lenta.' ¿Cuál es correcto?", options:["porque","por qué","porqué","por que"], correctAnswer:"porque", difficulty:"medium", points:20, explanation:"'Porque' (one word, no accent) = because, used to give a reason." },
  { id:"gap2-qw-7", themeId:"human-ingenuity", type:"mcq", prompt:"[El porqué] 'Nadie entiende ___ de su decisión.' ¿Cuál es correcto?", options:["el porqué","porque","por qué","porqué de"], correctAnswer:"el porqué", difficulty:"hard", points:30, explanation:"'El porqué' (with article, one word) is a noun meaning 'the reason'." },
  { id:"gap2-qw-8", themeId:"social-organization", type:"mcq", prompt:"[Qué vs Cuál] '¿___ son las causas principales de la pobreza?' ¿Cuál es correcto?", options:["Cuáles","Cuál","Qué son","Quiénes"], correctAnswer:"Cuáles", difficulty:"medium", points:20, explanation:"Plural 'las causas' → cuáles (plural of cuál)." },
  { id:"gap2-qw-9", themeId:"social-organization", type:"mcq", prompt:"[Cómo vs Qué] '¿___ te llamas?' ¿Cuál es correcto?", options:["Cómo","Qué","Cuál","Cuánto"], correctAnswer:"Cómo", difficulty:"easy", points:10, explanation:"'¿Cómo te llamas?' (literally 'how do you call yourself') is the fixed idiom for asking someone's name." },
  { id:"gap2-qw-10", themeId:"sharing-planet", type:"mcq", prompt:"[Qué vs Cuál] '¿___ opinas sobre el cambio climático?' ¿Cuál es correcto?", options:["Qué","Cuál","Cuáles","Cuál es"], correctAnswer:"Qué", difficulty:"medium", points:20, explanation:"'¿Qué opinas?' = what do you think — 'qué' before a verb, asking about content/opinion." },
  { id:"gap2-qw-11", themeId:"sharing-planet", type:"mcq", prompt:"[Cuánto] '¿___ agua consume una ducha de diez minutos?' ¿Cuál es correcto?", options:["Cuánta","Cuánto","Cuántos","Cuál"], correctAnswer:"Cuánta", difficulty:"medium", points:20, explanation:"'Cuánta' agrees with feminine 'agua' (uses feminine agreement despite taking 'el agua' as its article)." },
  { id:"gap2-qw-12", themeId:"identities", type:"short", prompt:"[Qué vs Cuál] Completa: '¿___ es tu comida favorita?' (elegir entre las comidas posibles)", correctAnswer:"cuál", difficulty:"medium", points:20 },
  { id:"gap2-qw-13", themeId:"experiences", type:"short", prompt:"[Por qué vs Porque] Completa: 'No sé ___ perdimos el vuelo.' (indirecta, sigue funcionando como '¿por qué?')", correctAnswer:"por qué", difficulty:"hard", points:30, explanation:"Indirect questions ('no sé por qué...') still use 'por qué' with accent, since it's still a question at heart." },
  { id:"gap2-qw-14", themeId:"human-ingenuity", type:"mcq", prompt:"[Quién vs Qué] '¿___ inventó el primer ordenador personal?' ¿Cuál es correcto?", options:["Quién","Qué","Cuál","Cómo"], correctAnswer:"Quién", difficulty:"easy", points:10, explanation:"'Quién' asks about a person (who)." },
  { id:"gap2-qw-15", themeId:"social-organization", type:"mcq", prompt:"[Dónde vs Adónde] '¿___ vas de vacaciones este verano?' ¿Cuál es correcto?", options:["Adónde","Dónde","Donde","De dónde"], correctAnswer:"Adónde", difficulty:"hard", points:30, explanation:"'Adónde' = to where, used with verbs of motion/destination (ir, viajar). 'Dónde' asks about a static location." },
  { id:"gap2-qw-16", themeId:"sharing-planet", type:"mcq", prompt:"[Qué vs Cuál] '¿___ es la diferencia entre reciclar y reutilizar?' ¿Cuál es correcto?", options:["Cuál","Qué","Cuáles","Quién"], correctAnswer:"Cuál", difficulty:"hard", points:30, explanation:"'¿Cuál es la diferencia?' is a fixed, very common construction — 'cuál' before 'es' + noun, asking to identify/select." },
  { id:"gap2-qw-17", themeId:"identities", type:"mcq", prompt:"[Qué vs Cuál - regla general] ¿Cuál es la regla general para elegir entre 'qué' y 'cuál' antes de un sustantivo?", options:["Siempre se usa 'qué' antes de un sustantivo","Siempre se usa 'cuál' antes de un sustantivo","Depende del verbo, nunca del sustantivo","Son intercambiables siempre"], correctAnswer:"Siempre se usa 'qué' antes de un sustantivo", difficulty:"hard", points:30, explanation:"Before a noun, standard Spanish always uses 'qué' (qué libro, qué país), even where English would say 'which'." },
  { id:"gap2-qw-18", themeId:"experiences", type:"mcq", prompt:"[Cuánto tiempo] '¿___ dura el vuelo a Buenos Aires?' ¿Cuál es correcto?", options:["Cuánto","Cuánta","Cuántos","Cuál"], correctAnswer:"Cuánto", difficulty:"easy", points:10 },
  { id:"gap2-qw-19", themeId:"human-ingenuity", type:"mcq", prompt:"[Por qué vs Para qué] '¿___ sirve esta aplicación?' ¿Cuál es correcto?", options:["Para qué","Por qué","Porque","Cuál"], correctAnswer:"Para qué", difficulty:"hard", points:30, explanation:"'¿Para qué sirve?' asks about PURPOSE/function (what is it for), distinct from '¿por qué?' (why/cause)." },
  { id:"gap2-qw-20", themeId:"social-organization", type:"mcq", prompt:"[Qué vs Cuál] '¿___ es tu opinión sobre la nueva ley?' ¿Cuál es correcto?", options:["Cuál","Qué","Cuáles","Cómo"], correctAnswer:"Cuál", difficulty:"medium", points:20, explanation:"'¿Cuál es tu opinión?' follows the 'cuál + es' pattern for asking someone to specify/select their view." },
];

module.exports = { questions };
