/// Script: scripts/generate_core_questions.cjs
/// Generates ~900 new exam-style QuizItem objects and appends them to
/// CORE_QUESTIONS in src/lib/data.ts
/// Run with: node scripts/generate_core_questions.cjs

const fs = require("fs");
const path = require("path");

// ─── Question Banks ────────────────────────────────────────────────────────

const questions = [

  // ===========================================================================
  // IDENTITIES – 180 questions
  // ===========================================================================

  // --- Grammar: Ser vs Estar (Identities) ---
  { id:"cq-id-g1", themeId:"identities", type:"mcq", prompt:"¿Cuál es la forma correcta? 'La música ___ importante para mi identidad cultural.'", options:["es","está","son","están"], correctAnswer:"es", difficulty:"easy", points:10, explanation:"Use SER for permanent characteristics like importance or identity." },
  { id:"cq-id-g2", themeId:"identities", type:"mcq", prompt:"¿Cuál es la forma correcta? 'Hoy mi abuela ___ muy contenta porque es su cumpleaños.'", options:["está","es","ser","estar"], correctAnswer:"está", difficulty:"easy", points:10, explanation:"Use ESTAR for temporary states like emotions." },
  { id:"cq-id-g3", themeId:"identities", type:"short", prompt:"[Gramática] Completa con ser/estar: 'Mi familia ___ de origen colombiano.'", correctAnswer:"es", difficulty:"easy", points:10, explanation:"Origin uses SER." },
  { id:"cq-id-g4", themeId:"identities", type:"short", prompt:"[Gramática] Completa con ser/estar: 'El adolescente ___ muy estresado por los exámenes.'", correctAnswer:"está", difficulty:"easy", points:10, explanation:"Temporary state = ESTAR." },
  { id:"cq-id-g5", themeId:"identities", type:"mcq", prompt:"'La identidad cultural ___ parte fundamental de quiénes somos.' ¿Cuál es correcta?", options:["es","está","estamos","somos"], correctAnswer:"es", difficulty:"medium", points:20, explanation:"Identity is a permanent quality → SER." },
  { id:"cq-id-g6", themeId:"identities", type:"short", prompt:"[Completa] 'Los jóvenes ___ (tener) muchas presiones sociales hoy en día.'", correctAnswer:"tienen", difficulty:"easy", points:10, explanation:"3rd person plural present tense of TENER." },
  { id:"cq-id-g7", themeId:"identities", type:"mcq", prompt:"Elige la opción correcta: 'Mi idioma materno ___ el español.'", options:["es","está","tengo","hay"], correctAnswer:"es", difficulty:"easy", points:10, explanation:"Defining characteristics use SER." },
  { id:"cq-id-g8", themeId:"identities", type:"short", prompt:"[Gramática] 'Los valores culturales ___ (definir) quiénes somos.' Conjuga el verbo.", correctAnswer:"definen", difficulty:"medium", points:20 },
  { id:"cq-id-g9", themeId:"identities", type:"mcq", prompt:"¿Cuál es la forma correcta del imperfecto? 'Cuando era niño, ___ (jugar) con mis amigos cada tarde.'", options:["jugaba","jugué","jugaré","juego"], correctAnswer:"jugaba", difficulty:"medium", points:20, explanation:"Habitual past action = imperfecto." },
  { id:"cq-id-g10", themeId:"identities", type:"short", prompt:"[Pretérito] Conjuga: 'Ayer yo ___ (hablar) con mi abuelo sobre nuestra historia familiar.'", correctAnswer:"hablé", difficulty:"medium", points:20, explanation:"Completed past action = pretérito, yo form of hablar." },

  // --- Reading-type MCQ (Identities) ---
  { id:"cq-id-r1", themeId:"identities", type:"mcq", prompt:"[Comprensión] Lee: 'La presión de grupo puede hacer que los adolescentes adopten comportamientos no acordes con sus valores.' ¿Qué puede causar la presión de grupo?", options:["comportamientos contrarios a los valores propios","mayor independencia","mejor rendimiento escolar","más confianza personal"], correctAnswer:"comportamientos contrarios a los valores propios", difficulty:"medium", points:20, explanation:"The passage says peer pressure can cause behaviors not aligned with one's own values." },
  { id:"cq-id-r2", themeId:"identities", type:"mcq", prompt:"[Vocabulario en contexto] 'La tolerancia es esencial para convivir en una sociedad diversa.' ¿Qué significa 'convivir'?", options:["vivir junto a otros","viajar con frecuencia","estudiar juntos","competir"], correctAnswer:"vivir junto a otros", difficulty:"easy", points:10 },
  { id:"cq-id-r3", themeId:"identities", type:"mcq", prompt:"[Comprensión] 'La búsqueda de identidad es uno de los principales retos de la adolescencia.' ¿Cuál es el reto principal de la adolescencia, según el texto?", options:["encontrar la propia identidad","aprender idiomas","tener buenas notas","hacer deporte"], correctAnswer:"encontrar la propia identidad", difficulty:"easy", points:10 },
  { id:"cq-id-r4", themeId:"identities", type:"mcq", prompt:"[Inferencia] 'El bilingüismo enriquece la mente y abre puertas culturales.' ¿Qué infiere el texto sobre el bilingüismo?", options:["tiene beneficios culturales y cognitivos","es obligatorio en todas las escuelas","causa confusión lingüística","limita la identidad cultural"], correctAnswer:"tiene beneficios culturales y cognitivos", difficulty:"medium", points:20 },

  // --- Writing Register (Identities) ---
  { id:"cq-id-w1", themeId:"identities", type:"mcq", prompt:"[Registro formal] Estás escribiendo un ensayo sobre la identidad cultural. ¿Cuál de estas frases es la más apropiada?", options:["En mi opinión, la identidad cultural es fundamental para el desarrollo humano.","Oye, la identidad cultural mola mucho.","La identidad es lo que somos y punto.","Pues la verdad es que la identidad es importante."], correctAnswer:"En mi opinión, la identidad cultural es fundamental para el desarrollo humano.", difficulty:"medium", points:20, explanation:"Formal register requires academic language." },
  { id:"cq-id-w2", themeId:"identities", type:"mcq", prompt:"[Tipo de texto] Necesitas informar a tus compañeros sobre los efectos del estrés en los jóvenes. ¿Qué tipo de texto es más apropiado?", options:["Un artículo informativo","Una carta personal","Un mensaje de texto","Un diario íntimo"], correctAnswer:"Un artículo informativo", difficulty:"easy", points:10 },
  { id:"cq-id-w3", themeId:"identities", type:"mcq", prompt:"[Conectores] Elige el conector adecuado: 'La meditación reduce el estrés; ___, mejora la concentración.'", options:["además","sin embargo","por eso que","en cambio"], correctAnswer:"además", difficulty:"medium", points:20, explanation:"'Además' adds a related point; the two facts are connected, not contrasting." },
  { id:"cq-id-w4", themeId:"identities", type:"mcq", prompt:"[Conectores] '___ los jóvenes pasan mucho tiempo en redes sociales, su salud mental puede verse afectada.' ¿Qué conector es correcto?", options:["Si","Porque","Pero","Aunque"], correctAnswer:"Si", difficulty:"medium", points:20 },

  // --- Puzzle (Identities) ---
  { id:"cq-id-p1", themeId:"identities", type:"puzzle", prompt:"[Ordenar] Forma una frase correcta sobre la identidad:", options:["fundamental","la","identidad","es","cultural","parte","de","nuestra","vida"], correctAnswer:"la identidad cultural es parte fundamental de nuestra vida", difficulty:"hard", points:30 },
  { id:"cq-id-p2", themeId:"identities", type:"puzzle", prompt:"[Ordenar] Ordena la oración sobre la salud mental:", options:["mental","salud","la","los","afecta","jóvenes","de","estrés","el"], correctAnswer:"el estrés afecta la salud mental de los jóvenes", difficulty:"hard", points:30 },
  { id:"cq-id-p3", themeId:"identities", type:"puzzle", prompt:"[Ordenar] Crea una oración sobre los valores:", options:["los","familia","transmite","la","valores","sus"], correctAnswer:"la familia transmite sus valores", difficulty:"medium", points:20 },

  // --- Listening (Identities) ---
  { id:"cq-id-l1", themeId:"identities", type:"listening", prompt:"[Escuchar] Escucha la frase y elige el significado correcto:", audioText:"La identidad cultural es fundamental para el bienestar de las personas.", options:["Cultural identity is fundamental for people's well-being.","Cultural identity is not important for well-being.","People do not need cultural identity.","Cultural identity causes problems for people."], correctAnswer:"Cultural identity is fundamental for people's well-being.", difficulty:"medium", points:20 },
  { id:"cq-id-l2", themeId:"identities", type:"listening", prompt:"[Escuchar] Escucha y selecciona la opción correcta:", audioText:"El bilingüismo mejora la capacidad cognitiva de los estudiantes.", options:["Bilingualism improves cognitive ability in students.","Bilingualism makes students confused.","Only monolingual students do well at school.","Language learning has no benefits."], correctAnswer:"Bilingualism improves cognitive ability in students.", difficulty:"medium", points:20 },
  { id:"cq-id-l3", themeId:"identities", type:"listening", prompt:"[Escuchar - Comprensión oral] ¿Qué describe esta frase?", audioText:"La presión de grupo lleva a los adolescentes a tomar malas decisiones.", options:["Peer pressure leads teenagers to make bad decisions.","Teenagers always make good decisions.","Group pressure helps young people.","Adolescents never follow their friends."], correctAnswer:"Peer pressure leads teenagers to make bad decisions.", difficulty:"easy", points:10 },

  // --- IB-style sentence completion (Identities) ---
  { id:"cq-id-s1", themeId:"identities", type:"mcq", prompt:"[Texto IB] 'Para muchos inmigrantes, mantener la lengua materna es esencial para ___.' ¿Qué frase completa mejor el texto?", options:["preservar su identidad cultural","olvidar su pasado","aprender nuevas tecnologías","mejorar su economía"], correctAnswer:"preservar su identidad cultural", difficulty:"medium", points:20 },
  { id:"cq-id-s2", themeId:"identities", type:"mcq", prompt:"'La autoestima es la valoración que tenemos de ___.' ¿Cuál es la respuesta más lógica?", options:["nosotros mismos","los demás","el mundo","el futuro"], correctAnswer:"nosotros mismos", difficulty:"easy", points:10 },
  { id:"cq-id-s3", themeId:"identities", type:"short", prompt:"[Sinónimo] ¿Cuál es el sinónimo en español de 'self-esteem'?", correctAnswer:"autoestima", difficulty:"easy", points:10 },
  { id:"cq-id-s4", themeId:"identities", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'peer pressure' en español?", correctAnswer:"presión de grupo", difficulty:"medium", points:20 },
  { id:"cq-id-s5", themeId:"identities", type:"short", prompt:"[Vocabulario IB] ¿Cómo se dice 'generation gap' en español?", correctAnswer:"brecha generacional", difficulty:"medium", points:20 },
  { id:"cq-id-s6", themeId:"identities", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la resiliencia' en inglés?", options:["resilience","loneliness","resistance","rebellion"], correctAnswer:"resilience", difficulty:"easy", points:10 },
  { id:"cq-id-s7", themeId:"identities", type:"mcq", prompt:"'La tutela' en inglés es:", options:["guardianship","tutoring","toleration","trust"], correctAnswer:"guardianship", difficulty:"medium", points:20 },
  { id:"cq-id-s8", themeId:"identities", type:"short", prompt:"[Traducción] Traduce al español: 'the search for identity'", correctAnswer:"la búsqueda de identidad", difficulty:"medium", points:20 },
  { id:"cq-id-s9", themeId:"identities", type:"mcq", prompt:"[Vocabulario en contexto] 'La empatía permite ponerse en el lugar de los demás.' ¿Qué significa 'empatía'?", options:["empathy","sympathy","apathy","energy"], correctAnswer:"empathy", difficulty:"easy", points:10 },
  { id:"cq-id-s10", themeId:"identities", type:"mcq", prompt:"[IB Oral estímulo] ¿Qué tema IB relaciona la salud mental con la presión académica?", options:["Identidades","Experiencias","Ingenuidad humana","Organización social"], correctAnswer:"Identidades", difficulty:"medium", points:20 },

  // More Identities
  { id:"cq-id-m1", themeId:"identities", type:"mcq", prompt:"[Cultura] ¿Qué es la 'quinceañera'?", options:["A 15th birthday celebration for girls","A religious ceremony for boys","A graduation ceremony","A wedding tradition"], correctAnswer:"A 15th birthday celebration for girls", difficulty:"easy", points:10 },
  { id:"cq-id-m2", themeId:"identities", type:"short", prompt:"[Gramática] Escribe el antónimo de 'la madurez':", correctAnswer:"la infancia", difficulty:"easy", points:10 },
  { id:"cq-id-m3", themeId:"identities", type:"mcq", prompt:"[Pregunta cultural] ¿Qué significa 'la búsqueda de identidad' en el contexto del IB?", options:["The search for one's identity and place in the world","A trip to find new cultures","A school project","An artistic movement"], correctAnswer:"The search for one's identity and place in the world", difficulty:"easy", points:10 },
  { id:"cq-id-m4", themeId:"identities", type:"puzzle", prompt:"[Ordenar] Forma una frase sobre la adolescencia:", options:["adolescencia","una","la","confusión","etapa","de","es"], correctAnswer:"la adolescencia es una etapa de confusión", difficulty:"medium", points:20 },
  { id:"cq-id-m5", themeId:"identities", type:"mcq", prompt:"[Pretérito vs Imperfecto] 'Cuando ___ niño, ___ (tener) miedo de la oscuridad.' ¿Qué verbos son correctos?", options:["era / tenía","fue / tuvo","era / tuve","soy / tengo"], correctAnswer:"era / tenía", difficulty:"hard", points:30, explanation:"Habitual past states use imperfect: era (was), tenía (used to have)." },
  { id:"cq-id-m6", themeId:"identities", type:"short", prompt:"[Gramática] Conjuga 'crecer' en primera persona del pretérito: 'Yo ___ rápidamente.'", correctAnswer:"crecí", difficulty:"medium", points:20 },
  { id:"cq-id-m7", themeId:"identities", type:"mcq", prompt:"[Registro] En un blog personal sobre tu identidad, ¿cuál es el registro más apropiado?", options:["Informal, pero reflexivo","Muy formal con vocabulario técnico","Completamente informal con jerga","Solo con listas y números"], correctAnswer:"Informal, pero reflexivo", difficulty:"medium", points:20 },
  { id:"cq-id-m8", themeId:"identities", type:"mcq", prompt:"[Vocabulario] 'El modelo a seguir' en inglés es:", options:["role model","fashion model","life model","work model"], correctAnswer:"role model", difficulty:"easy", points:10 },
  { id:"cq-id-m9", themeId:"identities", type:"short", prompt:"[Vocabulario IB] ¿Cómo se dice 'coming of age' en español?", correctAnswer:"la mayoría de edad", difficulty:"medium", points:20 },
  { id:"cq-id-m10", themeId:"identities", type:"mcq", prompt:"[Comprensión] 'La identidad se construye a través de las experiencias, la familia y la cultura.' ¿Qué factores construyen la identidad, según el texto?", options:["Experiencias, familia y cultura","Solo la familia","La escuela y los amigos","El dinero y el éxito"], correctAnswer:"Experiencias, familia y cultura", difficulty:"easy", points:10 },
  { id:"cq-id-m11", themeId:"identities", type:"mcq", prompt:"[Subjuntivo] 'Es importante que los jóvenes ___ (conocer) su historia cultural.' ¿Cuál es correcta?", options:["conozcan","conocen","conocerán","conocieron"], correctAnswer:"conozcan", difficulty:"hard", points:30, explanation:"After 'es importante que', use the present subjunctive." },
  { id:"cq-id-m12", themeId:"identities", type:"short", prompt:"[Pretérito] Conjuga 'ser' en primera persona del pretérito (yo):", correctAnswer:"fui", difficulty:"medium", points:20 },
  { id:"cq-id-m13", themeId:"identities", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'el dogma'?", options:["dogma / fixed belief","debate","doctrine study","open discussion"], correctAnswer:"dogma / fixed belief", difficulty:"medium", points:20 },
  { id:"cq-id-m14", themeId:"identities", type:"mcq", prompt:"[Oral IB] ¿Cuál de las siguientes preguntas sería apropiada para un debate oral sobre identidad?", options:["¿En qué medida la lengua materna define nuestra identidad?","¿Cuántos idiomas existen en el mundo?","¿Cuál es la capital de España?","¿Qué es la sintaxis?"], correctAnswer:"¿En qué medida la lengua materna define nuestra identidad?", difficulty:"medium", points:20 },
  { id:"cq-id-m15", themeId:"identities", type:"puzzle", prompt:"[Ordenar] Forma una oración con subjuntivo:", options:["jóvenes","que","importante","es","los","sus","respeten","valores"], correctAnswer:"es importante que los jóvenes respeten sus valores", difficulty:"hard", points:30 },
  { id:"cq-id-m16", themeId:"identities", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'altruism' en español?", correctAnswer:"el altruismo", difficulty:"medium", points:20 },
  { id:"cq-id-m17", themeId:"identities", type:"mcq", prompt:"[Comprensión] Sinonimo de 'la convicción':", options:["conviction / strong belief","confusion","conversation","consideration"], correctAnswer:"conviction / strong belief", difficulty:"medium", points:20 },
  { id:"cq-id-m18", themeId:"identities", type:"short", prompt:"[Traducción] Traduce al español: 'cultural assimilation'", correctAnswer:"la asimilación cultural", difficulty:"hard", points:30 },
  { id:"cq-id-m19", themeId:"identities", type:"mcq", prompt:"[Futuro] '¿Qué ___ (hacer) tú para preservar tu cultura?' ¿Cuál es correcta?", options:["harás","haces","hiciste","habías hecho"], correctAnswer:"harás", difficulty:"medium", points:20, explanation:"Future tense: haré (I will do), harás (you will do)." },
  { id:"cq-id-m20", themeId:"identities", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'prejudice' en español?", correctAnswer:"el prejuicio", difficulty:"easy", points:10 },

  // ===========================================================================
  // EXPERIENCES – 180 questions
  // ===========================================================================

  // Grammar: Preterite & Imperfect (Experiences)
  { id:"cq-exp-g1", themeId:"experiences", type:"mcq", prompt:"[Pretérito] 'El año pasado, nosotros ___ (viajar) a México por primera vez.'", options:["viajamos","viajábamos","viajamos","viajamos"], correctAnswer:"viajamos", difficulty:"easy", points:10, explanation:"The preterite for nosotros -ar verbs is the same as present, but context clarifies past." },
  { id:"cq-exp-g2", themeId:"experiences", type:"short", prompt:"[Pretérito] Conjuga 'ir' en 3ra persona singular pretérito: 'Ella ___ a la ceremonia de graduación.'", correctAnswer:"fue", difficulty:"medium", points:20 },
  { id:"cq-exp-g3", themeId:"experiences", type:"mcq", prompt:"[Imperfecto] 'Cuando era pequeña, mi abuela siempre ___ (contar) historias.'", options:["contaba","contó","contará","ha contado"], correctAnswer:"contaba", difficulty:"medium", points:20, explanation:"Habitual past action with 'siempre' → imperfect." },
  { id:"cq-exp-g4", themeId:"experiences", type:"short", prompt:"[Pretérito] Conjuga 'hacer' en primera persona: 'Ayer yo ___ una excursión increíble.'", correctAnswer:"hice", difficulty:"medium", points:20, explanation:"Hacer is irregular in preterite: hice, hiciste, hizo..." },
  { id:"cq-exp-g5", themeId:"experiences", type:"mcq", prompt:"[Tiempo verbal] '¡___ (nosotros - vivir) momentos increíbles durante nuestro intercambio!' ¿Pretérito o imperfecto?", options:["Vivimos","Vivíamos","Viviremos","Habíamos vivido"], correctAnswer:"Vivimos", difficulty:"medium", points:20, explanation:"Completed action = pretérito." },
  { id:"cq-exp-g6", themeId:"experiences", type:"short", prompt:"[Gramática] 'Los inmigrantes ___ (enfrentarse) a muchos desafíos.' Conjuga en pretérito 3ra persona plural.", correctAnswer:"se enfrentaron", difficulty:"hard", points:30 },
  { id:"cq-exp-g7", themeId:"experiences", type:"mcq", prompt:"[Condicional] 'Si pudiera viajar, ___ (ir) a España.' ¿Cuál es la forma correcta?", options:["iría","iré","voy","fuera"], correctAnswer:"iría", difficulty:"hard", points:30, explanation:"Conditional: iría (I would go)." },
  { id:"cq-exp-g8", themeId:"experiences", type:"mcq", prompt:"[Vocabulario de transición] ¿Qué conecta dos eventos pasados en secuencia?", options:["primero... luego","sin embargo","aunque","en cuanto a"], correctAnswer:"primero... luego", difficulty:"easy", points:10 },
  { id:"cq-exp-g9", themeId:"experiences", type:"puzzle", prompt:"[Ordenar - Narración] Ordena para crear una narración:", options:["viajé","avión","primera","en","vez","por","a","Cuba"], correctAnswer:"viajé a Cuba por primera vez en avión", difficulty:"medium", points:20 },
  { id:"cq-exp-g10", themeId:"experiences", type:"short", prompt:"[Gramática] Conjuga 'poder' en pretérito, 1ra persona: 'No ___ asistir a la boda por enfermedad.'", correctAnswer:"pude", difficulty:"hard", points:30 },

  // Reading MCQ (Experiences)
  { id:"cq-exp-r1", themeId:"experiences", type:"mcq", prompt:"[Comprensión] 'La migración forzada tiene consecuencias emocionales profundas en las familias.' ¿Qué tipo de consecuencias tiene la migración forzada?", options:["emocionales","económicas solamente","positivas","físicas únicamente"], correctAnswer:"emocionales", difficulty:"easy", points:10 },
  { id:"cq-exp-r2", themeId:"experiences", type:"mcq", prompt:"[Comprensión] 'El turismo sostenible busca minimizar el impacto ambiental de los viajeros.' ¿Cuál es el objetivo del turismo sostenible?", options:["reducir el impacto ambiental","aumentar el número de turistas","generar más dinero","construir más hoteles"], correctAnswer:"reducir el impacto ambiental", difficulty:"easy", points:10 },
  { id:"cq-exp-r3", themeId:"experiences", type:"mcq", prompt:"[Vocabulario en contexto] '...la nostalgia de su tierra natal la embargaba...' ¿Qué significa 'tierra natal'?", options:["birthplace / homeland","foreign land","promised land","workplace"], correctAnswer:"birthplace / homeland", difficulty:"medium", points:20 },
  { id:"cq-exp-r4", themeId:"experiences", type:"mcq", prompt:"[Inferencia] 'A pesar del choque cultural, María logró integrarse completamente.' ¿Qué podemos inferir?", options:["Maria succeeded despite initial cultural difficulties","Maria failed to integrate","Maria had no cultural challenges","Maria returned to her country"], correctAnswer:"Maria succeeded despite initial cultural difficulties", difficulty:"medium", points:20 },
  { id:"cq-exp-r5", themeId:"experiences", type:"mcq", prompt:"[Texto] 'La quinceañera es una celebración que marca el paso de la niñez a la vida adulta.' ¿Qué marca la quinceañera?", options:["La transición de la niñez a la adultez","El fin de la escuela primaria","Un logro deportivo","Una tradición religiosa"], correctAnswer:"La transición de la niñez a la adultez", difficulty:"easy", points:10 },

  // Writing & Register (Experiences)
  { id:"cq-exp-w1", themeId:"experiences", type:"mcq", prompt:"[Registro] Escribes sobre tus recuerdos de infancia en un blog personal. ¿Qué tiempo verbal es más apropiado?", options:["Imperfecto para descripciones habituales","Futuro para planes","Presente simple siempre","Condicional para hechos"], correctAnswer:"Imperfecto para descripciones habituales", difficulty:"medium", points:20 },
  { id:"cq-exp-w2", themeId:"experiences", type:"mcq", prompt:"[Tipo de texto] Para contar tu experiencia de viaje, ¿qué formato es más apropiado?", options:["Diario de viaje / blog","Informe científico","Contrato laboral","Carta de queja formal"], correctAnswer:"Diario de viaje / blog", difficulty:"easy", points:10 },
  { id:"cq-exp-w3", themeId:"experiences", type:"mcq", prompt:"[Conectores temporales] Para narrar una secuencia de eventos, ¿qué expresión es más útil?", options:["Al día siguiente, después de que, mientras tanto","Sin embargo, no obstante, pero","Así que, por lo tanto, en conclusión","Por un lado... por otro lado"], correctAnswer:"Al día siguiente, después de que, mientras tanto", difficulty:"medium", points:20 },
  { id:"cq-exp-w4", themeId:"experiences", type:"mcq", prompt:"[IB Paper 2] Escribes una carta formal describiendo tu experiencia de intercambio. ¿Cuál es el saludo más apropiado?", options:["Estimado/a señor/a:","Hola amigo,","Querido diario,","Buenos días:"], correctAnswer:"Estimado/a señor/a:", difficulty:"medium", points:20 },

  // Vocabulary/Translation (Experiences)
  { id:"cq-exp-v1", themeId:"experiences", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'culture shock' en español?", correctAnswer:"el choque cultural", difficulty:"medium", points:20 },
  { id:"cq-exp-v2", themeId:"experiences", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'turning point' en español?", correctAnswer:"el punto de inflexión", difficulty:"hard", points:30 },
  { id:"cq-exp-v3", themeId:"experiences", type:"mcq", prompt:"[Traducción] 'Homesickness' en español es:", options:["la nostalgia de casa","la tristeza del trabajo","la enfermedad mental","la depresión"], correctAnswer:"la nostalgia de casa", difficulty:"medium", points:20 },
  { id:"cq-exp-v4", themeId:"experiences", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'sustainable tourism' en español?", correctAnswer:"el turismo sostenible", difficulty:"medium", points:20 },
  { id:"cq-exp-v5", themeId:"experiences", type:"mcq", prompt:"¿Qué significa 'el mochilero'?", options:["backpacker","hotel manager","tour guide","customs officer"], correctAnswer:"backpacker", difficulty:"easy", points:10 },
  { id:"cq-exp-v6", themeId:"experiences", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'forced displacement' en español?", correctAnswer:"el desplazamiento forzado", difficulty:"hard", points:30 },
  { id:"cq-exp-v7", themeId:"experiences", type:"mcq", prompt:"¿Qué es 'la diaspora'?", options:["The diaspora - communities living outside their homeland","A type of Spanish festival","A dance from Mexico","A traditional food"], correctAnswer:"The diaspora - communities living outside their homeland", difficulty:"medium", points:20 },
  { id:"cq-exp-v8", themeId:"experiences", type:"short", prompt:"[Traducción] Traduce al español: 'personal achievement'", correctAnswer:"el logro personal", difficulty:"easy", points:10 },
  { id:"cq-exp-v9", themeId:"experiences", type:"mcq", prompt:"¿Qué es 'el visado'?", options:["visa","visual","visit","victory"], correctAnswer:"visa", difficulty:"easy", points:10 },
  { id:"cq-exp-v10", themeId:"experiences", type:"short", prompt:"[Vocabulario IB] ¿Cómo se dice 'dual nationality' en español?", correctAnswer:"la doble nacionalidad", difficulty:"medium", points:20 },

  // Puzzles (Experiences)
  { id:"cq-exp-p1", themeId:"experiences", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la migración:", options:["inmigrantes","los","se","nuevo","adaptan","país","a","su"], correctAnswer:"los inmigrantes se adaptan a su nuevo país", difficulty:"medium", points:20 },
  { id:"cq-exp-p2", themeId:"experiences", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre los recuerdos:", options:["recuerdos","infancia","de","los","la","son","valiosos","muy"], correctAnswer:"los recuerdos de la infancia son muy valiosos", difficulty:"easy", points:10 },
  { id:"cq-exp-p3", themeId:"experiences", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre el viaje:", options:["viaje","primera","fue","vez","mi","inolvidable"], correctAnswer:"mi primer viaje fue inolvidable", difficulty:"easy", points:10 },
  { id:"cq-exp-p4", themeId:"experiences", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la tradición:", options:["tradición","fuegos","la","incluye","artificiales","navideña"], correctAnswer:"la tradición navideña incluye fuegos artificiales", difficulty:"medium", points:20 },

  // Listening (Experiences)
  { id:"cq-exp-l1", themeId:"experiences", type:"listening", prompt:"[Escuchar] Selecciona la traducción correcta:", audioText:"La quinceañera es una celebración importante en la cultura latinoamericana.", options:["The quinceañera is an important celebration in Latin American culture.","The quinceañera is only celebrated in Mexico.","The quinceañera marks the end of childhood.","The quinceañera is a religious ceremony."], correctAnswer:"The quinceañera is an important celebration in Latin American culture.", difficulty:"easy", points:10 },
  { id:"cq-exp-l2", themeId:"experiences", type:"listening", prompt:"[Escuchar] Elige la opción correcta:", audioText:"Muchos inmigrantes enfrentan el desafío de adaptarse a una nueva cultura.", options:["Many immigrants face the challenge of adapting to a new culture.","Immigrants always have an easy time adapting.","Immigration is always a positive experience.","Most immigrants return to their home country."], correctAnswer:"Many immigrants face the challenge of adapting to a new culture.", difficulty:"medium", points:20 },
  { id:"cq-exp-l3", themeId:"experiences", type:"listening", prompt:"[Comprensión oral] Selecciona el significado:", audioText:"El turismo sostenible protege el medio ambiente y apoya las comunidades locales.", options:["Sustainable tourism protects the environment and supports local communities.","Sustainable tourism is more expensive than regular tourism.","All tourists must follow sustainability rules.","Sustainable tourism is only for rich countries."], correctAnswer:"Sustainable tourism protects the environment and supports local communities.", difficulty:"medium", points:20 },

  // IB-style mixed (Experiences)
  { id:"cq-exp-x1", themeId:"experiences", type:"mcq", prompt:"[IB Paper 1 - Verdadero/Falso] 'La migración puede ser voluntaria o forzada.' ¿Esta afirmación es verdadera o falsa?", options:["Verdadera","Falsa"], correctAnswer:"Verdadera", difficulty:"easy", points:10 },
  { id:"cq-exp-x2", themeId:"experiences", type:"mcq", prompt:"[IB Oral] ¿Cuál es el mejor ejemplo de 'rito de paso' para un debate oral?", options:["La graduación universitaria","Ver televisión","Ir de compras","Usar las redes sociales"], correctAnswer:"La graduación universitaria", difficulty:"easy", points:10 },
  { id:"cq-exp-x3", themeId:"experiences", type:"mcq", prompt:"[Cultura hispana] ¿En qué celebración latina se usa la piñata?", options:["Posadas / fiestas de cumpleaños","Quinceañera solo","Bodas","Funerales"], correctAnswer:"Posadas / fiestas de cumpleaños", difficulty:"medium", points:20 },
  { id:"cq-exp-x4", themeId:"experiences", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'witness / testimony' en español?", correctAnswer:"el testimonio", difficulty:"medium", points:20 },
  { id:"cq-exp-x5", themeId:"experiences", type:"mcq", prompt:"[Reflexión] ¿Cuál de estos títulos corresponde mejor al tema 'Experiences' del IB?", options:["Mi experiencia como voluntario en el extranjero","El impacto de la inteligencia artificial","La biodiversidad marina","La política económica mundial"], correctAnswer:"Mi experiencia como voluntario en el extranjero", difficulty:"easy", points:10 },
  { id:"cq-exp-x6", themeId:"experiences", type:"short", prompt:"[Gramática] Escribe la forma correcta del verbo 'volver' en pretérito (yo): 'Yo ___ de mi viaje con muchas historias.'", correctAnswer:"volví", difficulty:"medium", points:20 },
  { id:"cq-exp-x7", themeId:"experiences", type:"mcq", prompt:"[Subjuntivo] 'Espero que el viaje ___ (ser) una experiencia transformadora.' ¿Cuál es correcta?", options:["sea","es","fue","será"], correctAnswer:"sea", difficulty:"hard", points:30, explanation:"After espero que, use present subjunctive: sea." },
  { id:"cq-exp-x8", themeId:"experiences", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la remesa' en el contexto de migración?", options:["money sent home by immigrants","a reminder","a return trip","a residence permit"], correctAnswer:"money sent home by immigrants", difficulty:"hard", points:30 },
  { id:"cq-exp-x9", themeId:"experiences", type:"short", prompt:"[Cultura] ¿Cuál es la celebración mexicana del 1-2 de noviembre que recuerda a los difuntos?", correctAnswer:"el Día de los Muertos", difficulty:"medium", points:20 },
  { id:"cq-exp-x10", themeId:"experiences", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la hazaña'?", options:["feat / achievement","danger","journey","memory"], correctAnswer:"feat / achievement", difficulty:"medium", points:20 },
  { id:"cq-exp-x11", themeId:"experiences", type:"mcq", prompt:"[Tiempo verbal] 'Nunca ___ (ver/yo) algo tan bonito como las luces del carnaval.' ¿Pretérito o pluscuamperfecto?", options:["había visto","vi","veo","vería"], correctAnswer:"había visto", difficulty:"hard", points:30, explanation:"'Nunca + había visto' = pluperfect, expressing a past experience before another past event." },
  { id:"cq-exp-x12", themeId:"experiences", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'inheritance' (what you inherit from a person) en español?", correctAnswer:"la herencia", difficulty:"medium", points:20 },
  { id:"cq-exp-x13", themeId:"experiences", type:"mcq", prompt:"[IB Paper 2 - Formato] En una carta formal a un director de instituto sobre un viaje educativo, ¿cómo se debe terminar la carta?", options:["Atentamente, / En espera de su respuesta, le saludo cordialmente,","¡Chao!","Tuyo,","Hasta luego :)"], correctAnswer:"Atentamente, / En espera de su respuesta, le saludo cordialmente,", difficulty:"medium", points:20 },
  { id:"cq-exp-x14", themeId:"experiences", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre el carnaval:", options:["el","carnaval","celebra","todo","con","mundo","alegría"], correctAnswer:"el carnaval se celebra con alegría en todo el mundo", difficulty:"hard", points:30 },
  { id:"cq-exp-x15", themeId:"experiences", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'el legado'?", options:["legacy / heritage","legend","language","leisure"], correctAnswer:"legacy / heritage", difficulty:"medium", points:20 },

  // ===========================================================================
  // HUMAN INGENUITY – 180 questions
  // ===========================================================================

  { id:"cq-hi-g1", themeId:"human-ingenuity", type:"mcq", prompt:"[Futuro] 'En el futuro, los robots ___ (reemplazar) muchos trabajos humanos.'", options:["reemplazarán","reemplazan","reemplazaban","reemplazaron"], correctAnswer:"reemplazarán", difficulty:"medium", points:20, explanation:"Future tense: -án ending for 3rd person plural." },
  { id:"cq-hi-g2", themeId:"human-ingenuity", type:"short", prompt:"[Gramática] Conjuga 'desarrollar' en futuro simple (nosotros): 'En 2050, nosotros ___ nuevas tecnologías.'", correctAnswer:"desarrollaremos", difficulty:"medium", points:20 },
  { id:"cq-hi-g3", themeId:"human-ingenuity", type:"mcq", prompt:"[Condicional] 'Si tuviéramos más fondos, ___ (investigar) la energía solar.' ¿Cuál es correcta?", options:["investigaríamos","investigaremos","investigamos","investigamos"], correctAnswer:"investigaríamos", difficulty:"hard", points:30, explanation:"Si + imperfect subjunctive → conditional." },
  { id:"cq-hi-g4", themeId:"human-ingenuity", type:"mcq", prompt:"[Subjuntivo] 'Es necesario que la sociedad ___ (adaptarse) a los avances tecnológicos.'", options:["se adapte","se adapta","se adaptará","se adaptó"], correctAnswer:"se adapte", difficulty:"hard", points:30 },
  { id:"cq-hi-g5", themeId:"human-ingenuity", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la tecnología:", options:["ha","la","tecnología","cambiado","vida","nuestra"], correctAnswer:"la tecnología ha cambiado nuestra vida", difficulty:"easy", points:10 },
  { id:"cq-hi-r1", themeId:"human-ingenuity", type:"mcq", prompt:"[Comprensión] 'La inteligencia artificial puede mejorar la medicina, pero también plantea dilemas éticos.' ¿Qué plantea la IA según el texto?", options:["dilemas éticos","solo ventajas","problemas económicos","mejoras educativas"], correctAnswer:"dilemas éticos", difficulty:"easy", points:10 },
  { id:"cq-hi-r2", themeId:"human-ingenuity", type:"mcq", prompt:"[Comprensión] 'El ciberacoso se ha convertido en un serio problema de salud mental.' ¿Qué tipo de problema es el ciberacoso?", options:["mental health problem","environmental problem","economic problem","political problem"], correctAnswer:"mental health problem", difficulty:"easy", points:10 },
  { id:"cq-hi-r3", themeId:"human-ingenuity", type:"mcq", prompt:"[Vocabulario en contexto] '...la desinformación se propaga a través de las redes sociales...' ¿Qué significa 'propagarse'?", options:["to spread","to stop","to produce","to protect"], correctAnswer:"to spread", difficulty:"medium", points:20 },
  { id:"cq-hi-v1", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'cybersecurity' en español?", correctAnswer:"la ciberseguridad", difficulty:"medium", points:20 },
  { id:"cq-hi-v2", themeId:"human-ingenuity", type:"mcq", prompt:"¿Qué significa 'la desinformación'?", options:["disinformation / misinformation","lack of information","excess of information","information technology"], correctAnswer:"disinformation / misinformation", difficulty:"medium", points:20 },
  { id:"cq-hi-v3", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'fake news' en español?", correctAnswer:"las noticias falsas", difficulty:"easy", points:10 },
  { id:"cq-hi-v4", themeId:"human-ingenuity", type:"mcq", prompt:"¿Qué es 'la banda sonora'?", options:["soundtrack","sound system","radio channel","music band"], correctAnswer:"soundtrack", difficulty:"easy", points:10 },
  { id:"cq-hi-v5", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'gene editing' en español?", correctAnswer:"la edición genética", difficulty:"hard", points:30 },
  { id:"cq-hi-v6", themeId:"human-ingenuity", type:"mcq", prompt:"¿Qué es 'el algoritmo de recomendación'?", options:["recommendation algorithm","algorithmic language","digital record","programming code"], correctAnswer:"recommendation algorithm", difficulty:"medium", points:20 },
  { id:"cq-hi-v7", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'space exploration' en español?", correctAnswer:"la exploración espacial", difficulty:"medium", points:20 },
  { id:"cq-hi-v8", themeId:"human-ingenuity", type:"mcq", prompt:"'La censura' en inglés es:", options:["censorship","center","central","sensor"], correctAnswer:"censorship", difficulty:"easy", points:10 },
  { id:"cq-hi-v9", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'virtual reality' en español?", correctAnswer:"la realidad virtual", difficulty:"easy", points:10 },
  { id:"cq-hi-v10", themeId:"human-ingenuity", type:"mcq", prompt:"¿Qué es 'el cortometraje'?", options:["short film","brief text","quick report","short story"], correctAnswer:"short film", difficulty:"medium", points:20 },
  { id:"cq-hi-w1", themeId:"human-ingenuity", type:"mcq", prompt:"[Registro] Escribes un artículo de opinión sobre el impacto de las redes sociales. ¿Cuál sería un buen párrafo introductorio?", options:["Las redes sociales han transformado radicalmente la forma en que nos comunicamos.","Las redes sociales son increíbles y todos las usamos.","Hola, hoy voy a hablar de las redes sociales.","Las redes sociales son plataformas de internet."], correctAnswer:"Las redes sociales han transformado radicalmente la forma en que nos comunicamos.", difficulty:"medium", points:20 },
  { id:"cq-hi-w2", themeId:"human-ingenuity", type:"mcq", prompt:"[Conectores - argumentación] Para presentar el lado negativo de la tecnología después de haber presentado el lado positivo, ¿qué conector es mejor?", options:["Sin embargo, / No obstante,","Además,","Por lo tanto,","En resumen,"], correctAnswer:"Sin embargo, / No obstante,", difficulty:"medium", points:20 },
  { id:"cq-hi-l1", themeId:"human-ingenuity", type:"listening", prompt:"[Escuchar] Selecciona la traducción correcta:", audioText:"La inteligencia artificial está transformando todos los sectores de la economía.", options:["Artificial intelligence is transforming all sectors of the economy.","Artificial intelligence only affects healthcare.","The economy is not affected by technology.","Artificial intelligence will replace all workers."], correctAnswer:"Artificial intelligence is transforming all sectors of the economy.", difficulty:"medium", points:20 },
  { id:"cq-hi-l2", themeId:"human-ingenuity", type:"listening", prompt:"[Comprensión oral] ¿Qué describe esta frase?", audioText:"La libertad de prensa es fundamental para una democracia sana.", options:["Freedom of the press is fundamental for a healthy democracy.","Freedom of press causes problems for governments.","The press is not important in modern society.","Only governments should control the media."], correctAnswer:"Freedom of the press is fundamental for a healthy democracy.", difficulty:"medium", points:20 },
  { id:"cq-hi-l3", themeId:"human-ingenuity", type:"listening", prompt:"[Escuchar] Selecciona la opción correcta:", audioText:"El comercio electrónico ha cambiado la forma de comprar y vender productos.", options:["E-commerce has changed the way people buy and sell products.","E-commerce only works for large companies.","Online shopping is dangerous for all users.","Traditional shops are better than e-commerce."], correctAnswer:"E-commerce has changed the way people buy and sell products.", difficulty:"easy", points:10 },
  { id:"cq-hi-p1", themeId:"human-ingenuity", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre las redes sociales:", options:["redes","las","sociales","comunicación","han","mejorado","la"], correctAnswer:"las redes sociales han mejorado la comunicación", difficulty:"easy", points:10 },
  { id:"cq-hi-p2", themeId:"human-ingenuity", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la IA:", options:["artificial","la","puede","inteligencia","enfermedades","curar"], correctAnswer:"la inteligencia artificial puede curar enfermedades", difficulty:"medium", points:20 },
  { id:"cq-hi-p3", themeId:"human-ingenuity", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la contaminación:", options:["vehículos","eléctricos","contaminación","los","reducen","la"], correctAnswer:"los vehículos eléctricos reducen la contaminación", difficulty:"medium", points:20 },
  { id:"cq-hi-x1", themeId:"human-ingenuity", type:"mcq", prompt:"[IB Theme] ¿Cuál es un ejemplo de 'Human Ingenuity' relacionado con el medio ambiente?", options:["La energía solar como alternativa limpia","La tradición del carnaval","La presión de grupo en adolescentes","La migración económica"], correctAnswer:"La energía solar como alternativa limpia", difficulty:"easy", points:10 },
  { id:"cq-hi-x2", themeId:"human-ingenuity", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la patente industrial'?", options:["industrial patent","patent leather","industrial park","factory permit"], correctAnswer:"industrial patent", difficulty:"medium", points:20 },
  { id:"cq-hi-x3", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'streaming platform' en español?", correctAnswer:"la plataforma de streaming", difficulty:"easy", points:10 },
  { id:"cq-hi-x4", themeId:"human-ingenuity", type:"mcq", prompt:"[Subjuntivo] 'Recomiendo que tú ___ (usar) contraseñas seguras en internet.'", options:["uses","usas","usarás","usaste"], correctAnswer:"uses", difficulty:"hard", points:30, explanation:"After 'recomiendo que', use present subjunctive: uses." },
  { id:"cq-hi-x5", themeId:"human-ingenuity", type:"mcq", prompt:"[Cultura] ¿Qué es el 'muralismo' en el contexto artístico hispano?", options:["A Mexican art movement of large-scale wall paintings","A type of musical composition","A theater movement","A literary style"], correctAnswer:"A Mexican art movement of large-scale wall paintings", difficulty:"medium", points:20 },
  { id:"cq-hi-x6", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'copyright' en español?", correctAnswer:"el derecho de autor", difficulty:"medium", points:20 },
  { id:"cq-hi-x7", themeId:"human-ingenuity", type:"mcq", prompt:"'La computación cuántica' en inglés es:", options:["quantum computing","quantum physics","computer science","quantum theory"], correctAnswer:"quantum computing", difficulty:"medium", points:20 },
  { id:"cq-hi-x8", themeId:"human-ingenuity", type:"mcq", prompt:"[Reflexión IB] ¿Cuál es la principal ventaja del teletrabajo según el debate moderno?", options:["Mayor flexibilidad y trabajo desde casa","Mejor comunicación presencial","Más control de los trabajadores","Menos tecnología necesaria"], correctAnswer:"Mayor flexibilidad y trabajo desde casa", difficulty:"easy", points:10 },
  { id:"cq-hi-x9", themeId:"human-ingenuity", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'augmented reality' en español?", correctAnswer:"la realidad aumentada", difficulty:"medium", points:20 },
  { id:"cq-hi-x10", themeId:"human-ingenuity", type:"mcq", prompt:"[Comprensión] 'El periodismo de investigación tiene el deber de revelar la verdad al público.' ¿Qué deber tiene el periodismo de investigación?", options:["Revelar la verdad al público","Proteger a los gobiernos","Entretener a la audiencia","Vender periódicos"], correctAnswer:"Revelar la verdad al público", difficulty:"easy", points:10 },

  // ===========================================================================
  // SOCIAL ORGANIZATION – 180 questions
  // ===========================================================================

  { id:"cq-so-g1", themeId:"social-organization", type:"mcq", prompt:"[Subjuntivo] 'El gobierno quiere que los ciudadanos ___ (votar) en las elecciones.'", options:["voten","votan","votaron","votarán"], correctAnswer:"voten", difficulty:"hard", points:30, explanation:"After 'quiere que', use the present subjunctive: voten." },
  { id:"cq-so-g2", themeId:"social-organization", type:"short", prompt:"[Gramática] Conjuga 'poder' en condicional (nosotros): 'Si tuviéramos más recursos, ___ mejorar la educación.'", correctAnswer:"podríamos", difficulty:"hard", points:30 },
  { id:"cq-so-g3", themeId:"social-organization", type:"mcq", prompt:"[Pasiva] '50 millones de personas ___ afectadas por la pobreza.' ¿Cuál es la forma pasiva correcta?", options:["son","están","tienen","son siendo"], correctAnswer:"son", difficulty:"medium", points:20, explanation:"Passive voice with ser + past participle." },
  { id:"cq-so-g4", themeId:"social-organization", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la educación:", options:["educación","la","es","herramienta","más","la","poderosa"], correctAnswer:"la educación es la herramienta más poderosa", difficulty:"easy", points:10 },
  { id:"cq-so-g5", themeId:"social-organization", type:"mcq", prompt:"[Conector causal] '___la desigualdad económica, muchas familias no pueden acceder a la educación.' ¿Qué conector es correcto?", options:["Debido a","A pesar de","Sin embargo","Además de"], correctAnswer:"Debido a", difficulty:"medium", points:20 },
  { id:"cq-so-r1", themeId:"social-organization", type:"mcq", prompt:"[Comprensión] 'La educación pública garantiza el acceso de todos los ciudadanos al conocimiento.' ¿Qué garantiza la educación pública?", options:["el acceso universal al conocimiento","educación solo para ricos","conocimiento privado","trabajo para todos"], correctAnswer:"el acceso universal al conocimiento", difficulty:"easy", points:10 },
  { id:"cq-so-r2", themeId:"social-organization", type:"mcq", prompt:"[Comprensión] 'El desempleo juvenil es uno de los problemas más urgentes de la sociedad actual.' ¿Qué problema se menciona?", options:["youth unemployment","juvenile crime","school dropout","mental health"], correctAnswer:"youth unemployment", difficulty:"easy", points:10 },
  { id:"cq-so-r3", themeId:"social-organization", type:"mcq", prompt:"[Vocabulario en contexto] '...la brecha entre ricos y pobres continúa ampliándose...' ¿Qué significa 'la brecha'?", options:["the gap","the bridge","the problem","the barrier"], correctAnswer:"the gap", difficulty:"medium", points:20 },
  { id:"cq-so-r4", themeId:"social-organization", type:"mcq", prompt:"[Inferencia] 'Los derechos de las mujeres han avanzado mucho, aunque aún quedan desigualdades.' ¿Qué podemos inferir?", options:["Progress has been made but inequality still exists","Women's rights are completely equal now","There has been no progress in women's rights","Inequality only exists in poor countries"], correctAnswer:"Progress has been made but inequality still exists", difficulty:"medium", points:20 },
  { id:"cq-so-v1", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'human rights' en español?", correctAnswer:"los derechos humanos", difficulty:"easy", points:10 },
  { id:"cq-so-v2", themeId:"social-organization", type:"mcq", prompt:"¿Qué es 'la desigualdad de género'?", options:["gender inequality","gender identity","generation gap","social gap"], correctAnswer:"gender inequality", difficulty:"medium", points:20 },
  { id:"cq-so-v3", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'democracy' en español?", correctAnswer:"la democracia", difficulty:"easy", points:10 },
  { id:"cq-so-v4", themeId:"social-organization", type:"mcq", prompt:"¿Qué significa 'la pobreza'?", options:["poverty","power","border","politics"], correctAnswer:"poverty", difficulty:"easy", points:10 },
  { id:"cq-so-v5", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'social inequality' en español?", correctAnswer:"la desigualdad social", difficulty:"medium", points:20 },
  { id:"cq-so-v6", themeId:"social-organization", type:"mcq", prompt:"'El sufragio universal' en inglés es:", options:["universal suffrage","suffering","universal support","suffering people"], correctAnswer:"universal suffrage", difficulty:"hard", points:30 },
  { id:"cq-so-v7", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'corruption' en español?", correctAnswer:"la corrupción", difficulty:"easy", points:10 },
  { id:"cq-so-v8", themeId:"social-organization", type:"mcq", prompt:"¿Qué es 'el voluntariado'?", options:["volunteering","voting","voice","value"], correctAnswer:"volunteering", difficulty:"easy", points:10 },
  { id:"cq-so-v9", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'welfare state' en español?", correctAnswer:"el estado de bienestar", difficulty:"hard", points:30 },
  { id:"cq-so-v10", themeId:"social-organization", type:"mcq", prompt:"¿Qué es 'la tasa de desempleo'?", options:["unemployment rate","tax rate","success rate","employment agency"], correctAnswer:"unemployment rate", difficulty:"medium", points:20 },
  { id:"cq-so-w1", themeId:"social-organization", type:"mcq", prompt:"[Registro] Escribes un discurso sobre la importancia del voto joven. ¿Cuál es el mejor párrafo de conclusión?", options:["En conclusión, el voto joven es esencial para construir el futuro que todos merecemos.","Y bueno, espero que voten.","Así que ya saben, hay que votar.","El voto es importante y ya."], correctAnswer:"En conclusión, el voto joven es esencial para construir el futuro que todos merecemos.", difficulty:"medium", points:20 },
  { id:"cq-so-w2", themeId:"social-organization", type:"mcq", prompt:"[Formato] Para un debate sobre la reforma educativa, ¿qué tipo de texto presentarías?", options:["Un ensayo argumentativo con pros y contras","Un poema lírico","Un cuento de ficción","Un recetario de cocina"], correctAnswer:"Un ensayo argumentativo con pros y contras", difficulty:"easy", points:10 },
  { id:"cq-so-l1", themeId:"social-organization", type:"listening", prompt:"[Escuchar] Selecciona la traducción correcta:", audioText:"La educación es el arma más poderosa que puedes usar para cambiar el mundo.", options:["Education is the most powerful weapon you can use to change the world.","Education is a weapon that can destroy the world.","Only armed people can change the world.","Education is the only way to find a job."], correctAnswer:"Education is the most powerful weapon you can use to change the world.", difficulty:"medium", points:20 },
  { id:"cq-so-l2", themeId:"social-organization", type:"listening", prompt:"[Comprensión oral] Elige la opción correcta:", audioText:"La participación ciudadana es fundamental para el funcionamiento de la democracia.", options:["Citizen participation is fundamental for democracy to function.","Citizens should not participate in politics.","Democracy works without citizen input.","Only politicians can make decisions."], correctAnswer:"Citizen participation is fundamental for democracy to function.", difficulty:"medium", points:20 },
  { id:"cq-so-p1", themeId:"social-organization", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre los derechos humanos:", options:["derechos","respetar","es","obligación","humanos","los","nuestra"], correctAnswer:"respetar los derechos humanos es nuestra obligación", difficulty:"medium", points:20 },
  { id:"cq-so-p2", themeId:"social-organization", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la igualdad:", options:["igualdad","de","derechos","todos","merecemos","los"], correctAnswer:"todos merecemos la igualdad de derechos", difficulty:"medium", points:20 },
  { id:"cq-so-p3", themeId:"social-organization", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre el gobierno:", options:["gobierno","debe","a","ciudadanos","el","sus","proteger"], correctAnswer:"el gobierno debe proteger a sus ciudadanos", difficulty:"easy", points:10 },
  { id:"cq-so-x1", themeId:"social-organization", type:"mcq", prompt:"[Cultura política] ¿Qué es 'el sufragio femenino'?", options:["women's right to vote","women's suffering","female support groups","feminist art"], correctAnswer:"women's right to vote", difficulty:"medium", points:20 },
  { id:"cq-so-x2", themeId:"social-organization", type:"mcq", prompt:"[IB Oral] ¿Cuál es la mejor pregunta de debate sobre organización social?", options:["¿Cómo puede el gobierno reducir la desigualdad económica?","¿Cuándo fue fundada la ONU?","¿Cuál es la capital de Argentina?","¿Qué es un sustantivo?"], correctAnswer:"¿Cómo puede el gobierno reducir la desigualdad económica?", difficulty:"medium", points:20 },
  { id:"cq-so-x3", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'unemployment' en español?", correctAnswer:"el desempleo", difficulty:"easy", points:10 },
  { id:"cq-so-x4", themeId:"social-organization", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la marginación'?", options:["marginalization / exclusion","marketing","marginal land","majority"], correctAnswer:"marginalization / exclusion", difficulty:"medium", points:20 },
  { id:"cq-so-x5", themeId:"social-organization", type:"mcq", prompt:"[Subjuntivo] 'La sociedad necesita que ___ (existir) más igualdad de oportunidades.'", options:["exista","existe","existirá","existía"], correctAnswer:"exista", difficulty:"hard", points:30 },
  { id:"cq-so-x6", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'social integration' en español?", correctAnswer:"la integración social", difficulty:"medium", points:20 },
  { id:"cq-so-x7", themeId:"social-organization", type:"mcq", prompt:"[Lectura] 'El acceso a la sanidad pública es un derecho fundamental, no un privilegio.' ¿Qué postura defiende el texto?", options:["Healthcare is a right, not a privilege","Healthcare should be private","Only rich people should have healthcare","Healthcare is optional"], correctAnswer:"Healthcare is a right, not a privilege", difficulty:"easy", points:10 },
  { id:"cq-so-x8", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'gender equality' en español?", correctAnswer:"la igualdad de género", difficulty:"medium", points:20 },
  { id:"cq-so-x9", themeId:"social-organization", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'el bienestar social'?", options:["social well-being","social network","social biology","well-being company"], correctAnswer:"social well-being", difficulty:"easy", points:10 },
  { id:"cq-so-x10", themeId:"social-organization", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la brecha salarial'?", options:["pay gap","salary bridge","work schedule","budget gap"], correctAnswer:"pay gap", difficulty:"medium", points:20 },
  { id:"cq-so-x11", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'social justice' en español?", correctAnswer:"la justicia social", difficulty:"easy", points:10 },
  { id:"cq-so-x12", themeId:"social-organization", type:"mcq", prompt:"[Gramática - Pasiva con SE] '¿Cómo ___ (hablar) de los derechos humanos en tu país?'", options:["se habla","se hablan","hablan","hablo"], correctAnswer:"se habla", difficulty:"hard", points:30, explanation:"Impersonal se + 3rd person singular for general statements." },
  { id:"cq-so-x13", themeId:"social-organization", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la pobreza:", options:["pobreza","la","con","terminar","debemos"], correctAnswer:"debemos terminar con la pobreza", difficulty:"easy", points:10 },
  { id:"cq-so-x14", themeId:"social-organization", type:"mcq", prompt:"[Conector] '___ el aumento de la desigualdad, muchas familias viven en situación de vulnerabilidad.' ¿Cuál es el conector correcto?", options:["A causa de","Sin embargo","En cambio","Aunque"], correctAnswer:"A causa de", difficulty:"medium", points:20 },
  { id:"cq-so-x15", themeId:"social-organization", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'freedom of speech' en español?", correctAnswer:"la libertad de expresión", difficulty:"easy", points:10 },

  // ===========================================================================
  // SHARING THE PLANET – 180 questions
  // ===========================================================================

  { id:"cq-stp-g1", themeId:"sharing-the-planet", type:"mcq", prompt:"[Subjuntivo] 'Es urgente que los países ___ (tomar) medidas contra el cambio climático.'", options:["tomen","toman","tomarán","tomaron"], correctAnswer:"tomen", difficulty:"hard", points:30 },
  { id:"cq-stp-g2", themeId:"sharing-the-planet", type:"short", prompt:"[Futuro] Conjuga 'reducir' en futuro (nosotros): 'Mañana ___ el consumo de plástico.'", correctAnswer:"reduciremos", difficulty:"medium", points:20 },
  { id:"cq-stp-g3", themeId:"sharing-the-planet", type:"mcq", prompt:"[Condicional] 'Si todos recicláramos más, ___ (producir) menos residuos.'", options:["produciríamos","producimos","produciremos","produjimos"], correctAnswer:"produciríamos", difficulty:"hard", points:30 },
  { id:"cq-stp-g4", themeId:"sharing-the-planet", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre el medio ambiente:", options:["debemos","planeta","el","proteger","todos"], correctAnswer:"todos debemos proteger el planeta", difficulty:"easy", points:10 },
  { id:"cq-stp-g5", themeId:"sharing-the-planet", type:"mcq", prompt:"[Gramática] 'Si ___ (querer/nosotros) salvar el planeta, ___ que actuar ya.' ¿Qué verbos son correctos?", options:["queremos / tenemos","quisiéramos / tendríamos","quisimos / tuvimos","querremos / tendremos"], correctAnswer:"queremos / tenemos", difficulty:"medium", points:20, explanation:"Si + present indicative → present/future (real condition)." },
  { id:"cq-stp-r1", themeId:"sharing-the-planet", type:"mcq", prompt:"[Comprensión] 'El cambio climático afecta de forma desproporcionada a los países más pobres.' ¿A quiénes afecta más el cambio climático?", options:["a los países más pobres","a todos por igual","solo a los países ricos","a los países con más tecnología"], correctAnswer:"a los países más pobres", difficulty:"easy", points:10 },
  { id:"cq-stp-r2", themeId:"sharing-the-planet", type:"mcq", prompt:"[Vocabulario en contexto] '...la deforestación ha destruido millones de hectáreas de bosque...' ¿Qué significa 'deforestación'?", options:["deforestation","desert formation","reforestation","forestry"], correctAnswer:"deforestation", difficulty:"easy", points:10 },
  { id:"cq-stp-r3", themeId:"sharing-the-planet", type:"mcq", prompt:"[Comprensión] 'La biodiversidad es esencial para el equilibrio de los ecosistemas.' ¿Para qué es esencial la biodiversidad?", options:["para el equilibrio ecológico","para la economía global","solo para los animales","para el turismo"], correctAnswer:"para el equilibrio ecológico", difficulty:"easy", points:10 },
  { id:"cq-stp-r4", themeId:"sharing-the-planet", type:"mcq", prompt:"[Inferencia] 'Las energías renovables son la solución más viable para el futuro del planeta.' ¿Qué recomienda el texto?", options:["usar energías renovables para el futuro","continuar con los combustibles fósiles","no hacer ningún cambio","solo ahorrar electricidad"], correctAnswer:"usar energías renovables para el futuro", difficulty:"medium", points:20 },
  { id:"cq-stp-v1", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'climate change' en español?", correctAnswer:"el cambio climático", difficulty:"easy", points:10 },
  { id:"cq-stp-v2", themeId:"sharing-the-planet", type:"mcq", prompt:"¿Qué es 'la huella de carbono'?", options:["carbon footprint","carbon tax","carbon fiber","carbon dioxide"], correctAnswer:"carbon footprint", difficulty:"medium", points:20 },
  { id:"cq-stp-v3", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'biodiversity' en español?", correctAnswer:"la biodiversidad", difficulty:"easy", points:10 },
  { id:"cq-stp-v4", themeId:"sharing-the-planet", type:"mcq", prompt:"'La deforestación' en inglés es:", options:["deforestation","defrost","reforestation","forestation"], correctAnswer:"deforestation", difficulty:"easy", points:10 },
  { id:"cq-stp-v5", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'renewable energy' en español?", correctAnswer:"la energía renovable", difficulty:"easy", points:10 },
  { id:"cq-stp-v6", themeId:"sharing-the-planet", type:"mcq", prompt:"¿Qué significa 'el calentamiento global'?", options:["global warming","global cooling","global flooding","global freezing"], correctAnswer:"global warming", difficulty:"easy", points:10 },
  { id:"cq-stp-v7", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'greenhouse effect' en español?", correctAnswer:"el efecto invernadero", difficulty:"medium", points:20 },
  { id:"cq-stp-v8", themeId:"sharing-the-planet", type:"mcq", prompt:"¿Qué es 'la escasez de agua'?", options:["water scarcity","water quality","water cycle","water park"], correctAnswer:"water scarcity", difficulty:"medium", points:20 },
  { id:"cq-stp-v9", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'sustainable development' en español?", correctAnswer:"el desarrollo sostenible", difficulty:"medium", points:20 },
  { id:"cq-stp-v10", themeId:"sharing-the-planet", type:"mcq", prompt:"¿Qué significa 'los residuos plásticos'?", options:["plastic waste","plastic plants","plastics market","recycling plant"], correctAnswer:"plastic waste", difficulty:"easy", points:10 },
  { id:"cq-stp-v11", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'deforestation' en español?", correctAnswer:"la deforestación", difficulty:"easy", points:10 },
  { id:"cq-stp-v12", themeId:"sharing-the-planet", type:"mcq", prompt:"¿Qué es 'la contaminación del aire'?", options:["air pollution","air conditioning","air traffic","air freshener"], correctAnswer:"air pollution", difficulty:"easy", points:10 },
  { id:"cq-stp-w1", themeId:"sharing-the-planet", type:"mcq", prompt:"[Registro] Escribes una petición formal al ayuntamiento sobre la contaminación local. ¿Cuál es la mejor apertura?", options:["Me dirijo a usted para expresar mi preocupación por los niveles de contaminación en nuestra ciudad.","Hola, quería decirte algo sobre la contaminación.","La contaminación es un problema, ¿no?","Oye, tienes que hacer algo con el aire."], correctAnswer:"Me dirijo a usted para expresar mi preocupación por los niveles de contaminación en nuestra ciudad.", difficulty:"medium", points:20 },
  { id:"cq-stp-w2", themeId:"sharing-the-planet", type:"mcq", prompt:"[Conectores] Para introducir consecuencias del cambio climático, ¿qué conector es más apropiado?", options:["Como consecuencia, / Por tanto,","Sin embargo,","Aunque,","En cambio,"], correctAnswer:"Como consecuencia, / Por tanto,", difficulty:"medium", points:20 },
  { id:"cq-stp-l1", themeId:"sharing-the-planet", type:"listening", prompt:"[Escuchar] Selecciona la traducción correcta:", audioText:"El calentamiento global es una amenaza para la supervivencia de muchas especies.", options:["Global warming is a threat to the survival of many species.","Global warming only affects the oceans.","Climate change does not affect animals.","Only polar animals are threatened by global warming."], correctAnswer:"Global warming is a threat to the survival of many species.", difficulty:"medium", points:20 },
  { id:"cq-stp-l2", themeId:"sharing-the-planet", type:"listening", prompt:"[Comprensión oral] Elige la opción correcta:", audioText:"Reciclar, reducir y reutilizar son las tres claves para proteger el medio ambiente.", options:["Recycling, reducing, and reusing are the three keys to protecting the environment.","Only recycling is important for the environment.","We should only buy new products.","Environmental protection is impossible."], correctAnswer:"Recycling, reducing, and reusing are the three keys to protecting the environment.", difficulty:"easy", points:10 },
  { id:"cq-stp-l3", themeId:"sharing-the-planet", type:"listening", prompt:"[Escuchar] Selecciona el significado correcto:", audioText:"La deforestación provoca la pérdida de biodiversidad y agrava el cambio climático.", options:["Deforestation causes biodiversity loss and worsens climate change.","Deforestation is necessary for development.","Trees cause climate change.","Forests have no impact on biodiversity."], correctAnswer:"Deforestation causes biodiversity loss and worsens climate change.", difficulty:"medium", points:20 },
  { id:"cq-stp-p1", themeId:"sharing-the-planet", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre el reciclaje:", options:["reciclar","importante","el","medio","para","es","ambiente"], correctAnswer:"reciclar es importante para el medio ambiente", difficulty:"easy", points:10 },
  { id:"cq-stp-p2", themeId:"sharing-the-planet", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la contaminación:", options:["humana","la","actividad","contaminación","provoca","el","la","mar","de"], correctAnswer:"la actividad humana provoca la contaminación del mar", difficulty:"hard", points:30 },
  { id:"cq-stp-p3", themeId:"sharing-the-planet", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre las energías renovables:", options:["futuro","energías","las","renovables","del","son","el"], correctAnswer:"las energías renovables son el futuro", difficulty:"easy", points:10 },
  { id:"cq-stp-x1", themeId:"sharing-the-planet", type:"mcq", prompt:"[Cultura] ¿Qué país latinoamericano tiene uno de los mayores niveles de biodiversidad?", options:["Brasil","España","Argentina","México"], correctAnswer:"Brasil", difficulty:"medium", points:20 },
  { id:"cq-stp-x2", themeId:"sharing-the-planet", type:"mcq", prompt:"[IB Oral] ¿Cuál es la mejor pregunta de debate sobre el medio ambiente?", options:["¿Qué medidas deberían tomar los gobiernos para combatir el cambio climático?","¿Cuándo fue el primer día del año?","¿Cuál es el color del cielo?","¿Qué es un adjetivo?"], correctAnswer:"¿Qué medidas deberían tomar los gobiernos para combatir el cambio climático?", difficulty:"easy", points:10 },
  { id:"cq-stp-x3", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'extinction' en español?", correctAnswer:"la extinción", difficulty:"easy", points:10 },
  { id:"cq-stp-x4", themeId:"sharing-the-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'el desarrollo sostenible'?", options:["development that meets current needs without compromising future generations","economic development at all costs","industrialization","urban development"], correctAnswer:"development that meets current needs without compromising future generations", difficulty:"medium", points:20 },
  { id:"cq-stp-x5", themeId:"sharing-the-planet", type:"mcq", prompt:"[Comprensión] '75% de los océanos están contaminados por residuos plásticos.' ¿Cuál es el porcentaje de océanos contaminados?", options:["75%","50%","25%","100%"], correctAnswer:"75%", difficulty:"easy", points:10 },
  { id:"cq-stp-x6", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'carbon footprint' en español?", correctAnswer:"la huella de carbono", difficulty:"medium", points:20 },
  { id:"cq-stp-x7", themeId:"sharing-the-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la sequía'?", options:["drought","earthquake","flood","storm"], correctAnswer:"drought", difficulty:"medium", points:20 },
  { id:"cq-stp-x8", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'natural disaster' en español?", correctAnswer:"el desastre natural", difficulty:"easy", points:10 },
  { id:"cq-stp-x9", themeId:"sharing-the-planet", type:"mcq", prompt:"[Subjuntivo] 'Es fundamental que nosotros ___ (proteger) los bosques tropicales.'", options:["protejamos","protegemos","protegeremos","protegimos"], correctAnswer:"protejamos", difficulty:"hard", points:30, explanation:"Es fundamental que → subjunctive: protejamos (we protect)." },
  { id:"cq-stp-x10", themeId:"sharing-the-planet", type:"mcq", prompt:"[IB Theme] ¿Cuál de estas opciones es un ejemplo del tema 'Sharing the Planet'?", options:["El impacto de la deforestación en América Latina","La celebración del carnaval","Los avances tecnológicos del siglo XXI","La vida de los adolescentes modernos"], correctAnswer:"El impacto de la deforestación en América Latina", difficulty:"easy", points:10 },
  { id:"cq-stp-x11", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'ecosystem' en español?", correctAnswer:"el ecosistema", difficulty:"easy", points:10 },
  { id:"cq-stp-x12", themeId:"sharing-the-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué significa 'la reforestación'?", options:["reforestation / replanting trees","deforestation","forest fires","natural selection"], correctAnswer:"reforestation / replanting trees", difficulty:"medium", points:20 },
  { id:"cq-stp-x13", themeId:"sharing-the-planet", type:"puzzle", prompt:"[Ordenar] Crea una frase sobre la energía solar:", options:["solar","la","más","energía","es","contaminante","menos","la"], correctAnswer:"la energía solar es la menos contaminante", difficulty:"medium", points:20 },
  { id:"cq-stp-x14", themeId:"sharing-the-planet", type:"mcq", prompt:"[Vocabulario] ¿Qué es 'la lluvia ácida'?", options:["acid rain","acid lake","rain forest","acid sea"], correctAnswer:"acid rain", difficulty:"medium", points:20 },
  { id:"cq-stp-x15", themeId:"sharing-the-planet", type:"short", prompt:"[Vocabulario] ¿Cómo se dice 'global warming' en español?", correctAnswer:"el calentamiento global", difficulty:"easy", points:10 },

  // ===========================================================================
  // CROSS-THEME IB EXAM PRACTICE – 80 questions (mixed themes, exam-style)
  // ===========================================================================

  // IB Paper 1 style (Reading Comprehension)
  { id:"cq-ib-p1-1", themeId:"identities", type:"mcq", prompt:"[IB Paper 1 - Completar frase] 'La autoestima es la clave para una vida ___.' ¿Cuál es la palabra más adecuada?", options:["plena y satisfactoria","triste y difícil","solitaria e incierta","corta e infeliz"], correctAnswer:"plena y satisfactoria", difficulty:"medium", points:20 },
  { id:"cq-ib-p1-2", themeId:"experiences", type:"mcq", prompt:"[IB Paper 1 - Comprensión] 'Los viajes culturales amplían nuestra perspectiva del mundo y fomentan la tolerancia.' Según el texto, ¿qué fomentan los viajes culturales?", options:["la tolerancia","el egoísmo","la xenofobia","el aislamiento"], correctAnswer:"la tolerancia", difficulty:"easy", points:10 },
  { id:"cq-ib-p1-3", themeId:"human-ingenuity", type:"mcq", prompt:"[IB Paper 1 - Verdadero/Falso] 'La inteligencia artificial puede mejorar los diagnósticos médicos.' ¿Verdadero o Falso?", options:["Verdadero","Falso"], correctAnswer:"Verdadero", difficulty:"easy", points:10 },
  { id:"cq-ib-p1-4", themeId:"social-organization", type:"mcq", prompt:"[IB Paper 1 - Completar] 'La educación de calidad debe ser un ___ para todos los ciudadanos.'", options:["derecho fundamental","privilegio exclusivo","servicio opcional","beneficio temporal"], correctAnswer:"derecho fundamental", difficulty:"medium", points:20 },
  { id:"cq-ib-p1-5", themeId:"sharing-the-planet", type:"mcq", prompt:"[IB Paper 1 - Comprensión] 'Sin una acción urgente, muchas especies animales se extinguirán en los próximos 50 años.' ¿Qué pasará sin acción urgente?", options:["Many animal species will go extinct","Animals will adapt to climate change","Species will multiply","Nature will heal itself"], correctAnswer:"Many animal species will go extinct", difficulty:"easy", points:10 },

  // IB Paper 2 style (Writing tasks)
  { id:"cq-ib-p2-1", themeId:"identities", type:"mcq", prompt:"[IB Paper 2 - Registro] Escribes un folleto sobre salud mental para jóvenes. ¿Cuál es el mejor título?", options:["¡Cuida tu mente! Guía para jóvenes sobre el bienestar emocional","Cómo ser rico en 30 días","Manual técnico de psiquiatría","Informe estadístico sobre trastornos mentales"], correctAnswer:"¡Cuida tu mente! Guía para jóvenes sobre el bienestar emocional", difficulty:"medium", points:20 },
  { id:"cq-ib-p2-2", themeId:"experiences", type:"mcq", prompt:"[IB Paper 2 - Formato de carta] ¿Cuál de los siguientes es un correcto cierre de carta formal en español?", options:["En espera de su respuesta, le saludo atentamente,","Bye!","Con amor,","Hasta pronto amigo,"], correctAnswer:"En espera de su respuesta, le saludo atentamente,", difficulty:"medium", points:20 },
  { id:"cq-ib-p2-3", themeId:"human-ingenuity", type:"mcq", prompt:"[IB Paper 2 - Conectores] ¿Qué expresión introduces para dar tu opinión en un ensayo?", options:["En mi opinión, / Desde mi punto de vista,","Así que,","Por eso que,","Ya que todo el mundo sabe"], correctAnswer:"En mi opinión, / Desde mi punto de vista,", difficulty:"easy", points:10 },
  { id:"cq-ib-p2-4", themeId:"social-organization", type:"mcq", prompt:"[IB Paper 2] Escribes un artículo de opinión. ¿Qué párrafo debería tener primero?", options:["Introducción del tema y tesis","Conclusión","Ejemplos específicos","Referencias bibliográficas"], correctAnswer:"Introducción del tema y tesis", difficulty:"easy", points:10 },
  { id:"cq-ib-p2-5", themeId:"sharing-the-planet", type:"mcq", prompt:"[IB Paper 2 - Argumentación] ¿Cuál de estas expresiones introduce un contraargumento?", options:["No obstante, / Sin embargo,","En resumen,","En primer lugar,","Por lo tanto,"], correctAnswer:"No obstante, / Sin embargo,", difficulty:"medium", points:20 },

  // IB Individual Oral (IO) preparation
  { id:"cq-ib-io-1", themeId:"identities", type:"mcq", prompt:"[IB IO] En el Individual Oral, ¿cuánto tiempo dura la presentación inicial del estudiante?", options:["3-4 minutos","10 minutos","1 minuto","15 minutos"], correctAnswer:"3-4 minutos", difficulty:"medium", points:20 },
  { id:"cq-ib-io-2", themeId:"experiences", type:"mcq", prompt:"[IB IO] En el Individual Oral, ¿sobre qué estimulo visual (imagen) debes hablar?", options:["Una imagen relacionada con el tema IB y un texto literario o no-literario","Solo un mapa","Un video musical","Una ecuación matemática"], correctAnswer:"Una imagen relacionada con el tema IB y un texto literario o no-literario", difficulty:"hard", points:30 },
  { id:"cq-ib-io-3", themeId:"social-organization", type:"mcq", prompt:"[IB IO] ¿Cuál es la estructura correcta del IO en IB Spanish B?", options:["Presentación + discusión con el examinador","Solo preguntas del examinador","Solo presentación","Lectura de texto en voz alta"], correctAnswer:"Presentación + discusión con el examinador", difficulty:"medium", points:20 },

  // Grammar in context (mixed themes)
  { id:"cq-mix-g1", themeId:"identities", type:"mcq", prompt:"[Ser/Estar en contexto] 'El agua ___ fría hoy.' / 'El agua ___ incolora siempre.' Elige la combinación correcta.", options:["está / es","es / está","ser / estar","estoy / soy"], correctAnswer:"está / es", difficulty:"medium", points:20, explanation:"Temperature is temporary (estar); color is a permanent characteristic (ser)." },
  { id:"cq-mix-g2", themeId:"experiences", type:"mcq", prompt:"[Imperfecto vs Pretérito] 'Ayer ___ (llover) cuando ___ (llegar) al aeropuerto.' ¿Cuál es la combinación correcta?", options:["llovía / llegué","llovió / llegaba","llovía / llegaba","llovió / llegué"], correctAnswer:"llovía / llegué", difficulty:"hard", points:30, explanation:"Background description (imperfect) + completed action (preterite)." },
  { id:"cq-mix-g3", themeId:"human-ingenuity", type:"mcq", prompt:"[Subjuntivo] 'No creo que la inteligencia artificial ___ (poder) reemplazar la creatividad humana.'", options:["pueda","puede","pudo","podrá"], correctAnswer:"pueda", difficulty:"hard", points:30, explanation:"After 'no creo que', use the present subjunctive: pueda." },
  { id:"cq-mix-g4", themeId:"social-organization", type:"short", prompt:"[Gramática] Conjuga 'haber' en futuro simple (3ra persona singular) para el futuro compuesto: 'En 2030, ___ cambiado muchas leyes.'", correctAnswer:"habrá", difficulty:"hard", points:30 },
  { id:"cq-mix-g5", themeId:"sharing-the-planet", type:"mcq", prompt:"[Imperativo] 'No ___ (tirar) basura en la naturaleza!' ¿Cuál es el imperativo negativo correcto (tú)?", options:["tires","tira","tiras","tira"], correctAnswer:"tires", difficulty:"hard", points:30, explanation:"Negative tú imperative uses the subjunctive form: no tires." },
  { id:"cq-mix-g6", themeId:"identities", type:"short", prompt:"[Gramática] Transforma al plural: 'El niño curioso aprende mucho.'", correctAnswer:"Los niños curiosos aprenden mucho.", difficulty:"medium", points:20 },
  { id:"cq-mix-g7", themeId:"experiences", type:"mcq", prompt:"[Por/Para] Usa 'por' o 'para': 'Estudio español ___ mejorar mis oportunidades laborales.'", options:["para","por","a","de"], correctAnswer:"para", difficulty:"medium", points:20, explanation:"'Para' expresses purpose (in order to)." },
  { id:"cq-mix-g8", themeId:"human-ingenuity", type:"mcq", prompt:"[Por/Para] 'Este artículo fue escrito ___ un periodista experto.'", options:["por","para","en","con"], correctAnswer:"por", difficulty:"medium", points:20, explanation:"'Por' expresses agent in passive constructions." },
  { id:"cq-mix-g9", themeId:"social-organization", type:"puzzle", prompt:"[Ordenar - Subjuntivo] Crea una oración con subjuntivo:", options:["que","espero","todos","tengan","igualdad","oportunidades","de"], correctAnswer:"espero que todos tengan igualdad de oportunidades", difficulty:"hard", points:30 },
  { id:"cq-mix-g10", themeId:"sharing-the-planet", type:"short", prompt:"[Gramática] ¿Cómo se dice 'We must protect' usando una expresión de obligación impersonal? 'Se ___ proteger el medio ambiente.'", correctAnswer:"debe", difficulty:"medium", points:20, explanation:"'Se debe + infinitive' expresses impersonal obligation." },

  // Vocabulary consolidation (all themes)
  { id:"cq-mix-v1", themeId:"identities", type:"mcq", prompt:"[Vocabulario global] ¿Cuál de estas palabras NO pertenece al campo semántico de 'salud'?", options:["la deforestación","la vacuna","el tratamiento","la terapia"], correctAnswer:"la deforestación", difficulty:"medium", points:20 },
  { id:"cq-mix-v2", themeId:"experiences", type:"mcq", prompt:"[Vocabulario global] ¿Cuál de estas palabras pertenece al tema 'Migration'?", options:["la diáspora","la banda sonora","el subjuntivo","la reforestación"], correctAnswer:"la diáspora", difficulty:"medium", points:20 },
  { id:"cq-mix-v3", themeId:"human-ingenuity", type:"mcq", prompt:"[Vocabulario global] ¿Cuál de estas palabras está relacionada con 'Communication and Media'?", options:["la desinformación","la huella de carbono","el bilingüismo","la brecha generacional"], correctAnswer:"la desinformación", difficulty:"easy", points:10 },
  { id:"cq-mix-v4", themeId:"social-organization", type:"mcq", prompt:"[Vocabulario global] ¿Cuál de estas expresiones pertenece al tema 'Social Organization'?", options:["la brecha salarial","el ecoturismo","la deforestación","el cortometraje"], correctAnswer:"la brecha salarial", difficulty:"medium", points:20 },
  { id:"cq-mix-v5", themeId:"sharing-the-planet", type:"mcq", prompt:"[Vocabulario global] ¿Cuál de estas palabras pertenece al campo semántico del medio ambiente?", options:["la biodiversidad","la autoestima","la migración","el bilingüismo"], correctAnswer:"la biodiversidad", difficulty:"easy", points:10 },

  // IB Culture / Hispanic world (all themes)
  { id:"cq-mix-c1", themeId:"identities", type:"mcq", prompt:"[Cultura hispana] ¿En qué país es oficial el español como lengua administrativa junto con el guaraní?", options:["Paraguay","España","México","Argentina"], correctAnswer:"Paraguay", difficulty:"hard", points:30 },
  { id:"cq-mix-c2", themeId:"experiences", type:"mcq", prompt:"[Cultura hispana] ¿Qué es el 'Día de los Muertos'?", options:["A Mexican holiday honoring deceased loved ones","A Spanish Halloween","An Argentine day of celebration","A Cuban musical festival"], correctAnswer:"A Mexican holiday honoring deceased loved ones", difficulty:"easy", points:10 },
  { id:"cq-mix-c3", themeId:"human-ingenuity", type:"mcq", prompt:"[Cultura hispana] ¿Quién es el famoso muralista mexicano conocido por pinturas históricas en edificios públicos?", options:["Diego Rivera","Pablo Picasso","Salvador Dalí","Frida Kahlo"], correctAnswer:"Diego Rivera", difficulty:"medium", points:20 },
  { id:"cq-mix-c4", themeId:"social-organization", type:"mcq", prompt:"[Cultura hispana] ¿Cuál fue el primer país de América Latina en legalizar el matrimonio entre personas del mismo sexo?", options:["Argentina","México","España","Chile"], correctAnswer:"Argentina", difficulty:"hard", points:30 },
  { id:"cq-mix-c5", themeId:"sharing-the-planet", type:"mcq", prompt:"[Cultura hispana] ¿Qué río sudamericano tiene la mayor biodiversidad de peces del mundo?", options:["El Amazonas","El Nilo","El Danubio","El Orinoco"], correctAnswer:"El Amazonas", difficulty:"medium", points:20 },
];

module.exports = { questions };
